('de', 'finalCta.cta2', '7 Tage kostenlos testen. Keine Kreditkarte erforderlich.', NOW()),
('de', 'finalCta.trust1', 'Sofortige ChiosBox ID', NOW()),
('de', 'finalCta.trust2', 'Tür-zu-Tür-Lieferung', NOW()),
('de', 'finalCta.trust3', 'Sichere Zahlung', NOW()),
('de', 'pkgReq.tag', 'Schnelle Bewerbung', NOW()),
('de', 'pkgReq.title', 'Paketanfrage erstellen', NOW()),
('de', 'pkgReq.description', 'Benachrichtigen Sie uns über Ihr Paket aus der Türkei, lassen Sie es sicher in unserem Lager empfangen.', NOW()),
('de', 'pkgReq.ready', 'Bereit in 3 Schritten', NOW()),
('de', 'pkgReq.readyDesc', 'Geben Sie Ihre Daten ein, lassen Sie uns Ihr Paket verfolgen', NOW()),
('de', 'pkgReq.success.title', 'Ihre Anfrage wurde empfangen!', NOW()),
('de', 'pkgReq.success.desc', 'Ihre Paketbenachrichtigung wurde gespeichert. Wir benachrichtigen Sie, wenn es aus der Türkei in unserem Lager ankommt.', NOW()),
('de', 'pkgReq.newRequest', 'Neue Anfrage', NOW()),
('de', 'pkgReq.registerTrack', 'Registrieren & Verfolgen', NOW()),
('de', 'pkgReq.step1.title', 'Persönliche Informationen', NOW()),
('de', 'pkgReq.fullName', 'Vollständiger Name *', NOW()),
('de', 'pkgReq.fullNamePlaceholder', 'Ihr vollständiger Name', NOW()),
('de', 'pkgReq.email', 'E-Mail *', NOW()),
('de', 'pkgReq.phone', 'Telefon', NOW()),
('de', 'pkgReq.step2.title', 'Versandinformationen', NOW()),
('de', 'pkgReq.carrier', 'Spediteur *', NOW()),
('de', 'pkgReq.trackingNo', 'Sendungsnummer *', NOW()),
('de', 'pkgReq.trackingPlaceholder', 'Ihre Sendungsnummer', NOW()),
('de', 'pkgReq.content', 'Paketinhalt *', NOW()),
('de', 'pkgReq.contentPlaceholder', 'Was ist in Ihrem Paket?', NOW()),
('de', 'pkgReq.estimatedValue', 'Geschätzter Wert (€)', NOW()),
('de', 'pkgReq.step3.title', 'Zusammenfassung & Genehmigung', NOW()),
('de', 'pkgReq.summaryName', 'Vollständiger Name', NOW()),
('de', 'pkgReq.summaryEmail', 'E-Mail', NOW()),
('de', 'pkgReq.summaryPhone', 'Telefon', NOW()),
('de', 'pkgReq.summaryCarrier', 'Versand', NOW()),
('de', 'pkgReq.summaryTracking', 'Sendungsnummer', NOW()),
('de', 'pkgReq.summaryContent', 'Inhalt', NOW()),
('de', 'pkgReq.summaryValue', 'Geschätzter Wert', NOW()),
('de', 'pkgReq.notes', 'Notizen', NOW()),
('de', 'pkgReq.notesPlaceholder', 'Möchten Sie eine Notiz hinzufügen?', NOW()),
('de', 'pkgReq.info', 'Ihre Paketbenachrichtigung wird in unserem Lager bearbeitet. Durch die Registrierung können Sie Ihre Pakete im Panel verfolgen und von Konsolidierungs- und Lieferoptionen profitieren.', NOW()),
('de', 'pkgReq.back', 'Zurück', NOW()),
('de', 'pkgReq.continue', 'Weiter', NOW()),
('de', 'pkgReq.submit', 'Anfrage senden', NOW()),
('de', 'pkgReq.carrier.yurtici', 'Yurtiçi Kargo', NOW()),
('de', 'pkgReq.carrier.aras', 'Aras Kargo', NOW()),
('de', 'pkgReq.carrier.mng', 'MNG Kargo', NOW()),
('de', 'pkgReq.carrier.ptt', 'PTT Kargo', NOW()),
('de', 'pkgReq.carrier.surat', 'Sürat Kargo', NOW()),
('de', 'pkgReq.carrier.diger', 'Sonstige', NOW()),
('de', 'dashboard.title', 'Admin-Dashboard', NOW()),
('de', 'dashboard.welcome', 'Willkommen, {name}', NOW()),
('de', 'dashboard.totalPackages', 'Gesamtpakete', NOW()),
('de', 'dashboard.inWarehouse', 'Im Lager', NOW()),
('de', 'dashboard.last7Days', 'Letzte 7 Tage', NOW()),
('de', 'dashboard.newPackages', 'neue Pakete', NOW()),
('de', 'dashboard.weeklyRevenue', 'Wocheneinnahmen', NOW()),
('de', 'dashboard.statusDistribution', 'Statusverteilung', NOW()),
('de', 'dashboard.recentActivity', 'Letzte Aktivitäten', NOW()),
('de', 'dashboard.unknown', 'Unbekannt', NOW()),
('de', 'dashboard.demurrageAlert', 'Verzugswarnung', NOW()),
('de', 'dashboard.demurrageDesc', '{count} Pakete über 14 Tage', NOW()),
('de', 'dashboard.pendingInvoices', 'Ausstehende Rechnungen', NOW()),
('de', 'dashboard.pendingInvoiceDesc', '{count} Rechnungen warten auf Zahlung', NOW()),
('de', 'dashboard.shelfUsage', 'Regalnutzung', NOW()),
('de', 'dashboard.quickActions', 'Schnellaktionen', NOW()),
('de', 'status.beklemede', 'Ausstehend', NOW()),
('de', 'status.yolda', 'Unterwegs', NOW()),
('de', 'status.depoda', 'Im Lager', NOW()),
('de', 'status.birlestirildi', 'Zusammengeführt', NOW()),
('de', 'status.teslimEdildi', 'Zugestellt', NOW()),
('de', 'action.kabul', 'Annahme', NOW()),
('de', 'actions.delivery', 'Zustellung', NOW()),
('de', 'action.delay', 'Verzug', NOW()),
('de', 'action.packages', 'Pakete', NOW()),
('de', 'action.faturalar', 'Rechnungen', NOW()),
('de', 'action.musteriler', 'Kunden', NOW()),
('de', 'packages.title', 'Pakete', NOW()),
('de', 'packages.count', '{total} Pakete', NOW()),
('de', 'packages.searchPlaceholder', 'Nach Sendungsnummer suchen...', NOW()),
('de', 'packages.allStatuses', 'Alle Status', NOW()),
('de', 'packages.notFound', 'Paket nicht gefunden', NOW()),
('de', 'packages.daysAgo', '{n} Tage', NOW()),
('de', 'packages.previous', 'Vorherige', NOW()),
('de', 'packages.next', 'Nächste', NOW()),
('de', 'packages.deleteConfirm', 'Sind Sie sicher, dass Sie dieses Paket löschen möchten?', NOW()),
('de', 'packages.detail.customer', 'Kunde', NOW()),
('de', 'packages.detail.carrier', 'Spediteur', NOW()),
('de', 'packages.detail.trackingNo', 'Sendungsnummer', NOW()),
('de', 'packages.detail.shelf', 'Regal', NOW()),
('de', 'packages.detail.arrival', 'Ankunft', NOW()),
('de', 'packages.detail.notification', 'Benachrichtigung', NOW()),
('de', 'packages.detail.inWarehouse', 'Im Lager', NOW()),
('de', 'packages.detail.weight', 'Gewicht', NOW()),
('de', 'packages.detail.dimensions', 'Abmessungen', NOW()),
('de', 'packages.detail.demurrageFee', 'Verzugsgebühr', NOW()),
('de', 'packages.detail.notes', 'Notiz', NOW()),
('de', 'packages.detail.updateStatus', 'Status aktualisieren', NOW()),
('de', 'packages.detail.delete', 'Paket löschen', NOW()),
('de', 'packages.detail.cancel', 'Abbrechen', NOW()),
('de', 'packages.detail.deleting', 'Wird gelöscht...', NOW()),
('de', 'packages.detail.confirmDelete', 'Ja, Löschen', NOW()),
('de', 'customers.title', 'Kunden', NOW()),
('de', 'customers.count', '{total} Kunden', NOW()),
('de', 'customers.searchPlaceholder', 'Nach Name, E-Mail oder ChiosBox ID suchen...', NOW()),
('de', 'customers.notFound', 'Kunde nicht gefunden', NOW()),
('de', 'customers.packageCount', '{n} Pakete', NOW()),
('de', 'customers.pending', 'ausstehend', NOW()),
('de', 'customers.previous', 'Vorherige', NOW()),
('de', 'customers.next', 'Nächste', NOW()),
('de', 'invoices.title', 'Rechnungen', NOW()),
('de', 'invoices.count', '{total} Rechnungen', NOW()),
('de', 'invoices.newInvoice', '+ Neue Rechnung', NOW()),
('de', 'invoices.all', 'Alle', NOW()),
('de', 'invoices.pending', 'Ausstehend', NOW()),
('de', 'invoices.paid', 'Bezahlt', NOW()),
('de', 'invoices.cancelled', 'Storniert', NOW()),
('de', 'invoices.notFound', 'Rechnung nicht gefunden', NOW()),
('de', 'invoices.acceptFee', 'Annahme: €{amount}', NOW()),
('de', 'invoices.consolidationFee', 'Zusammenführung: €{amount}', NOW()),
('de', 'invoices.demurrageFee', 'Verzug: €{amount}', NOW()),
('de', 'invoices.packageCount', '{n} Pakete', NOW()),
('de', 'invoices.previous', 'Vorherige', NOW()),
('de', 'invoices.next', 'Nächste', NOW()),
('de', 'invoices.createModal.title', 'Neue Rechnung', NOW()),
('de', 'invoices.createModal.customer', 'Kunde', NOW()),
('de', 'invoices.createModal.selectCustomer', 'Kunden auswählen', NOW()),
('de', 'invoices.createModal.packetsToBill', 'Zu berechnende Pakete', NOW()),
('de', 'invoices.createModal.noUnbilled', 'Keine unberechneten Pakete gefunden', NOW()),
('de', 'invoices.createModal.consolidationFee', 'Zusammenführungsgebühr', NOW()),
('de', 'invoices.createModal.acceptFee', 'Annahmegebühr ({count} Pakete × €{fee})', NOW()),
('de', 'invoices.createModal.demurrageFee', 'Verzugsgebühr', NOW()),
('de', 'invoices.createModal.consolidationLine', 'Zusammenführungsgebühr', NOW()),
('de', 'invoices.createModal.total', 'Gesamt', NOW()),
('de', 'invoices.createModal.creating', 'Wird erstellt...', NOW()),
('de', 'invoices.createModal.createButton', 'Rechnung erstellen (€{amount})', NOW()),
('de', 'invoices.createModal.selectCustomerError', 'Kunden auswählen', NOW()),
('de', 'invoices.createModal.selectPackageError', 'Wählen Sie mindestens ein Paket', NOW()),
('de', 'invoices.createModal.createError', 'Rechnung konnte nicht erstellt werden', NOW()),
('de', 'invoices.detail.customer', 'Kunde', NOW()),
('de', 'invoices.detail.date', 'Datum', NOW()),
('de', 'invoices.detail.paymentDate', 'Zahlungsdatum', NOW()),
('de', 'invoices.detail.acceptFee', 'Annahmegebühr', NOW()),
('de', 'invoices.detail.consolidationFee', 'Zusammenführungsgebühr', NOW()),
('de', 'invoices.detail.demurrageFee', 'Verzugsgebühr', NOW()),
('de', 'invoices.detail.total', 'Gesamt', NOW()),
('de', 'invoices.detail.packets', 'Pakete ({count})', NOW()),
('de', 'invoices.detail.markPaid', 'Als bezahlt markieren', NOW()),
('de', 'invoices.detail.cancel', 'Stornieren', NOW()),
('de', 'invoices.detail.undoCancel', 'Storno rückgängig machen', NOW()),
('de', 'invoices.detail.undoPayment', 'Zahlung rückgängig machen', NOW()),
('de', 'intake.title', 'Paketannahme', NOW()),
('de', 'intake.newIntake', 'Neue Annahme', NOW()),
('de', 'intake.error.search', 'Suche fehlgeschlagen', NOW()),
('de', 'intake.error.searchPaket', 'Fehler beim Suchen nach dem Paket', NOW()),
('de', 'intake.error.saveFailed', 'Speichern fehlgeschlagen', NOW()),
('de', 'intake.error.generic', 'Ein Fehler ist aufgetreten', NOW()),
('de', 'intake.barcodeInstruction', 'Barcode der Kamera zeigen oder manuell eingeben', NOW()),
('de', 'intake.barcodeLabel', 'Barcode / Sendungsnummer', NOW()),
('de', 'intake.barcodePlaceholder', 'Barcode scannen oder eingeben', NOW()),
('de', 'intake.notFound', 'Kein Paket für diese Sendungsnummer gefunden', NOW()),
('de', 'intake.customer', 'Kunde', NOW()),
('de', 'intake.content', 'Inhalt', NOW()),
('de', 'intake.notes', 'Notiz: {text}', NOW()),
('de', 'intake.shelfAssignment', 'Regalzuweisung', NOW()),
('de', 'intake.saving', 'Wird gespeichert...', NOW()),
('de', 'intake.save', 'SPEICHERN', NOW()),
('de', 'intake.saved', 'Gespeichert!', NOW()),
('de', 'intake.shelfPrefix', 'Regal: {shelf}', NOW()),
('de', 'intake.unknown', 'Unbekannt', NOW()),
('de', 'pickup.title', 'Zustellung', NOW()),
('de', 'pickup.newDelivery', 'Neue Zustellung', NOW()),
('de', 'pickup.error.search', 'Suche fehlgeschlagen', NOW()),
('de', 'pickup.error.searchPaket', 'Fehler beim Suchen nach dem Paket', NOW()),
('de', 'pickup.error.codeFailed', 'Code konnte nicht generiert werden', NOW()),
('de', 'pickup.error.generic', 'Ein Fehler ist aufgetreten', NOW()),
('de', 'pickup.error.deliveryFailed', 'Zustellung fehlgeschlagen', NOW()),
('de', 'pickup.inputPlaceholder', 'Sendungsnummer oder CBX ID eingeben', NOW()),
('de', 'pickup.notFound', 'Kein Paket für diesen Code gefunden', NOW()),
('de', 'pickup.toDeliver', 'Zu liefern', NOW()),
('de', 'pickup.verificationTitle', 'Verifizierungscode', NOW()),
('de', 'pickup.verificationDesc', 'Einmalcode an Kunden senden', NOW()),
('de', 'pickup.sending', 'Wird gesendet...', NOW()),
('de', 'pickup.sendCode', 'Code senden', NOW()),
('de', 'pickup.mockCodeLabel', 'Verifizierungscode (Mock)', NOW()),
('de', 'pickup.mockCodeNote', 'Wird per echter SMS an den Kunden gesendet', NOW()),
('de', 'pickup.customerCode', 'Code des Kunden', NOW()),
('de', 'pickup.codePlaceholder', '6-stelliger Code', NOW()),
('de', 'pickup.delivering', 'Wird zugestellt...', NOW()),
('de', 'pickup.deliver', 'ZUSTELLEN', NOW()),
('de', 'pickup.delivered', 'Zugestellt!', NOW()),
('de', 'demurrage.title', 'Verzugsradar', NOW()),
('de', 'demurrage.subtitle', 'Verfolgen Sie Pakete, die die Lagerzeit überschreiten', NOW()),
('de', 'demurrage.normal', 'Normal (≤14 Tage)', NOW()),
('de', 'demurrage.delay', 'Verzug (15-29 Tage)', NOW()),
('de', 'demurrage.abandonedZone', 'Aufgegeben (30+ Tage)', NOW()),
('de', 'demurrage.abandoned', 'Aufgegeben', NOW()),
('de', 'demurrage.unknown', 'Unbekannt', NOW()),
('de', 'demurrage.shelfPrefix', 'Regal {shelf}', NOW()),
('de', 'demurrage.arrival', 'Ankunft: {date}', NOW()),
('de', 'demurrage.daysLabel', '{n} Tage', NOW()),
('de', 'demurrage.demurrageFee', 'Verzugsgebühr', NOW()),
('de', 'demurrage.error.applyFailed', 'Verzugsgebühr konnte nicht angewendet werden', NOW()),
('de', 'demurrage.cancel', 'Abbrechen', NOW()),
('de', 'demurrage.applyAmount', '€{amount} anwenden', NOW()),
('de', 'demurrage.invoiceCreated', 'Rechnung erstellt!', NOW()),
('de', 'demurrage.applyFeeButton', 'Verzugsgebühr anwenden (€{amount})', NOW()),
('de', 'demurrage.confirmDelete', 'Ja, Löschen', NOW()),
('de', 'demurrage.discard', 'Entsorgen', NOW()),
('de', 'demurrage.allClear', 'Alle Pakete bereinigt', NOW()),
('de', 'demurrage.detail.customer', 'Kunde', NOW()),
('de', 'demurrage.detail.content', 'Inhalt', NOW()),
('de', 'demurrage.detail.shelf', 'Regal', NOW()),
('de', 'demurrage.detail.arrivalDate', 'Ankunftsdatum', NOW()),
('de', 'demurrage.detail.inWarehouse', 'Im Lager', NOW()),
('de', 'demurrage.detail.freeDaysLeft', 'Verbleibende kostenlose Tage', NOW()),
('de', 'demurrage.detail.demurrageFee', 'Verzugsgebühr', NOW()),
('de', 'demurrage.detail.appliedFee', 'Angewandte Gebühr', NOW()),
('de', 'demurrage.detail.weight', 'Gewicht', NOW()),
('de', 'demurrage.detail.dimensions', 'Abmessungen', NOW()),
('de', 'demurrage.detail.notes', 'Notiz', NOW()),
('de', 'users.title', 'Benutzerverwaltung', NOW()),
('de', 'users.subtitle', 'Rollen- und Berechtigungszuweisungen', NOW()),
('de', 'users.searchPlaceholder', 'Nach Name, E-Mail oder ChiosBox ID suchen...', NOW()),
('de', 'users.error.updateFailed', 'Aktualisierung fehlgeschlagen', NOW()),
('de', 'users.editModal.title', 'Benutzer bearbeiten', NOW()),
('de', 'users.editModal.adminAccess', 'Admin-Berechtigung', NOW()),
('de', 'users.editModal.adminAccessDesc', 'Zugang zum Admin-Panel', NOW()),
('de', 'users.editModal.permissions', 'Berechtigungen', NOW()),
('de', 'users.editModal.superAdmin', 'Super-Admin — hat alle Berechtigungen, kann nicht bearbeitet werden.', NOW()),
('de', 'users.editModal.saving', 'Wird gespeichert...', NOW()),
('de', 'users.editModal.save', 'Speichern', NOW()),
('de', 'perm.intake', 'Annahme (Paketannahme)', NOW()),
('de', 'perm.pickup', 'Zustellung', NOW()),
('de', 'perm.demurrage', 'Verwaltungsverwaltung', NOW()),
('de', 'perm.packages', 'Paketliste', NOW()),
('de', 'perm.invoices', 'Rechnungsverwaltung', NOW()),
('de', 'perm.customers', 'Kundenverwaltung', NOW()),
('de', 'perm.settings', 'Systemeinstellungen', NOW()),
('de', 'error.root.title', 'Etwas ist schief gelaufen', NOW()),
('de', 'error.root.description', 'Ein unerwarteter Fehler ist aufgetreten. Bitte versuchen Sie es erneut.', NOW()),
('de', 'error.root.retry', 'Erneut versuchen', NOW()),
('de', 'notFound.title', 'Seite nicht gefunden', NOW()),
('de', 'notFound.description', 'Die gesuchte Seite existiert möglicherweise nicht oder wurde verschoben.', NOW()),
('de', 'notFound.homeLink', 'Zurück zur Startseite', NOW()),
('de', 'error.dashboard.title', 'Ein Fehler ist aufgetreten', NOW()),
('de', 'error.dashboard.description', 'Beim Laden der Seite ist ein Problem aufgetreten.', NOW()),
('de', 'error.dashboard.retry', 'Erneut versuchen', NOW()),
('de', 'error.admin.title', 'Admin-Dashboard-Fehler', NOW()),
('de', 'error.admin.description', 'Beim Laden der Seite ist ein Problem aufgetreten.', NOW()),
('de', 'error.admin.retry', 'Erneut versuchen', NOW()),
('de', 'loading.text', 'Wird geladen...', NOW()),
('de', 'loading.adminText', 'Wird geladen...', NOW()),
('de', 'login.email', 'E-Mail', NOW()),
('de', 'login.password', 'Passwort', NOW()),
('de', 'login.rememberMe', 'Angemeldet bleiben', NOW()),
('de', 'login.forgotPassword', 'Passwort vergessen', NOW()),
('de', 'login.submit', 'Anmelden', NOW()),
('de', 'login.submitting', 'Anmeldung läuft...', NOW()),
('de', 'login.noAccount', 'Noch kein Konto?', NOW()),
('de', 'login.registerLink', 'Registrieren', NOW()),
('de', 'register.steps.info', 'Angaben', NOW()),
('de', 'register.steps.emailVerify', 'E-Mail', NOW()),
('de', 'register.steps.phoneVerify', 'Telefon', NOW()),
('de', 'register.steps.payment', 'Zahlung', NOW()),
('de', 'register.nameLabel', 'Vollständiger Name', NOW()),
('de', 'register.namePlaceholder', 'Ihr vollständiger Name', NOW()),
('de', 'register.emailLabel', 'E-Mail', NOW()),
('de', 'register.emailPlaceholder', 'beispiel@email.com', NOW()),
('de', 'register.passwordLabel', 'Passwort', NOW()),
('de', 'register.passwordConfirmLabel', 'Passwort bestätigen', NOW()),
('de', 'register.passwordMismatch', 'Passwörter stimmen nicht überein', NOW()),
('de', 'register.planLabel', 'Plan wählen', NOW()),
('de', 'register.tosAgreement', 'Ich habe die Nutzungsbedingungen und die Datenschutzrichtlinie gelesen und akzeptiere sie.', NOW()),
('de', 'register.tosRequired', 'Sie müssen die Nutzungsbedingungen akzeptieren', NOW()),
('de', 'register.continue', 'Weiter', NOW()),
('de', 'register.loginLink', 'Anmelden', NOW()),
('de', 'register.emailVerifyTitle', 'E-Mail verifizieren', NOW()),
('de', 'register.emailVerifyDescription', 'Geben Sie den 6-stelligen Code ein, der an Ihre E-Mail gesendet wurde.', NOW()),
('de', 'register.verifying', 'Wird überprüft...', NOW()),
('de', 'register.resendCode', 'Code erneut senden', NOW()),
('de', 'register.smsNotReceived', 'SMS nicht erhalten? Erneut senden in {countdown}s', NOW()),
('de', 'register.backToInfo', 'Zurück zu Angaben', NOW()),
('de', 'register.phoneVerifyTitle', 'Telefon verifizieren', NOW()),
('de', 'register.phoneVerifyDescription', 'Geben Sie den 6-stelligen Code ein, der an Ihre Telefonnummer gesendet wurde.', NOW()),
('de', 'register.phoneTitle', 'Ihre Telefonnummer', NOW()),
('de', 'register.phoneDescription', 'Geben Sie Ihre Telefonnummer für Lieferbenachrichtigungen ein.', NOW()),
('de', 'register.phoneLabel', 'Telefonnummer', NOW()),
('de', 'register.sendSmsCode', 'SMS-Code senden', NOW()),
('de', 'register.freeTrialFirst', 'Erste 7 Tage kostenlos', NOW()),
('de', 'register.trialBadge', 'Testphase', NOW()),
('de', 'register.dueToday', 'Heute fällig', NOW()),
('de', 'register.cardNumberLabel', 'Kartennummer', NOW()),
('de', 'register.cardExpiryLabel', 'Ablaufdatum', NOW()),
('de', 'register.cardCvcLabel', 'CVC', NOW()),
('de', 'register.backBtn', 'Zurück', NOW()),
('de', 'register.processing', 'Wird verarbeitet...', NOW()),
('de', 'register.securePayment', 'Gesichert durch Stripe-Zahlung', NOW()),
('de', 'register.confirmPayment', 'Zahlung bestätigen — €0.00', NOW()),
('de', 'register.welcomeTitle', 'Willkommen!', NOW()),
('de', 'register.welcomeMessage', 'Ihr Konto und Abonnement wurden aktiviert.', NOW()),
('de', 'register.redirecting', 'Sie werden weitergeleitet...', NOW()),
('de', 'register.planTemel', 'Basis', NOW()),
('de', 'register.planPremium', 'Premium', NOW()),
('de', 'register.emailNotReceived', 'Code nicht erhalten? Erneut senden in {countdown}s', NOW()),
('de', 'register.backToEmail', '← Zurück zum E-Mail-Schritt', NOW()),
('de', 'register.monthSuffix', '/Mon.', NOW()),
('de', 'dashboard.greeting', 'Hallo {name}', NOW()),
('de', 'dashboard.defaultPlan', 'Basisplan', NOW()),
('de', 'dashboard.planActive', 'Aktiv', NOW()),
('de', 'dashboard.chiosBoxId', 'ChiosBox ID:', NOW()),
('de', 'dashboard.addressCopied', 'Kopiert!', NOW()),
('de', 'dashboard.copyAddress', 'Meine Adresse kopieren', NOW()),
('de', 'dashboard.payInvoice', 'Jetzt bezahlen', NOW()),
('de', 'dashboard.activePackages', 'Aktive Pakete', NOW()),
('de', 'dashboard.viewAll', 'Alle anzeigen →', NOW()),
('de', 'dashboard.noPackagesYet', 'Sie haben noch keine Pakete gemeldet', NOW()),
('de', 'dashboard.reportFirstPackage', 'Ihr erstes Paket melden →', NOW()),
('de', 'dashboard.storagePeriod', 'Lagerdauer', NOW()),
('de', 'dashboard.freeStorage', 'Kostenlose Lagerung', NOW()),
('de', 'dashboard.storageExpiring', 'Läuft bald ab!', NOW()),
('de', 'dashboard.inWarehouseDesc', 'Im Lager', NOW()),
('de', 'dashboard.inTransit', 'Unterwegs', NOW()),
('de', 'dashboard.reportPackage', 'Paket melden', NOW()),
('de', 'dashboard.consolidateAction', 'Zusammenführen', NOW()),
('de', 'dashboard.settings', 'Einstellungen', NOW()),
('de', 'dashboard.pendingInvoiceCount', '{count} ausstehende Rechnung(en)', NOW()),
('de', 'dashboard.pendingTotal', 'Gesamt: €{amount}', NOW()),
('de', 'dashboard.status.depoda', 'Im Lager', NOW()),
('de', 'dashboard.status.yolda', 'Unterwegs', NOW()),
('de', 'dashboard.status.bekleniyor', 'Zahlung ausstehend', NOW()),
('de', 'dashboard.status.teslim_edildi', 'Zugestellt', NOW()),
('de', 'packages.status.depoda', 'Im Lager', NOW()),
('de', 'packages.status.yolda', 'Unterwegs', NOW()),
('de', 'packages.status.bekleniyor', 'Zahlung ausstehend', NOW()),
('de', 'packages.status.birlestirildi', 'Zusammengefasst', NOW()),
('de', 'packages.status.teslim_edildi', 'Zugestellt', NOW()),
('de', 'packages.stepper.reported', 'Gemeldet', NOW()),
('de', 'packages.stepper.inWarehouse', 'Im Lager', NOW()),
('de', 'packages.stepper.consolidated', 'Zusammengefasst', NOW()),
('de', 'packages.stepper.delivered', 'Zugestellt', NOW()),
('de', 'packages.detail.warehouse', 'Lager', NOW()),
('de', 'packages.detail.masterBox', 'Masterkarton', NOW()),
('de', 'packages.detail.warehouseArrival', 'Lagerankunft', NOW()),
('de', 'packages.detail.freeDaysLeft', 'Verbleibende kostenlose Tage', NOW()),
('de', 'packages.detail.chat', 'Support', NOW()),
('de', 'packages.detail.messagePlaceholder', 'Nachricht eingeben...', NOW()),
('de', 'packages.searchPlaceholder2', 'Nach Sendungsnummer, Inhalt oder Spediteur suchen...', NOW()),
('de', 'packages.filter.all', 'Alle', NOW()),
('de', 'packages.filter.depoda', 'Im Lager', NOW()),
('de', 'packages.filter.yolda', 'Unterwegs', NOW()),
('de', 'packages.filter.bekleniyor', 'Zahlung ausstehend', NOW()),
('de', 'packages.filter.birlestirildi', 'Zusammengefasst', NOW()),
('de', 'packages.filter.teslim_edildi', 'Zugestellt', NOW()),
('de', 'packages.noSearchResults', 'Keine Pakete entsprechen Ihrer Suche', NOW()),
('de', 'packages.noCategoryPackages', 'Keine Pakete in dieser Kategorie', NOW()),
('de', 'checkout.error.loadFailed', 'Rechnung konnte nicht geladen werden', NOW()),
('de', 'checkout.error.generic', 'Ein Fehler ist aufgetreten', NOW()),
('de', 'checkout.error.tryLater', 'Bitte versuchen Sie es später erneut', NOW()),
('de', 'checkout.loading', 'Rechnungen werden geladen...', NOW()),
('de', 'checkout.empty.title', 'Keine ausstehenden Rechnungen', NOW()),
('de', 'checkout.empty.description', 'Sie haben derzeit keine Rechnungen zu bezahlen. Eine Rechnung wird erstellt, sobald Ihre Pakete im Lager eintreffen.', NOW()),
('de', 'checkout.summary.title', 'Zahlungsübersicht', NOW()),
('de', 'checkout.summary.pendingCount', '{count} ausstehende Rechnung(en)', NOW()),
('de', 'checkout.summary.selectedCount', '{count} Rechnung(en) ausgewählt', NOW()),
('de', 'checkout.payAll', 'Alle bezahlen — €{amount}', NOW()),
('de', 'checkout.paySelected', 'Ausgewählte bezahlen — €{amount}', NOW()),
('de', 'checkout.secureNote', 'Gesichert durch Stripe-Zahlungsinfrastruktur', NOW()),
('de', 'checkout.processing.title', 'Zahlung wird verarbeitet...', NOW()),
('de', 'checkout.processing.subtitle', 'Bitte warten', NOW()),
('de', 'checkout.success.title', 'Zahlung erfolgreich!', NOW()),
('de', 'checkout.success.subtitle', 'Ihr Liefer-QR-Code wird generiert', NOW()),
('de', 'checkout.success.ready', 'Bereit für Lieferung', NOW()),
('de', 'checkout.fee.accept', 'Annahmegebühr', NOW()),
('de', 'checkout.fee.consolidation', 'Konsolidierungsgebühr', NOW()),
('de', 'checkout.fee.consolidationShort', 'Zusammenfassung', NOW()),
('de', 'checkout.fee.demurrage', 'Lagergebühr', NOW()),
('de', 'consolidate.title', 'Konsolidierung', NOW()),
('de', 'consolidate.description', 'Sparen Sie Versandkosten durch Konsolidierung Ihrer Pakete', NOW()),
('de', 'consolidate.error.consolidationFailed', 'Konsolidierung fehlgeschlagen', NOW()),
('de', 'consolidate.error.generic', 'Ein Fehler ist aufgetreten', NOW()),
('de', 'consolidate.availablePackages', 'Für Konsolidierung verfügbare Pakete', NOW()),
('de', 'consolidate.packageCount', '{count} Paket(e)', NOW()),
('de', 'consolidate.add', 'Hinzufügen', NOW()),
('de', 'consolidate.noAvailable', 'Alle Pakete hinzugefügt oder keine Pakete im Lager', NOW()),
('de', 'consolidate.masterBox', 'Masterkarton', NOW()),
('de', 'consolidate.addFromLeft', 'Fügen Sie links Pakete hinzu', NOW()),
('de', 'consolidate.costSummary', 'Kostenübersicht', NOW()),
('de', 'consolidate.acceptFeeLine', 'Annahmegebühr ({count} × €{fee})', NOW()),
('de', 'consolidate.consolidationFee', 'Konsolidierungsgebühr', NOW()),
('de', 'consolidate.total', 'Gesamt', NOW()),
('de', 'consolidate.savings', 'Geschätzte Ersparnis: +€{amount}', NOW()),
('de', 'consolidate.submitting', 'Wird konsolidiert...', NOW()),
('de', 'consolidate.submit', 'Zusammenführen', NOW()),
('de', 'profile.title', 'Profil', NOW()),
('de', 'profile.description', 'Verwalten Sie Ihre Kontoinformationen und Lieferadresse', NOW()),
('de', 'profile.saved', 'Informationen aktualisiert', NOW()),
('de', 'profile.edit', 'Bearbeiten', NOW()),
('de', 'profile.nameLabel', 'Vollständiger Name', NOW()),
('de', 'profile.nameRequired', 'Vollständiger Name darf nicht leer sein', NOW()),
('de', 'profile.emailLabel', 'E-Mail', NOW()),
('de', 'profile.phoneLabel', 'Telefon', NOW()),
('de', 'profile.chiosBoxId', 'ChiosBox ID', NOW()),
('de', 'profile.cancel', 'Abbrechen', NOW()),
('de', 'profile.saving', 'Wird gespeichert...', NOW()),
('de', 'profile.save', 'Speichern', NOW()),
('de', 'profile.saveFailed', 'Aktualisierung fehlgeschlagen', NOW()),
('de', 'profile.genericError', 'Ein Fehler ist aufgetreten', NOW()),
('de', 'profile.addressTitle', 'Ihre Lieferadresse', NOW()),
('de', 'profile.addressCopied', 'Kopiert!', NOW()),
('de', 'profile.copyAddress', 'Adresse kopieren', NOW()),
('de', 'profile.subscriptionTitle', 'Abonnement-Informationen', NOW()),
('de', 'profile.defaultPlan', 'Basisplan', NOW()),
('de', 'profile.statusActive', 'Aktiv', NOW()),
('de', 'profile.statusInactive', 'Inaktiv', NOW()),
('de', 'profile.notificationsTitle', 'Benachrichtigungen', NOW()),
('de', 'profile.notificationsDescription', 'Erhalten Sie sofort Paket- und Rechnungsbenachrichtigungen', NOW()),
('de', 'profile.notificationsActive', 'Benachrichtigungen aktiv', NOW()),
('de', 'profile.notificationsDenied', 'Sie müssen die Benachrichtigungserlaubnis in den Browsereinstellungen aktivieren', NOW()),
('de', 'profile.notificationsEnabling', 'Wird eingerichtet...', NOW()),
('de', 'profile.notificationsEnable', 'Benachrichtigungen aktivieren', NOW()),
('de', 'profile.logout', 'Abmelden', NOW()),
('de', 'profile.changePassword', 'Passwort ändern', NOW()),
('de', 'profile.changePasswordDescription', 'Sie können Ihr Passwort hier aus Sicherheitsgründen ändern.', NOW()),
('de', 'profile.currentPassword', 'Aktuelles Passwort', NOW()),
('de', 'profile.newPassword', 'Neues Passwort', NOW()),
('de', 'profile.confirmPassword', 'Neues Passwort (bestätigen)', NOW()),
('de', 'profile.passwordChanged', 'Passwort erfolgreich geändert!', NOW()),
('de', 'profile.passwordRequired', 'Bitte füllen Sie alle Passwortfelder aus.', NOW()),
('de', 'profile.passwordMinLength', 'Das Passwort muss mindestens 6 Zeichen lang sein.', NOW()),
('de', 'profile.passwordMismatch', 'Passwörter stimmen nicht überein.', NOW()),
('de', 'profile.passwordChangeFailed', 'Passwortänderung fehlgeschlagen.', NOW()),
('de', 'actions.carrier.other', 'Andere', NOW()),
('de', 'actions.weight.light', 'Leicht', NOW()),
('de', 'actions.weight.medium', 'Mittel', NOW()),
('de', 'actions.weight.heavy', 'Schwer', NOW()),
('de', 'actions.weight.veryHeavy', 'Sehr schwer', NOW()),
('de', 'actions.dimension.small', 'Klein', NOW()),
('de', 'actions.dimension.smallBox', 'Kleine Karton', NOW()),
('de', 'actions.dimension.medium', 'Mittel', NOW()),
('de', 'actions.dimension.mediumBox', 'Standardkarton', NOW()),
('de', 'actions.dimension.large', 'Groß', NOW()),
('de', 'actions.dimension.largeBox', 'Große Karton', NOW()),
('de', 'actions.submitFailed', 'Meldung fehlgeschlagen', NOW()),
('de', 'actions.connectionError', 'Verbindungsfehler — bitte erneut versuchen', NOW()),
('de', 'actions.success.title', 'Paket gemeldet!', NOW()),
('de', 'actions.feeLabel', 'Annahmegebühr', NOW()),
('de', 'actions.feeDescription', 'Wird bezahlt, wenn das Paket im Lager ankommt', NOW()),
('de', 'actions.feeExplanation', 'Eine Rechnung wird erstellt, sobald Ihr Paket im ChiosBox-Lager ankommt, und Sie werden zur Zahlung aufgefordert.', NOW()),
('de', 'actions.goToPayment', 'Zur Zahlung', NOW()),
('de', 'actions.viewPackages', 'Meine Pakete anzeigen', NOW()),
('de', 'actions.newReport', 'Neues Paket melden', NOW()),
('de', 'actions.formDescription', 'Geben Sie die Daten Ihres Pakets ein', NOW()),
('de', 'actions.trackingLabel', 'Sendungsnummer', NOW()),
('de', 'actions.trackingPlaceholder', 'z.B.: 1Z999AA10123456784', NOW()),
('de', 'actions.carrierLabel', 'Spediteur', NOW()),
('de', 'actions.carrierPlaceholder', 'Spediteurnamen eingeben', NOW()),
('de', 'actions.contentLabel', 'Paketinhalt', NOW()),
('de', 'actions.contentPlaceholder', 'z.B.: Nike Air Max 90', NOW()),
('de', 'actions.weightLabel', 'Gewicht', NOW()),
('de', 'actions.optional', '(optional)', NOW()),
('de', 'actions.weightManualPlaceholder', 'oder manuell eingeben', NOW()),
('de', 'actions.weightUnit', 'kg', NOW()),
('de', 'actions.sizeLabel', 'Größe', NOW()),
('de', 'actions.sizeManualPlaceholder', 'oder manuell: 30x20x15 cm', NOW()),
('de', 'actions.noteLabel', 'Notiz', NOW()),
('de', 'actions.notePlaceholder', 'Zerbrechlich, Geschenkverpackung usw.', NOW()),
('de', 'actions.submitting', 'Wird gesendet...', NOW()),
('de', 'actions.submit', 'Melden', NOW()),
('de', 'sidebar.home', 'Startseite', NOW()),
('de', 'sidebar.packages', 'Meine Pakete', NOW()),
('de', 'sidebar.consolidate', 'Zusammenführen', NOW()),
('de', 'sidebar.actions', 'Aktionen', NOW()),
('de', 'sidebar.payment', 'Zahlung', NOW()),
('de', 'sidebar.profile', 'Profil', NOW()),