('tr', 'checkout.empty.description', 'Şu anda ödemeniz gereken fatura bulunmuyor. Paketleriniz depoya ulaştığında fatura oluşturulacaktır.', NOW()),
('tr', 'checkout.summary.title', 'Ödeme Özeti', NOW()),
('tr', 'checkout.summary.pendingCount', '{count} bekleyen fatura', NOW()),
('tr', 'checkout.summary.selectedCount', '{count} fatura seçildi', NOW()),
('tr', 'checkout.payAll', 'Tümünü öde — €{amount}', NOW()),
('tr', 'checkout.paySelected', 'Seçilenleri öde — €{amount}', NOW()),
('tr', 'checkout.secureNote', 'Stripe güvenli ödeme altyapısı ile korunmaktadır', NOW()),
('tr', 'checkout.processing.title', 'Ödeme İşleniyor...', NOW()),
('tr', 'checkout.processing.subtitle', 'Lütfen bekleyin', NOW()),
('tr', 'checkout.success.title', 'Ödeme Başarılı!', NOW()),
('tr', 'checkout.success.subtitle', 'Teslimat QR kodunuz oluşturuluyor', NOW()),
('tr', 'checkout.success.ready', 'Teslimata Hazır', NOW()),
('tr', 'checkout.fee.accept', 'Kabul ücreti', NOW()),
('tr', 'checkout.fee.consolidation', 'Konsolidasyon ücreti', NOW()),
('tr', 'checkout.fee.consolidationShort', 'Birleştirme', NOW()),
('tr', 'checkout.fee.demurrage', 'Gecikme ücreti', NOW()),
('tr', 'consolidate.title', 'Konsolidasyon', NOW()),
('tr', 'consolidate.description', 'Paketlerinizi birleştirerek kargo maliyetinden tasarruf edin', NOW()),
('tr', 'consolidate.error.consolidationFailed', 'Konsolidasyon başarısız', NOW()),
('tr', 'consolidate.error.generic', 'Bir hata oluştu', NOW()),
('tr', 'consolidate.availablePackages', 'Birleştirilebilir Paketler', NOW()),
('tr', 'consolidate.packageCount', '{count} paket', NOW()),
('tr', 'consolidate.add', 'Ekle', NOW()),
('tr', 'consolidate.noAvailable', 'Tüm paketler eklendi veya depoda paket yok', NOW()),
('tr', 'consolidate.masterBox', 'Master Box', NOW()),
('tr', 'consolidate.addFromLeft', 'Soldan paket ekleyin', NOW()),
('tr', 'consolidate.costSummary', 'Maliyet Özeti', NOW()),
('tr', 'consolidate.acceptFeeLine', 'Kabul ücreti ({count} × €{fee})', NOW()),
('tr', 'consolidate.consolidationFee', 'Konsolidasyon ücreti', NOW()),
('tr', 'consolidate.total', 'Toplam', NOW()),
('tr', 'consolidate.savings', 'Tahmini Tasarruf: +€{amount}', NOW()),
('tr', 'consolidate.submitting', 'Birleştiriliyor...', NOW()),
('tr', 'consolidate.submit', 'Birleştir', NOW()),
('tr', 'profile.title', 'Profil', NOW()),
('tr', 'profile.description', 'Hesap bilgilerinizi ve teslimat adresinizi yönetin', NOW()),
('tr', 'profile.saved', 'Bilgiler güncellendi', NOW()),
('tr', 'profile.edit', 'Düzenle', NOW()),
('tr', 'profile.nameLabel', 'Ad Soyad', NOW()),
('tr', 'profile.nameRequired', 'Ad Soyad boş olamaz', NOW()),
('tr', 'profile.emailLabel', 'E-posta', NOW()),
('tr', 'profile.phoneLabel', 'Telefon', NOW()),
('tr', 'profile.chiosBoxId', 'ChiosBox ID', NOW()),
('tr', 'profile.cancel', 'İptal', NOW()),
('tr', 'profile.saving', 'Kaydediliyor...', NOW()),
('tr', 'profile.save', 'Kaydet', NOW()),
('tr', 'profile.saveFailed', 'Güncelleme başarısız', NOW()),
('tr', 'profile.genericError', 'Bir hata oluştu', NOW()),
('tr', 'profile.addressTitle', 'Teslimat Adresiniz', NOW()),
('tr', 'profile.addressCopied', 'Kopyalandı!', NOW()),
('tr', 'profile.copyAddress', 'Adresi Kopyala', NOW()),
('tr', 'profile.subscriptionTitle', 'Abonelik Bilgileri', NOW()),
('tr', 'profile.defaultPlan', 'Temel Plan', NOW()),
('tr', 'profile.statusActive', 'Aktif', NOW()),
('tr', 'profile.statusInactive', 'Pasif', NOW()),
('tr', 'profile.notificationsTitle', 'Bildirimler', NOW()),
('tr', 'profile.notificationsDescription', 'Paket ve fatura bildirimlerini anında alın', NOW()),
('tr', 'profile.notificationsActive', 'Bildirimler aktif', NOW()),
('tr', 'profile.notificationsDenied', 'Tarayıcı ayarlarından bildirim iznini açmanız gerekiyor', NOW()),
('tr', 'profile.notificationsEnabling', 'Ayarlanıyor...', NOW()),
('tr', 'profile.notificationsEnable', 'Bildirimleri Aç', NOW()),
('tr', 'profile.logout', 'Çıkış Yap', NOW()),
('tr', 'profile.changePassword', 'Şifre Değiştir', NOW()),
('tr', 'profile.changePasswordDescription', 'Güvenliğiniz için şifrenizi buradan değiştirebilirsiniz.', NOW()),
('tr', 'profile.currentPassword', 'Mevcut şifre', NOW()),
('tr', 'profile.newPassword', 'Yeni şifre', NOW()),
('tr', 'profile.confirmPassword', 'Yeni şifre (tekrar)', NOW()),
('tr', 'profile.passwordChanged', 'Şifreniz başarıyla değiştirildi!', NOW()),
('tr', 'profile.passwordRequired', 'Tüm şifre alanlarını doldurun.', NOW()),
('tr', 'profile.passwordMinLength', 'Şifre en az 6 karakter olmalıdır.', NOW()),
('tr', 'profile.passwordMismatch', 'Şifreler eşleşmiyor.', NOW()),
('tr', 'profile.passwordChangeFailed', 'Şifre değiştirme başarısız oldu.', NOW()),
('tr', 'profile.addressLabel', 'Adres', NOW()),
('tr', 'profile.addressPlaceholder', 'Adresinizi girin', NOW()),
('tr', 'tour.start', 'Tur Rehberini Başlat', NOW()),
('tr', 'tour.next', 'İleri', NOW()),
('tr', 'tour.back', 'Geri', NOW()),
('tr', 'tour.finish', 'Bitir', NOW()),
('tr', 'tour.skip', 'Atla', NOW()),
('tr', 'tour.close', 'Kapat', NOW()),
('tr', 'tour.helpTooltip', 'Tur Rehberi', NOW()),
('tr', 'tour.step.dashboardWelcome.title', 'Hoşgeldiniz', NOW()),
('tr', 'tour.step.dashboardWelcome.content', 'ChiosBox''a hoş geldiniz! Bu sizin kontrol paneliniz. Üstte ChiosBox ID''niz ve teslimat adresiniz görünür. ''Adresimi Kopyala'' butonu ile adresinizi kopyalayın ve Türk online mağazalarında alışveriş yaparken teslimat adresi olarak kullanın.', NOW()),
('tr', 'tour.step.dashboardStats.title', 'İstatistik Kartları', NOW()),
('tr', 'tour.step.dashboardStats.content', 'Aktif paket sayınızı, depodaki ve yoldaki paketlerinizi, kalan ücretsiz saklama sürenizi ve bekleyen fatura sayınızı burada görebilirsiniz. Her kart sizi bilgilendirir.', NOW()),
('tr', 'tour.step.dashboardPackages.title', 'Aktif Paketler', NOW()),
('tr', 'tour.step.dashboardPackages.content', 'Son eklenen paketleriniz durum etiketleriyle burada listelenir. Henüz paket bildirmediyseniz boş durum mesajı görünür. Tüm paketlerinizi görmek için ''Tümünü Gör'' bağlantısına tıklayın.', NOW()),
('tr', 'tour.step.dashboardActions.title', 'Hızlı İşlemler', NOW()),
('tr', 'tour.step.dashboardActions.content', 'Sık kullanılan işlemlere hızlı erişim. ''Adresimi Kopyala'' ile ChiosBox adresinizi kopyalayın — bunu online alışverişlerde teslimat adresi olarak kullanacaksınız. ''Şimdi Öde'' ile bekleyen faturalarınızı ödeyebilirsiniz.', NOW()),
('tr', 'tour.step.actions.title', 'Paket Bildirme — Sipariş Süreci', NOW()),
('tr', 'tour.step.actions.content', 'Online alışverişinizden sonra satıcı kargoya verdiğinde bir takip numarası oluşur. O numarayı buraya girerek paketinizi ChiosBox sistemine eklersiniz. Böylece paketiniz depoya ulaştığında sizi bilgilendirebiliriz. Hadi formu adım adım dolduralım!', NOW()),
('tr', 'tour.step.tracking.title', 'Takip Numarası', NOW()),
('tr', 'tour.step.tracking.content', 'Satıcınızdan aldığınız kargo takip numarasını buraya girin. Numarayı girdiğinizde kargo firması otomatik algılanır. Örneğin: TR-2026-0044 gibi bir numara kullanabilirsiniz.', NOW()),
('tr', 'tour.step.carrier.title', 'Kargo Firması', NOW()),
('tr', 'tour.step.carrier.content', 'Paketinizi hangi kargo firmasının getirdiğini seçin. Takip numarasından otomatik algılanmadıysa listeden seçebilir veya ''Diğer'' ile manuel girebilirsiniz.', NOW()),
('tr', 'tour.step.packageForm.title', 'Paket Bilgileri', NOW()),
('tr', 'tour.step.packageForm.content', 'Paketinizin detaylarını girin: İçerik açıklaması (ne olduğunu tanımlar), ağırlık (ücretlendirmeyi etkiler), boyutlar (kutu seçimi için önemli) ve özel notlar. Bu bilgiler paketinizin işlenmesini hızlandırır.', NOW()),
('tr', 'tour.step.submit.title', 'Paket Bildir', NOW()),
('tr', 'tour.step.submit.content', 'Tüm bilgileri girdikten sonra bu butona tıklayarak paketinizi ChiosBox''a bildirin. Demo modunda form doldurulacak ve 3. paket listenize eklenecek.', NOW()),
('tr', 'tour.step.packages.title', 'Paketlerim — Liste', NOW()),
('tr', 'tour.step.packages.content', 'Tüm bildirdiğiniz paketler burada listelenir. Arama ve filtreleme ile paketlerinizi hızlıca bulun. Her paket kartında durum etiketi, kargo firması, takip numarası ve içerik bilgisi görünür. Artık 3 demo paketiniz var!', NOW()),
('tr', 'tour.step.packageCard.title', 'Paket Kartı', NOW()),
('tr', 'tour.step.packageCard.content', 'Her paket kartında durum etiketi (bekleniyor, yolda, depoda, teslim edildi), kargo firması, takip numarası ve içerik özeti görünür. Detayları görmek için karta tıklayın.', NOW()),
('tr', 'tour.step.packageDetail.title', 'Paket Detayları', NOW()),
('tr', 'tour.step.packageDetail.content', 'Pakete tıkladığınızda detay modalı açılır. Burada depo varış tarihi, kalan ücretsiz saklama süresi, raf konumu ve depo fotoğrafını görebilirsiniz. Destek chat bölümünden paketinizle ilgili soru sorabilirsiniz. Ödeme yapmadan önce bilgilerinizi buradan kontrol edebilirsiniz.', NOW()),
('tr', 'tour.step.consolidateLeft.title', 'Depo Paketleri', NOW()),
('tr', 'tour.step.consolidateLeft.content', 'Sol panelde depoda bekleyen paketleriniz listelenir. Konsolidasyon kutusuna eklemek istediğiniz paketleri seçin. Birden fazla paketi tek kutuda birleştirerek uluslararası kargo maliyetlerinden tasarruf edin.', NOW()),
('tr', 'tour.step.consolidateRight.title', 'Konsolidasyon Kutusu', NOW()),
('tr', 'tour.step.consolidateRight.content', 'Seçtiğiniz paketler master box''a transfer olur. Paket birleştirildiğinde konsolidasyon ücreti eklenir ama ayrı ayrı göndermekten çok daha ucuzdur. Farkı fiyat karşılaştırmasında görebilirsiniz.', NOW()),
('tr', 'tour.step.consolidateConfirm.title', 'Konsolidasyon Onayı', NOW()),
('tr', 'tour.step.consolidateConfirm.content', 'Paketlerinizi seçtikten sonra bu butona tıklayarak konsolidasyon talebinizi gönderin. Bu adım opsiyoneldir — paketleri tek tek de gönderebilirsiniz.', NOW()),
('tr', 'tour.step.checkout.title', 'Fatura İnceleme', NOW()),
('tr', 'tour.step.checkout.content', 'Ödeme yapmadan önce faturalarınızı inceleyin. Kabul ücreti, konsolidasyon ücreti, depo fazlası ücreti gibi kalemleri ve paket bazlı dökümü görebilirsiniz. Toplam tutarı kontrol edin. İsterseniz paketlerinize geri dönüp düzenlemeler yapabilirsiniz.', NOW()),
('tr', 'tour.step.checkoutPay.title', 'Ödeme ve QR Kod', NOW()),
('tr', 'tour.step.checkoutPay.content', 'Ödeme onayladıktan sonra teslim QR kodunuz oluşturulur. Bu QR kodu ChiosBox teslimat noktasında göstererek paketlerinizi alabilirsiniz.', NOW()),
('tr', 'tour.step.profileInfo.title', 'Kişisel Bilgiler', NOW()),
('tr', 'tour.step.profileInfo.content', 'Adınız, e-posta adresiniz, telefon numaranız ve ChiosBox ID''niz burada görünür. Düzenle butonu ile bilgilerinizi güncelleyebilir, kaydet butonu ile değişiklikleri kaydedebilirsiniz.', NOW()),
('tr', 'tour.step.profilePassword.title', 'Şifre Değiştirme', NOW()),
('tr', 'tour.step.profilePassword.content', 'Güvenliğiniz için şifrenizi buradan değiştirebilirsiniz. Mevcut şifrenizi girin, yeni şifrenizi belirleyin ve onaylayın.', NOW()),
('tr', 'tour.step.profileAddress.title', 'ChiosBox Teslimat Adresi', NOW()),
('tr', 'tour.step.profileAddress.content', 'Bu adres Sakız Adası''ndaki depomuzun adresidir. Türk online mağazalarından alışveriş yaparken teslimat adresi olarak bu adresi kullanın. ''Adresi Kopyala'' butonu ile hızlıca kopyalayabilirsiniz.', NOW()),
('tr', 'tour.step.profileSubscription.title', 'Üyelik Bilgisi', NOW()),
('tr', 'tour.step.profileSubscription.content', 'Mevcut planınız ve abonelik durumunuz burada görünür. Plan adı (Basic Plan) ve durum (Aktif/Pasif) bilgilerini kontrol edebilirsiniz.', NOW()),
('tr', 'tour.step.profileExtras.title', 'Ayarlar ve Bildirimler', NOW()),
('tr', 'tour.step.profileExtras.content', 'Bildirimleri açarak paket güncellemelerini anında alın. Turu yeniden başlatmak için ''?'' butonunu kullanabilirsiniz. Çıkış yapmak için alttaki butona tıklayın.', NOW()),
('tr', 'tour.orderFlow.title', 'Sipariş & Kargo Süreci', NOW()),
('tr', 'tour.orderFlow.step1.title', 'Web Sitesine Gir', NOW()),
('tr', 'tour.orderFlow.step1.content', 'Türkiye''deki herhangi bir online mağazadan (Trendyol, Hepsiburada, Amazon vb.) alışveriş yapın.', NOW()),
('tr', 'tour.orderFlow.step2.title', 'Ürünü Seç ve Satın Al', NOW()),
('tr', 'tour.orderFlow.step2.content', 'İstediğiniz ürünü seçin, sepete ekleyin ve siparişi tamamlayın. Ödeme adımında ChiosBox adresinizi kullanın.', NOW()),
('tr', 'tour.orderFlow.step3.title', 'Satıcı Kargoya Verdi', NOW()),
('tr', 'tour.orderFlow.step3.content', 'Satıcı siparişinizi kargoya verdiğinde, bir takip numarası oluşur. Bu numarayı kargo firmasıyla birlikte not edin.', NOW()),
('tr', 'tour.orderFlow.step4.title', 'Takip Numarası Belli Oldu', NOW()),
('tr', 'tour.orderFlow.step4.content', 'Kargo firması ve takip numaranız belli oldu! Artık ChiosBox''a paket bildirimi yapabilirsiniz.', NOW()),
('tr', 'tour.orderFlow.step5.title', 'Paket Bildirebilirsiniz!', NOW()),
('tr', 'tour.orderFlow.step5.content', 'Şimdi bir sonraki adımda takip numaranızı ve kargo firmasını girerek paketinizi ChiosBox sistemine ekleyebilirsiniz.', NOW()),
('tr', 'tour.orderFlow.next', 'Sonraki', NOW()),
('tr', 'tour.orderFlow.finish', 'Tamam, Anladım!', NOW()),
('tr', 'actions.carrier.other', 'Diğer', NOW()),
('tr', 'actions.weight.light', 'Hafif', NOW()),
('tr', 'actions.weight.medium', 'Orta', NOW()),
('tr', 'actions.weight.heavy', 'Ağır', NOW()),
('tr', 'actions.weight.veryHeavy', 'Çok Ağır', NOW()),
('tr', 'actions.dimension.small', 'Küçük', NOW()),
('tr', 'actions.dimension.smallBox', 'Küçük kutu', NOW()),
('tr', 'actions.dimension.medium', 'Orta', NOW()),
('tr', 'actions.dimension.mediumBox', 'Standart kutu', NOW()),
('tr', 'actions.dimension.large', 'Büyük', NOW()),
('tr', 'actions.dimension.largeBox', 'Büyük kutu', NOW()),
('tr', 'actions.submitFailed', 'Bildirim başarısız', NOW()),
('tr', 'actions.connectionError', 'Bağlantı hatası — lütfen tekrar deneyin', NOW()),
('tr', 'actions.success.title', 'Paket Bildirildi!', NOW()),
('tr', 'actions.feeLabel', 'Kabul ücreti', NOW()),
('tr', 'actions.feeDescription', 'Paket depoya ulaştığında ödenecek', NOW()),
('tr', 'actions.feeExplanation', 'Paketiniz ChiosBox deposuna ulaştığında fatura oluşturulacak ve ödeme yapmanız istenecektir.', NOW()),
('tr', 'actions.goToPayment', 'Ödemeye Git', NOW()),
('tr', 'actions.viewPackages', 'Paketlerimi Gör', NOW()),
('tr', 'actions.newReport', 'Yeni Paket Bildir', NOW()),
('tr', 'actions.formDescription', 'Alışveriş yaptığınız paketin bilgilerini girin', NOW()),
('tr', 'actions.trackingLabel', 'Takip Numarası', NOW()),
('tr', 'actions.trackingPlaceholder', 'örn: 1Z999AA10123456784', NOW()),
('tr', 'actions.carrierLabel', 'Kargo Firması', NOW()),
('tr', 'actions.carrierPlaceholder', 'Kargo firması adı yazın', NOW()),
('tr', 'actions.contentLabel', 'Paket İçeriği', NOW()),
('tr', 'actions.contentPlaceholder', 'örn: Nike Air Max 90', NOW()),
('tr', 'actions.weightLabel', 'Ağırlık', NOW()),
('tr', 'actions.optional', '(opsiyonel)', NOW()),
('tr', 'actions.weightManualPlaceholder', 'veya manuel girin', NOW()),
('tr', 'actions.weightUnit', 'kg', NOW()),
('tr', 'actions.sizeLabel', 'Boyut', NOW()),
('tr', 'actions.sizeManualPlaceholder', 'veya manuel: 30x20x15 cm', NOW()),
('tr', 'actions.noteLabel', 'Not', NOW()),
('tr', 'actions.notePlaceholder', 'Kırılabilir, hediye paketi vb.', NOW()),
('tr', 'actions.submitting', 'Gönderiliyor...', NOW()),
('tr', 'actions.submit', 'Bildir', NOW()),
('tr', 'sidebar.home', 'Ana Sayfa', NOW()),
('tr', 'sidebar.packages', 'Paketlerim', NOW()),
('tr', 'sidebar.consolidate', 'Birleştir', NOW()),
('tr', 'sidebar.actions', 'İşlemler', NOW()),
('tr', 'sidebar.payment', 'Ödeme', NOW()),
('tr', 'sidebar.profile', 'Profil', NOW()),
('tr', 'sidebar.logout', 'Çıkış Yap', NOW()),
('tr', 'admin.panel', 'Panel', NOW()),
('tr', 'admin.users', 'Kullanıcılar', NOW()),
('tr', 'admin.languages', 'Diller', NOW()),
('tr', 'admin.translations', 'Çeviriler', NOW()),
('tr', 'admin.logout', 'Çıkış', NOW()),
('tr', 'adminLogin.title', 'Admin Girişi', NOW()),
('tr', 'adminLogin.email', 'E-posta', NOW()),
('tr', 'adminLogin.password', 'Şifre', NOW()),
('tr', 'adminLogin.submitting', 'Giriş Yapılıyor...', NOW()),
('tr', 'adminLogin.error.loginFailed', 'Giriş başarısız', NOW()),
('tr', 'adminLogin.error.noAdminAccess', 'Bu hesap admin erişimine sahip değil', NOW()),
('tr', 'adminLogin.error.generic', 'Bir hata oluştu', NOW()),
('tr', 'planSelector.period', '/ay', NOW()),
('tr', 'planSelector.temel.name', 'Temel', NOW()),
('tr', 'planSelector.temel.f1', 'ChiosBox EU adresi', NOW()),
('tr', 'planSelector.temel.f2', '14 gün ücretsiz depolama', NOW()),
('tr', 'planSelector.temel.f3', 'Panel erişimi', NOW()),
('tr', 'planSelector.temel.f4', 'E-posta bildirimleri', NOW()),
('tr', 'planSelector.premium.name', 'Premium', NOW()),
('tr', 'planSelector.premium.badge', 'En Popüler', NOW()),
('tr', 'planSelector.premium.f1', 'Her şey Temel pakette', NOW()),
('tr', 'planSelector.premium.f2', '21 gün ücretsiz depolama', NOW()),
('tr', 'planSelector.premium.f3', 'Ücretsiz konsolidasyon', NOW()),
('tr', 'planSelector.premium.f4', 'Türkiye teslimat takibi', NOW()),
('tr', 'planSelector.premium.f5', 'Özel destek hattı', NOW()),
('tr', 'register.pageTitle', 'ChiosBox''a Katılın', NOW()),
('tr', 'register.pageSubtitle', 'Avrupa teslimat adresinizi hemen alın, kapıdan kapıya kargo ayrıcalığını yaşayın', NOW()),
('tr', 'store.error.packagesLoadFailed', 'Paketler yüklenemedi', NOW()),
('tr', 'store.error.generic', 'Bir hata oluştu', NOW()),
('tr', 'store.error.deleteFailed', 'Silme başarısız', NOW()),
('tr', 'store.error.intakeFailed', 'Kabul başarısız', NOW()),
('tr', 'store.error.deliveryFailed', 'Teslimat başarısız', NOW()),
('tr', 'store.error.discardFailed', 'Tasfiye başarısız', NOW()),
('tr', 'store.error.registerFailed', 'Kayıt başarısız', NOW()),
('tr', 'api.error.loginRequired', 'Oturum açmanız gerekiyor', NOW()),
('tr', 'api.error.unauthorized', 'Yetkisiz erişim', NOW()),
('tr', 'api.error.authCheckFailed', 'Yetki doğrulama hatası', NOW()),
('tr', 'api.error.rateLimited', 'Çok fazla istek. Lütfen daha sonra tekrar deneyin.', NOW()),
('tr', 'authLayout.heading', 'ChiosBox ile Avrupa Kapınızda', NOW()),
('tr', 'authLayout.description', 'Türkiye&apos;den Avrupa&apos;ya, Avrupa&apos;dan Türkiye&apos;ye kapıdan kapıya kargo hizmeti', NOW()),
('tr', 'login.pageTitle', 'Tekrar Hoş Geldiniz', NOW()),
('tr', 'login.pageSubtitle', 'ChiosBox hesabınıza giriş yapın', NOW()),
('tr', 'packages.demurrageFee', 'Gecikme Ücreti', NOW()),
('tr', 'packages.weight', 'Ağırlık', NOW()),
('tr', 'packages.noMessagesYet', 'Henüz mesaj yok', NOW()),
('tr', 'packages.chatHint', 'Paketinizle ilgili sorularınızı buradan sorabilirsiniz', NOW()),
('tr', 'packages.giveUp', 'Vazgeç', NOW()),
('tr', 'packages.daysFree', '{days} ücretsiz', NOW()),
('tr', 'packages.carrier', 'Kargo', NOW()),
('tr', 'packages.trackingNo', 'Takip No', NOW()),
('tr', 'packages.notification', 'Bildirim', NOW()),
('tr', 'packages.dimensions', 'Boyut', NOW()),
('tr', 'packages.note', 'Not', NOW()),
('tr', 'packages.deletePackage', 'Paketi Sil', NOW()),
('tr', 'packages.deleting', 'Siliniyor...', NOW()),
('tr', 'packages.confirmDelete', 'Evet, Sil', NOW()),
('tr', 'packages.close', 'Kapat', NOW()),
('tr', 'packages.notifyNew', 'Yeni Bildir', NOW()),
('tr', 'packages.demurrageShort', 'gecikme', NOW()),
('tr', 'common.days', 'gün', NOW()),
('tr', 'islandScene.departed.badge', 'Türkiye''den Yola Çıktı', NOW()),
('tr', 'islandScene.departed.title', 'Paketleriniz Yolda', NOW()),
('tr', 'islandScene.departed.description', 'Türkiye''deki satıcılardan alınan paketler, Sakız Adası''na doğru yola çıkıyor.', NOW()),
('tr', 'islandScene.crossing.badge', 'Ege''yi Aşıyor', NOW()),
('tr', 'islandScene.crossing.title', 'Güvenle Taşınıyor', NOW()),
('tr', 'islandScene.crossing.description', 'Tekneler ve kargo yollarıyla, her paket sigortalı ve takip edilebilir.', NOW()),
('tr', 'islandScene.arrived.badge', 'Hedefe Ulaştı', NOW()),
('tr', 'islandScene.arrived.title', 'Sakız Adası Depomuzda', NOW()),
('tr', 'islandScene.arrived.description', 'Konsolide edin, tasarruf edin, kapınıza teslim edelim.', NOW()),
('tr', 'bento.route.title', 'Kesintisiz Lojistik', NOW()),
('tr', 'bento.route.euStore', 'AB Mağazası', NOW()),
('tr', 'bento.route.warehouse', 'Sakız Deposu', NOW()),
('tr', 'bento.storage.title', 'Bekleme Süresi', NOW()),
('tr', 'bento.storage.days', 'Gün Ücretsiz', NOW()),
('tr', 'bento.storage.subtitle', 'Depolama Hakkı', NOW()),
('tr', 'bento.delivery.title', 'Kolay Teslimat', NOW()),
('tr', 'bento.delivery.headline', 'Adaya Geçin', NOW()),
('tr', 'bento.delivery.subtitle', 'Hafta sonu feribotla al.', NOW()),
('tr', 'adminCustomers.backToList', 'Müşterilere Dön', NOW()),
('tr', 'adminCustomers.package', 'Paket', NOW()),
('tr', 'adminCustomers.totalSpent', 'Toplam Harcama', NOW()),
('tr', 'adminCustomers.pending', 'Bekleyen', NOW()),
('tr', 'adminCustomers.packages', 'Paketler', NOW()),
('tr', 'adminCustomers.invoices', 'Faturalar', NOW()),
('tr', 'adminCustomers.noPackagesYet', 'Henüz paket yok', NOW()),
('tr', 'adminCustomers.noInvoicesYet', 'Henüz fatura yok', NOW()),
('tr', 'adminCustomers.paid', 'Ödendi', NOW()),
('tr', 'adminCustomers.cancelled', 'İptal', NOW()),
('tr', 'adminCustomers.waiting', 'Beklemede', NOW()),
('tr', 'adminCustomers.status.bekleniyor', 'Beklemede', NOW()),
('tr', 'adminCustomers.status.yolda', 'Yolda', NOW()),
('tr', 'adminCustomers.status.depoda', 'Depoda', NOW()),
('tr', 'adminCustomers.status.birlestirildi', 'Birleştirildi', NOW()),
('tr', 'adminCustomers.status.teslim_edildi', 'Teslim Edildi', NOW()),
('tr', 'adminLogin.brandingTitle', 'ChiosBox Yönetim Paneli', NOW()),
('tr', 'adminLogin.brandingDesc', 'Paket yönetimi, faturalama ve müşteri işlemleri için admin girişi', NOW()),
('tr', 'adminLogin.heading', 'Yönetim Paneli', NOW()),
('tr', 'adminLogin.subheading', 'Admin hesabınızla giriş yapın', NOW()),
('tr', 'adminLogin.customerQuestion', 'Müşteri misiniz?', NOW()),
('tr', 'adminLogin.customerLogin', 'Müşteri Girişi', NOW()),
('tr', 'adminTranslations.title', 'Çeviriler', NOW()),
('tr', 'adminTranslations.description', 'Tüm metinleri düzenleyin', NOW()),
('tr', 'adminTranslations.saveChanges', '{count} Değişikliği Kaydet', NOW()),
('tr', 'adminTranslations.saving', 'Kaydediliyor...', NOW()),
('tr', 'adminTranslations.saved', '{count} çeviri kaydedildi', NOW()),
('tr', 'adminTranslations.saveFailed', 'Kaydetme başarısız', NOW()),
('tr', 'adminTranslations.searchPlaceholder', 'Çeviri anahtarında ara...', NOW()),
('tr', 'adminTranslations.noResults', 'Aramaya uygun çeviri bulunamadı', NOW()),
('tr', 'adminTranslations.empty', 'Bu dil için henüz çeviri eklenmemiş', NOW()),
('tr', 'adminTranslations.delete', 'Sil', NOW()),
('tr', 'adminLanguages.title', 'Diller', NOW()),
('tr', 'adminLanguages.description', 'Uygulama dillerini yönetin', NOW()),
('tr', 'adminLanguages.addLanguage', 'Dil Ekle', NOW()),
('tr', 'adminLanguages.addNewLanguage', 'Yeni Dil Ekle', NOW()),
('tr', 'adminLanguages.code', 'Kod', NOW()),
('tr', 'adminLanguages.name', 'İsim', NOW()),
('tr', 'adminLanguages.flag', 'Bayrak Emoji', NOW()),
('tr', 'adminLanguages.add', 'Ekle', NOW()),
('tr', 'adminLanguages.adding', 'Ekleniyor...', NOW()),
('tr', 'adminLanguages.cancel', 'İptal', NOW()),
('tr', 'adminLanguages.default', 'Varsayılan', NOW()),
('tr', 'adminLanguages.active', 'Aktif', NOW()),
('tr', 'adminLanguages.inactive', 'Devre dışı', NOW()),
('tr', 'adminLanguages.setDefault', 'Varsayılan Yap', NOW()),
('tr', 'adminLanguages.delete', 'Sil', NOW()),
('tr', 'adminLanguages.remove', 'Kaldır', NOW()),
('tr', 'adminLanguages.noLanguagesYet', 'Henüz dil eklenmemiş', NOW()),
('tr', 'admin.policies', 'Politikalar', NOW()),
('tr', 'adminPolicies.title', 'Yasal Politikalar', NOW()),
('tr', 'adminPolicies.description', 'Kullanıcı sözleşmesi, gizlilik politikası ve KVKK metinlerini yönetin.', NOW()),
('tr', 'admin.settings', 'Ayarlar', NOW()),
('tr', 'adminSettings.title', 'Sistem Ayarları', NOW()),
('tr', 'adminSettings.description', 'Ücretler, plan fiyatları, limitler ve iş kurallarını yönetin. Değişiklikler anında geçerli olur.', NOW()),
('tr', 'adminSettings.saving', 'Kaydediliyor...', NOW()),
('tr', 'adminSettings.saveChanges', '{count} Değişikliği Kaydet', NOW()),
('tr', 'adminSettings.saved', '{count} ayar kaydedildi.', NOW()),
('tr', 'adminSettings.saveFailed', 'Kaydetme başarısız.', NOW()),
('tr', 'adminSettings.empty', 'Bu kategoride ayar bulunamadı.', NOW()),
('tr', 'adminSettings.catFees', 'Ücretler', NOW()),
('tr', 'adminSettings.catPlans', 'Planlar', NOW()),
('tr', 'adminSettings.catLimits', 'Limitler', NOW()),
('tr', 'adminSettings.catBusiness', 'İş Kuralları', NOW()),
('tr', 'adminSettings.catRateLimits', 'Rate Limitler', NOW()),
('tr', 'adminSettings.warningTitle', 'Dikkat', NOW()),
('tr', 'adminSettings.warningText', 'Ücret ve plan değişiklikleri yeni işlemleri etkiler. Mevcut faturalar kendi tutarlarıyla korunur. Değişiklik yapmadan önce emin olun.', NOW()),
('tr', 'adminPolicies.titleLabel', 'Başlık', NOW()),
('tr', 'adminPolicies.titlePlaceholder', 'Politika başlığı', NOW()),
('tr', 'adminPolicies.contentLabel', 'İçerik', NOW()),
('tr', 'adminPolicies.contentPlaceholder', 'HTML içeriğini buraya yazın...', NOW()),
('tr', 'adminPolicies.contentHint', 'HTML formatında içerik girebilirsiniz. Etiketler desteklenir.', NOW()),
('tr', 'adminPolicies.save', 'Kaydet', NOW()),
('tr', 'adminPolicies.saving', 'Kaydediliyor...', NOW()),
('tr', 'adminPolicies.saved', 'Başarıyla kaydedildi', NOW()),
('tr', 'adminPolicies.saveFailed', 'Kaydetme başarısız', NOW()),
('tr', 'adminPolicies.published', 'Yayında', NOW()),
('tr', 'adminPolicies.draft', 'Taslak', NOW()),
('tr', 'footer.kvkk', 'KVKK Aydınlatma Metni', NOW()),
('en', 'nav.howItWorks', 'How It Works?', NOW()),
('en', 'nav.pricing', 'Prices', NOW()),
('en', 'nav.trust', 'Trust', NOW()),
('en', 'nav.logout', 'Logout', NOW()),
('en', 'nav.login', 'Log In', NOW()),
('en', 'nav.getAddress', 'Get Your Address Now', NOW()),
('en', 'footer.description', 'Package consolidation management based on Chios for those shopping e-commerce from Turkey to the EU.', NOW()),
('en', 'footer.service', 'Service', NOW()),
('en', 'footer.howItWorks', 'How It Works?', NOW()),
('en', 'footer.pricing', 'Pricing', NOW()),
('en', 'footer.consolidation', 'Consolidation', NOW()),
('en', 'footer.support', 'Support', NOW()),
('en', 'footer.faq', 'Frequently Asked Questions', NOW()),
('en', 'footer.contact', 'Contact', NOW()),
('en', 'footer.tracking', 'Shipment Tracking', NOW()),
('en', 'footer.legal', 'Legal', NOW()),
('en', 'footer.privacy', 'Privacy Policy', NOW()),
('en', 'footer.terms', 'Terms of Use', NOW()),
('en', 'footer.sslSecure', 'SSL Secure', NOW()),
('en', 'footer.copyright', '© 2026 ChiosBox — Greek IKE Company. All rights reserved.', NOW()),
('en', 'footer.location', 'Chios, Greece', NOW()),
('en', 'hero.tag', 'Turkey → EU Shipping Made Easy', NOW()),
('en', 'hero.badge', 'Turkey → EU Shipping Made Easy', NOW()),
('en', 'hero.title.line1', 'European Delivery', NOW()),
('en', 'hero.title.line2', 'Your Address', NOW()),
('en', 'hero.title.line3', 'Ready', NOW()),
('en', 'hero.title1', 'European Delivery', NOW()),
('en', 'hero.title2', 'Your Address', NOW()),
('en', 'hero.title3', 'Ready', NOW()),
('en', 'hero.description', 'Shop from Turkey, let your packages arrive at our warehouse on Chios. Consolidate, save, and we deliver to your door.', NOW()),
('en', 'hero.cta', 'Get Your Address Now', NOW()),
('en', 'hero.ctaSecondary', 'How It Works?', NOW()),
('en', 'hero.howItWorks', 'How It Works?', NOW()),
('en', 'hero.feature1', 'Starting from €9.99/month', NOW()),
('en', 'hero.feature2', 'Instant address', NOW()),
('en', 'hero.feature3', 'Door-to-door delivery', NOW()),
('en', 'howItWorks.tag', 'Easy & Fast', NOW()),
('en', 'howItWorks.title', 'How It Works?', NOW()),
('en', 'howItWorks.description', 'Manage your shipping from Turkey to Europe in four simple steps.', NOW()),
('en', 'howItWorks.step1.number', '01', NOW()),
('en', 'howItWorks.step1.title', 'Shop', NOW()),
('en', 'howItWorks.step1.description', 'Shop from any e-commerce site in Turkey. Use your ChiosBox address as the delivery address.', NOW()),
('en', 'howItWorks.step1.desc', 'Shop from any e-commerce site in Turkey. Use your ChiosBox address as the delivery address.', NOW()),
('en', 'howItWorks.step2.number', '02', NOW()),
('en', 'howItWorks.step2.title', 'Arrive at Our Warehouse', NOW()),
('en', 'howItWorks.step2.description', 'Your packages arrive at our secure warehouse on Chios. The barcode is scanned and logged into the system.', NOW()),
('en', 'howItWorks.step2.desc', 'Your packages arrive at our secure warehouse on Chios. The barcode is scanned and logged into the system.', NOW()),
('en', 'howItWorks.step3.number', '03', NOW()),
('en', 'howItWorks.step3.title', 'Photo Approval', NOW()),
('en', 'howItWorks.step3.description', 'Warehouse staff takes a photo of your package. You view it from your panel and verify the contents.', NOW()),
('en', 'howItWorks.step3.desc', 'Warehouse staff takes a photo of your package. You view it from your panel and verify the contents.', NOW()),
('en', 'howItWorks.step4.number', '04', NOW()),
('en', 'howItWorks.step4.title', 'Pick Up', NOW()),
('en', 'howItWorks.step4.description', 'Consolidate your packages, save money. Show your QR code, pick up on your island. It''s that simple!', NOW()),
('en', 'howItWorks.step4.desc', 'Consolidate your packages, save money. Show your QR code, pick up on your island. It''s that simple!', NOW()),
('en', 'pricing.tag', 'Transparent Pricing', NOW()),
('en', 'pricing.title', 'Calculate Your Cost', NOW()),
('en', 'pricing.description', 'Select how many packages you have and how long you want to store them. See your estimated cost instantly.', NOW()),
('en', 'pricing.parameters', 'Parameters', NOW()),
('en', 'pricing.packageCount', 'Package Count', NOW()),