INSERT INTO translations (language_code, key, value, updated_at) VALUES
('tr', 'nav.howItWorks', 'Nasıl Çalışır?', NOW()),
('tr', 'nav.pricing', 'Fiyatlar', NOW()),
('tr', 'nav.trust', 'Güven', NOW()),
('tr', 'nav.logout', 'Çıkış', NOW()),
('tr', 'nav.login', 'Giriş Yap', NOW()),
('tr', 'nav.getAddress', 'Hemen Adresini Al', NOW()),
('tr', 'footer.description', 'Türkiye''den AB''ye e-ticaret alışverişi yapanlar için Sakız Adası merkezli paket konsolidasyon yönetimi.', NOW()),
('tr', 'footer.service', 'Hizmet', NOW()),
('tr', 'footer.howItWorks', 'Nasıl Çalışır?', NOW()),
('tr', 'footer.pricing', 'Fiyatlandırma', NOW()),
('tr', 'footer.consolidation', 'Konsolidasyon', NOW()),
('tr', 'footer.support', 'Destek', NOW()),
('tr', 'footer.faq', 'Sıkça Sorulan Sorular', NOW()),
('tr', 'footer.contact', 'İletişim', NOW()),
('tr', 'footer.tracking', 'Kargo Takip', NOW()),
('tr', 'footer.legal', 'Yasal', NOW()),
('tr', 'footer.privacy', 'Gizlilik Politikası', NOW()),
('tr', 'footer.terms', 'Kullanım Koşulları', NOW()),
('tr', 'footer.sslSecure', 'SSL Güvenli', NOW()),
('tr', 'footer.copyright', '© 2026 ChiosBox — Yunanistan IKE Şirketi. Tüm hakları saklıdır.', NOW()),
('tr', 'footer.location', 'Sakız Adası, Yunanistan', NOW()),
('tr', 'hero.tag', 'Türkiye → AB Kargo Kolaylığı', NOW()),
('tr', 'hero.badge', 'Türkiye → AB Kargo Kolaylığı', NOW()),
('tr', 'hero.title.line1', 'Avrupa Teslimat', NOW()),
('tr', 'hero.title.line2', 'Adresiniz', NOW()),
('tr', 'hero.title.line3', 'Hazır', NOW()),
('tr', 'hero.title1', 'Avrupa Teslimat', NOW()),
('tr', 'hero.title2', 'Adresiniz', NOW()),
('tr', 'hero.title3', 'Hazır', NOW()),
('tr', 'hero.description', 'Türkiye''den alışveriş yapın, paketleriniz Sakız Adası''ndaki depomuza gelsin. Birleştirin, tasarruf edin, kapınıza teslim edelim.', NOW()),
('tr', 'hero.cta', 'Hemen Adresini Al', NOW()),
('tr', 'hero.ctaSecondary', 'Nasıl Çalışır?', NOW()),
('tr', 'hero.howItWorks', 'Nasıl Çalışır?', NOW()),
('tr', 'hero.feature1', '€9.99/ay''dan başlayan fiyatlarla', NOW()),
('tr', 'hero.feature2', 'Anında adres', NOW()),
('tr', 'hero.feature3', 'Kapıdan kapıya teslimat', NOW()),
('tr', 'howItWorks.tag', 'Kolay & Hızlı', NOW()),
('tr', 'howItWorks.title', 'Nasıl Çalışır?', NOW()),
('tr', 'howItWorks.description', 'Dört basit adımda Türkiye''den Avrupa''ya kargo teslimatınızı yönetin.', NOW()),
('tr', 'howItWorks.step1.number', '01', NOW()),
('tr', 'howItWorks.step1.title', 'Alışveriş Yapın', NOW()),
('tr', 'howItWorks.step1.description', 'Türkiye''deki herhangi bir e-ticaret sitesinden alışveriş yapın. ChiosBox adresinizi teslimat adresi olarak kullanın.', NOW()),
('tr', 'howItWorks.step1.desc', 'Türkiye''deki herhangi bir e-ticaret sitesinden alışveriş yapın. ChiosBox adresinizi teslimat adresi olarak kullanın.', NOW()),
('tr', 'howItWorks.step2.number', '02', NOW()),
('tr', 'howItWorks.step2.title', 'Depomuza Gelsin', NOW()),
('tr', 'howItWorks.step2.description', 'Paketleriniz Sakız Adası''ndaki güvenli depomuza ulaşır. Barkod okutulur ve sistemde kayda girer.', NOW()),
('tr', 'howItWorks.step2.desc', 'Paketleriniz Sakız Adası''ndaki güvenli depomuza ulaşır. Barkod okutulur ve sistemde kayda girer.', NOW()),
('tr', 'howItWorks.step3.number', '03', NOW()),
('tr', 'howItWorks.step3.title', 'Fotoğraf Onayı', NOW()),
('tr', 'howItWorks.step3.description', 'Depo görevlisi paketinizin fotoğrafını çeker. Panelinizden paketinizi görür, içeriğini doğrularsınız.', NOW()),
('tr', 'howItWorks.step3.desc', 'Depo görevlisi paketinizin fotoğrafını çeker. Panelinizden paketinizi görür, içeriğini doğrularsınız.', NOW()),
('tr', 'howItWorks.step4.number', '04', NOW()),
('tr', 'howItWorks.step4.title', 'Teslim Alın', NOW()),
('tr', 'howItWorks.step4.description', 'Paketlerinizi birleştirin, tasarruf edin. QR kodunuzu gösterin, adanızda teslim alın. Bu kadar basit!', NOW()),
('tr', 'howItWorks.step4.desc', 'Paketlerinizi birleştirin, tasarruf edin. QR kodunuzu gösterin, adanızda teslim alın. Bu kadar basit!', NOW()),
('tr', 'pricing.tag', 'Şeffaf Fiyatlandırma', NOW()),
('tr', 'pricing.title', 'Maliyetinizi Hesaplayın', NOW()),
('tr', 'pricing.description', 'Kaç paketiniz var ve ne kadar depolamak istediğinizi seçin. Anında tahmini maliyetinizi görün.', NOW()),
('tr', 'pricing.parameters', 'Parametreler', NOW()),
('tr', 'pricing.packageCount', 'Paket Sayısı', NOW()),
('tr', 'pricing.storageDays', 'Depolama Süresi (Gün)', NOW()),
('tr', 'pricing.storage1', '1 gün', NOW()),
('tr', 'pricing.storage30', '30 gün', NOW()),
('tr', 'pricing.freeStorage', 'İlk 14 gün ücretsiz depolama', NOW()),
('tr', 'pricing.acceptFeeInfo', 'Paket başı kabul ücreti €4', NOW()),
('tr', 'pricing.monthlyCost', 'Aylık Tahmini Maliyet', NOW()),
('tr', 'pricing.acceptFee', 'Kabul Ücreti', NOW()),
('tr', 'pricing.consolidationFee', 'Konsolidasyon Ücreti', NOW()),
('tr', 'pricing.demurrageFee', 'Gecikme Ücreti', NOW()),
('tr', 'pricing.total', 'Toplam', NOW()),
('tr', 'pricing.savings', 'Birleştirerek ~€{amount} tasarruf edebilirsiniz!', NOW()),
('tr', 'pricing.planTitle', 'Size Uygun Paketi Seçin', NOW()),
('tr', 'pricing.planDesc', 'Türkiye''den Avrupa''ya, Avrupa''dan Türkiye''ye kapıdan kapıya kargo ayrıcalığı', NOW()),
('tr', 'pricing.basic.name', 'Temel', NOW()),
('tr', 'pricing.basic.price', '€9.99', NOW()),
('tr', 'pricing.basic.pricePeriod', '/ay', NOW()),
('tr', 'pricing.basic.subtitle', 'Basit adres, basit teslimat', NOW()),
('tr', 'pricing.basic.f1', 'ChiosBox EU adresi', NOW()),
('tr', 'pricing.basic.f2', '14 gün ücretsiz depolama', NOW()),
('tr', 'pricing.basic.f3', 'Panel erişimi', NOW()),
('tr', 'pricing.basic.f4', 'E-posta bildirimleri', NOW()),
('tr', 'pricing.basic.cta', 'Temel Paketi Seç', NOW()),
('tr', 'pricing.premium.badge', 'En Popüler', NOW()),
('tr', 'pricing.premium.name', 'Premium', NOW()),
('tr', 'pricing.premium.subtitle', 'Tam kontrol, maksimum tasarruf', NOW()),
('tr', 'pricing.premium.f1', 'Her şey Temel pakette', NOW()),
('tr', 'pricing.premium.f2', '21 gün ücretsiz depolama', NOW()),
('tr', 'pricing.premium.f3', 'Ücretsiz konsolidasyon', NOW()),
('tr', 'pricing.premium.f4', 'Türkiye teslimat takibi', NOW()),
('tr', 'pricing.premium.f5', 'Özel destek hattı', NOW()),
('tr', 'pricing.premium.cta', 'Premium Paketi Seç', NOW()),
('tr', 'pricing.month', '/ay', NOW()),
('tr', 'pricing.mostPopular', 'En Popüler', NOW()),
('tr', 'pricing.fee.accept', 'Kabul Ücreti', NOW()),
('tr', 'pricing.fee.storage14', '14 gün ücretsiz depolama', NOW()),
('tr', 'pricing.fee.acceptInfo', 'Paket başı kabul ücreti €4', NOW()),
('tr', 'pricing.fee.acceptUnit', '× €{fee}', NOW()),
('tr', 'pricing.demurrageFeeLabel', '{days} gün × €{fee}', NOW()),
('tr', 'trust.tag', 'Güvenilir & Şeffaf', NOW()),
('tr', 'trust.title', 'Bize Güvenin', NOW()),
('tr', 'trust.description', 'Binlerce kullanıcı ChiosBox ile Türkiye''den Avrupa''ya güvenle alışveriş yapıyor.', NOW()),
('tr', 'trust.stat1.label', 'Aktif Kullanıcı', NOW()),
('tr', 'trust.stat2.label', 'Teslim Edilen Paket', NOW()),
('tr', 'trust.stat3.label', 'Memnuniyet Oranı', NOW()),
('tr', 'trust.stat4.label', 'Ortalama Teslimat', NOW()),
('tr', 'trust.stat4.suffix', 'gün', NOW()),
('tr', 'trust.badge1.title', 'Yunanistan IKE Tescilli', NOW()),
('tr', 'trust.badge1.desc', 'Resmi olarak kayıtlı şirket', NOW()),
('tr', 'trust.badge2.title', 'SSL 256-bit Şifreleme', NOW()),
('tr', 'trust.badge2.desc', 'Verileriniz güvende', NOW()),
('tr', 'trust.badge3.title', 'Stripe Ödeme Altyapısı', NOW()),
('tr', 'trust.badge3.desc', 'Güvenli online ödeme', NOW()),
('tr', 'trust.badge4.title', 'AB Uyumlu', NOW()),
('tr', 'trust.badge4.desc', 'Avrupa Birliği düzenlemelerine uygun', NOW()),
('tr', 'trust.testimonial1.text', 'Artık Türkiye''den aldığım her şeyi ChiosBox üzerinden yönetiyorum. Birleştirme özelliği sayesinde kargo maliyetlerim yarı yarıya düştü.', NOW()),
('tr', 'trust.testimonial2.text', 'Panel çok kolay kullanılıyor. Paketlerimin fotoğrafını görüyorum, ne zaman geleceğini biliyorum. Harika bir hizmet!', NOW()),
('tr', 'trust.testimonial3.text', 'QR kod ile teslim almak çok pratik. Ofise gittim, kodu gösterdim, 2 dakikada paketimi aldım. Kesinlikle tavsiye ediyorum.', NOW()),
('tr', 'finalCta.tag', 'Hemen Başlayın', NOW()),
('tr', 'finalCta.title', 'Hemen Başlayın', NOW()),
('tr', 'finalCta.title1', 'Avrupa Teslimat Adresinizi', NOW()),
('tr', 'finalCta.title2', 'Hemen Alın', NOW()),
('tr', 'finalCta.description', '€9.99/ay''dan başlayan fiyatlarla, Türkiye''den yaptığınız alışverişleri Sakız Adası üzerinden AB''ye sorunsuz teslim edelim.', NOW()),
('tr', 'finalCta.cta', 'Hemen Başla', NOW()),
('tr', 'finalCta.cta2', '7 gün ücretsiz deneme. Kredi kartı gerekmez.', NOW()),
('tr', 'finalCta.trust1', 'Anında ChiosBox ID', NOW()),
('tr', 'finalCta.trust2', 'Kapıdan kapıya teslimat', NOW()),
('tr', 'finalCta.trust3', 'Güvenli ödeme', NOW()),
('tr', 'pkgReq.tag', 'Hızlı Başvuru', NOW()),
('tr', 'pkgReq.title', 'Paket İsteği Oluştur', NOW()),
('tr', 'pkgReq.description', 'Türkiye''den gelen paketinizi bildirin, depomuzda güvenle karşılayalım.', NOW()),
('tr', 'pkgReq.ready', '3 Adımda Hazır', NOW()),
('tr', 'pkgReq.readyDesc', 'Bilgilerinizi girin, paketinizi takip edelim', NOW()),
('tr', 'pkgReq.success.title', 'İsteğiniz Alındı!', NOW()),
('tr', 'pkgReq.success.desc', 'Paket bildiriminiz kaydedildi. Türkiye''den depomuza ulaştığında sizi bilgilendireceğiz.', NOW()),
('tr', 'pkgReq.newRequest', 'Yeni İstek', NOW()),
('tr', 'pkgReq.registerTrack', 'Kayıt Ol & Takip Et', NOW()),
('tr', 'pkgReq.step1.title', 'Kişisel Bilgiler', NOW()),
('tr', 'pkgReq.fullName', 'Ad Soyad *', NOW()),
('tr', 'pkgReq.fullNamePlaceholder', 'Adınız Soyadınız', NOW()),
('tr', 'pkgReq.email', 'E-posta *', NOW()),
('tr', 'pkgReq.phone', 'Telefon', NOW()),
('tr', 'pkgReq.step2.title', 'Kargo Bilgileri', NOW()),
('tr', 'pkgReq.carrier', 'Kargo Firması *', NOW()),
('tr', 'pkgReq.trackingNo', 'Takip Numarası *', NOW()),
('tr', 'pkgReq.trackingPlaceholder', 'Kargo takip numaranız', NOW()),
('tr', 'pkgReq.content', 'Paket İçeriği *', NOW()),
('tr', 'pkgReq.contentPlaceholder', 'Paketinizin içinde ne var?', NOW()),
('tr', 'pkgReq.estimatedValue', 'Tahmini Değer (€)', NOW()),
('tr', 'pkgReq.step3.title', 'Özet & Onay', NOW()),
('tr', 'pkgReq.summaryName', 'Ad Soyad', NOW()),
('tr', 'pkgReq.summaryEmail', 'E-posta', NOW()),
('tr', 'pkgReq.summaryPhone', 'Telefon', NOW()),
('tr', 'pkgReq.summaryCarrier', 'Kargo', NOW()),
('tr', 'pkgReq.summaryTracking', 'Takip No', NOW()),
('tr', 'pkgReq.summaryContent', 'İçerik', NOW()),
('tr', 'pkgReq.summaryValue', 'Tahmini Değer', NOW()),
('tr', 'pkgReq.notes', 'Notlar', NOW()),
('tr', 'pkgReq.notesPlaceholder', 'Eklemek istediğiniz bir not var mı?', NOW()),
('tr', 'pkgReq.info', 'Paket bildiriminiz depomuzda işleme alınacaktır. Kayıt olarak paketlerinizi panelden takip edebilir, konsolidasyon ve teslimat seçeneklerinden yararlanabilirsiniz.', NOW()),
('tr', 'pkgReq.back', 'Geri', NOW()),
('tr', 'pkgReq.continue', 'Devam', NOW()),
('tr', 'pkgReq.submit', 'İsteği Gönder', NOW()),
('tr', 'pkgReq.carrier.yurtici', 'Yurtiçi Kargo', NOW()),
('tr', 'pkgReq.carrier.aras', 'Aras Kargo', NOW()),
('tr', 'pkgReq.carrier.mng', 'MNG Kargo', NOW()),
('tr', 'pkgReq.carrier.ptt', 'PTT Kargo', NOW()),
('tr', 'pkgReq.carrier.surat', 'Sürat Kargo', NOW()),
('tr', 'pkgReq.carrier.diger', 'Diğer', NOW()),
('tr', 'dashboard.title', 'Yönetim Paneli', NOW()),
('tr', 'dashboard.welcome', 'Hoş geldin, {name}', NOW()),
('tr', 'dashboard.totalPackages', 'Toplam Paket', NOW()),
('tr', 'dashboard.inWarehouse', 'Depoda', NOW()),
('tr', 'dashboard.last7Days', 'Son 7 Gün', NOW()),
('tr', 'dashboard.newPackages', 'yeni paket', NOW()),
('tr', 'dashboard.weeklyRevenue', 'Haftalık Gelir', NOW()),
('tr', 'dashboard.statusDistribution', 'Durum Dağılımı', NOW()),
('tr', 'dashboard.recentActivity', 'Son Aktiviteler', NOW()),
('tr', 'dashboard.unknown', 'Bilinmeyen', NOW()),
('tr', 'dashboard.demurrageAlert', 'Gecikme Uyarısı', NOW()),
('tr', 'dashboard.demurrageDesc', '{count} paket 14 günü aştı', NOW()),
('tr', 'dashboard.pendingInvoices', 'Bekleyen Faturalar', NOW()),
('tr', 'dashboard.pendingInvoiceDesc', '{count} fatura ödenmeyi bekliyor', NOW()),
('tr', 'dashboard.shelfUsage', 'Raf Kullanımı', NOW()),
('tr', 'dashboard.quickActions', 'Hızlı İşlemler', NOW()),
('tr', 'status.beklemede', 'Beklemede', NOW()),
('tr', 'status.yolda', 'Yolda', NOW()),
('tr', 'status.depoda', 'Depoda', NOW()),
('tr', 'status.birlestirildi', 'Birleştirildi', NOW()),
('tr', 'status.teslimEdildi', 'Teslim Edildi', NOW()),
('tr', 'action.kabul', 'Kabul', NOW()),
('tr', 'actions.delivery', 'Teslimat', NOW()),
('tr', 'action.delay', 'Gecikme', NOW()),
('tr', 'action.packages', 'Paketler', NOW()),
('tr', 'action.faturalar', 'Faturalar', NOW()),
('tr', 'action.musteriler', 'Müşteriler', NOW()),
('tr', 'packages.title', 'Paketler', NOW()),
('tr', 'packages.count', '{total} paket', NOW()),
('tr', 'packages.searchPlaceholder', 'Takip no ile ara...', NOW()),
('tr', 'packages.allStatuses', 'Tüm Durumlar', NOW()),
('tr', 'packages.notFound', 'Paket bulunamadı', NOW()),
('tr', 'packages.daysAgo', '{n} gün', NOW()),
('tr', 'packages.previous', 'Önceki', NOW()),
('tr', 'packages.next', 'Sonraki', NOW()),
('tr', 'packages.deleteConfirm', 'Bu paketi silmek istediğinize emin misiniz?', NOW()),
('tr', 'packages.detail.customer', 'Müşteri', NOW()),
('tr', 'packages.detail.carrier', 'Kargo', NOW()),
('tr', 'packages.detail.trackingNo', 'Takip No', NOW()),
('tr', 'packages.detail.shelf', 'Raf', NOW()),
('tr', 'packages.detail.arrival', 'Varış', NOW()),
('tr', 'packages.detail.notification', 'Bildirim', NOW()),
('tr', 'packages.detail.inWarehouse', 'Depoda', NOW()),
('tr', 'packages.detail.weight', 'Ağırlık', NOW()),
('tr', 'packages.detail.dimensions', 'Boyut', NOW()),
('tr', 'packages.detail.demurrageFee', 'Gecikme Ücreti', NOW()),
('tr', 'packages.detail.notes', 'Not', NOW()),
('tr', 'packages.detail.updateStatus', 'Durum Güncelle', NOW()),
('tr', 'packages.detail.delete', 'Paketi Sil', NOW()),
('tr', 'packages.detail.cancel', 'Vazgeç', NOW()),
('tr', 'packages.detail.deleting', 'Siliniyor...', NOW()),
('tr', 'packages.detail.confirmDelete', 'Evet, Sil', NOW()),
('tr', 'customers.title', 'Müşteriler', NOW()),
('tr', 'customers.count', '{total} müşteri', NOW()),
('tr', 'customers.searchPlaceholder', 'İsim, email veya ChiosBox ID ile ara...', NOW()),
('tr', 'customers.notFound', 'Müşteri bulunamadı', NOW()),
('tr', 'customers.packageCount', '{n} paket', NOW()),
('tr', 'customers.pending', 'bekliyor', NOW()),
('tr', 'customers.previous', 'Önceki', NOW()),
('tr', 'customers.next', 'Sonraki', NOW()),
('tr', 'invoices.title', 'Faturalar', NOW()),
('tr', 'invoices.count', '{total} fatura', NOW()),
('tr', 'invoices.newInvoice', '+ Yeni Fatura', NOW()),
('tr', 'invoices.all', 'Tümü', NOW()),
('tr', 'invoices.pending', 'Beklemede', NOW()),
('tr', 'invoices.paid', 'Ödendi', NOW()),
('tr', 'invoices.cancelled', 'İptal', NOW()),
('tr', 'invoices.notFound', 'Fatura bulunamadı', NOW()),
('tr', 'invoices.acceptFee', 'Kabul: €{amount}', NOW()),
('tr', 'invoices.consolidationFee', 'Birleştirme: €{amount}', NOW()),
('tr', 'invoices.demurrageFee', 'Gecikme: €{amount}', NOW()),
('tr', 'invoices.packageCount', '{n} paket', NOW()),
('tr', 'invoices.previous', 'Önceki', NOW()),
('tr', 'invoices.next', 'Sonraki', NOW()),
('tr', 'invoices.createModal.title', 'Yeni Fatura', NOW()),
('tr', 'invoices.createModal.customer', 'Müşteri', NOW()),
('tr', 'invoices.createModal.selectCustomer', 'Müşteri seçin', NOW()),
('tr', 'invoices.createModal.packetsToBill', 'Faturalanacak Paketler', NOW()),
('tr', 'invoices.createModal.noUnbilled', 'Faturalanmamış paket bulunamadı', NOW()),
('tr', 'invoices.createModal.consolidationFee', 'Birleştirme Ücreti', NOW()),
('tr', 'invoices.createModal.acceptFee', 'Kabul Ücreti ({count} paket × €{fee})', NOW()),
('tr', 'invoices.createModal.demurrageFee', 'Gecikme Ücreti', NOW()),
('tr', 'invoices.createModal.consolidationLine', 'Birleştirme Ücreti', NOW()),
('tr', 'invoices.createModal.total', 'Toplam', NOW()),
('tr', 'invoices.createModal.creating', 'Oluşturuluyor...', NOW()),
('tr', 'invoices.createModal.createButton', 'Fatura Oluştur (€{amount})', NOW()),
('tr', 'invoices.createModal.selectCustomerError', 'Müşteri seçin', NOW()),
('tr', 'invoices.createModal.selectPackageError', 'En az bir paket seçin', NOW()),
('tr', 'invoices.createModal.createError', 'Fatura oluşturulamadı', NOW()),
('tr', 'invoices.detail.customer', 'Müşteri', NOW()),
('tr', 'invoices.detail.date', 'Tarih', NOW()),
('tr', 'invoices.detail.paymentDate', 'Ödeme Tarihi', NOW()),
('tr', 'invoices.detail.acceptFee', 'Kabul Ücreti', NOW()),
('tr', 'invoices.detail.consolidationFee', 'Birleştirme Ücreti', NOW()),
('tr', 'invoices.detail.demurrageFee', 'Gecikme Ücreti', NOW()),
('tr', 'invoices.detail.total', 'Toplam', NOW()),
('tr', 'invoices.detail.packets', 'Paketler ({count})', NOW()),
('tr', 'invoices.detail.markPaid', 'Ödendi İşaretle', NOW()),
('tr', 'invoices.detail.cancel', 'İptal Et', NOW()),
('tr', 'invoices.detail.undoCancel', 'İptali Geri Al', NOW()),
('tr', 'invoices.detail.undoPayment', 'Ödemeyi Geri Al', NOW()),
('tr', 'intake.title', 'Paket Kabul', NOW()),
('tr', 'intake.newIntake', 'Yeni Kabul', NOW()),
('tr', 'intake.error.search', 'Arama başarısız', NOW()),
('tr', 'intake.error.searchPaket', 'Paket aranırken hata oluştu', NOW()),
('tr', 'intake.error.saveFailed', 'Kayıt başarısız', NOW()),
('tr', 'intake.error.generic', 'Bir hata oluştu', NOW()),
('tr', 'intake.barcodeInstruction', 'Barkodu kameraya gösterin veya manuel girin', NOW()),
('tr', 'intake.barcodeLabel', 'Barkod / Takip No', NOW()),
('tr', 'intake.barcodePlaceholder', 'Barkodu okutun veya yazın', NOW()),
('tr', 'intake.notFound', 'Bu takip numarasına ait paket bulunamadı', NOW()),
('tr', 'intake.customer', 'Müşteri', NOW()),
('tr', 'intake.content', 'İçerik', NOW()),
('tr', 'intake.notes', 'Not: {text}', NOW()),
('tr', 'intake.shelfAssignment', 'Raf Atama', NOW()),
('tr', 'intake.saving', 'Kaydediliyor...', NOW()),
('tr', 'intake.save', 'KAYDET', NOW()),
('tr', 'intake.saved', 'Kaydedildi!', NOW()),
('tr', 'intake.shelfPrefix', 'Raf: {shelf}', NOW()),
('tr', 'intake.unknown', 'Bilinmeyen', NOW()),
('tr', 'pickup.title', 'Teslimat', NOW()),
('tr', 'pickup.newDelivery', 'Yeni Teslimat', NOW()),
('tr', 'pickup.error.search', 'Arama başarısız', NOW()),
('tr', 'pickup.error.searchPaket', 'Paket aranırken hata oluştu', NOW()),
('tr', 'pickup.error.codeFailed', 'Kod üretilemedi', NOW()),
('tr', 'pickup.error.generic', 'Bir hata oluştu', NOW()),
('tr', 'pickup.error.deliveryFailed', 'Teslimat başarısız', NOW()),
('tr', 'pickup.inputPlaceholder', 'Takip no veya CBX ID girin', NOW()),
('tr', 'pickup.notFound', 'Bu koda ait paket bulunamadı', NOW()),
('tr', 'pickup.toDeliver', 'Teslim Edilecek', NOW()),
('tr', 'pickup.verificationTitle', 'Doğrulama Kodu', NOW()),
('tr', 'pickup.verificationDesc', 'Müşteriye tek kullanımlık kod gönderin', NOW()),
('tr', 'pickup.sending', 'Gönderiliyor...', NOW()),
('tr', 'pickup.sendCode', 'Kod Gönder', NOW()),
('tr', 'pickup.mockCodeLabel', 'Doğrulama Kodu (Mock)', NOW()),
('tr', 'pickup.mockCodeNote', 'Gerçek SMS ile müşteriye gönderilecek', NOW()),
('tr', 'pickup.customerCode', 'Müşterinin Kodu', NOW()),
('tr', 'pickup.codePlaceholder', '6 haneli kod', NOW()),
('tr', 'pickup.delivering', 'Teslim Ediliyor...', NOW()),
('tr', 'pickup.deliver', 'TESLİM ET', NOW()),
('tr', 'pickup.delivered', 'Teslim Edildi!', NOW()),
('tr', 'demurrage.title', 'Gecikme Radarı', NOW()),
('tr', 'demurrage.subtitle', 'Depolama süresini aşan paketleri takip edin', NOW()),
('tr', 'demurrage.normal', 'Normal (≤14 gün)', NOW()),
('tr', 'demurrage.delay', 'Gecikme (15-29 gün)', NOW()),
('tr', 'demurrage.abandonedZone', 'Terk Edildi (30+ gün)', NOW()),
('tr', 'demurrage.abandoned', 'Terk Edildi', NOW()),
('tr', 'demurrage.unknown', 'Bilinmeyen', NOW()),
('tr', 'demurrage.shelfPrefix', 'Raf {shelf}', NOW()),
('tr', 'demurrage.arrival', 'Geliş: {date}', NOW()),
('tr', 'demurrage.daysLabel', '{n} gün', NOW()),
('tr', 'demurrage.demurrageFee', 'Gecikme Ücreti', NOW()),
('tr', 'demurrage.error.applyFailed', 'Gecikme ücreti uygulanamadı', NOW()),
('tr', 'demurrage.cancel', 'Vazgeç', NOW()),
('tr', 'demurrage.applyAmount', '€{amount} Uygula', NOW()),
('tr', 'demurrage.invoiceCreated', 'Fatura Oluşturuldu!', NOW()),
('tr', 'demurrage.applyFeeButton', 'Gecikme Ücreti Uygula (€{amount})', NOW()),
('tr', 'demurrage.confirmDelete', 'Evet, Sil', NOW()),
('tr', 'demurrage.discard', 'Tasfiye Et', NOW()),
('tr', 'demurrage.allClear', 'Tüm paketler temizlendi', NOW()),
('tr', 'demurrage.detail.customer', 'Müşteri', NOW()),
('tr', 'demurrage.detail.content', 'İçerik', NOW()),
('tr', 'demurrage.detail.shelf', 'Raf', NOW()),
('tr', 'demurrage.detail.arrivalDate', 'Geliş Tarihi', NOW()),
('tr', 'demurrage.detail.inWarehouse', 'Depoda', NOW()),
('tr', 'demurrage.detail.freeDaysLeft', 'Kalan Ücretsiz Gün', NOW()),
('tr', 'demurrage.detail.demurrageFee', 'Gecikme Ücreti', NOW()),
('tr', 'demurrage.detail.appliedFee', 'Uygulanan Ücret', NOW()),
('tr', 'demurrage.detail.weight', 'Ağırlık', NOW()),
('tr', 'demurrage.detail.dimensions', 'Boyut', NOW()),
('tr', 'demurrage.detail.notes', 'Not', NOW()),
('tr', 'users.title', 'Kullanıcı Yönetimi', NOW()),
('tr', 'users.subtitle', 'Rol ve izin atamaları', NOW()),
('tr', 'users.searchPlaceholder', 'İsim, email veya ChiosBox ID ile ara...', NOW()),
('tr', 'users.error.updateFailed', 'Güncelleme başarısız', NOW()),
('tr', 'users.editModal.title', 'Kullanıcı Düzenle', NOW()),
('tr', 'users.editModal.adminAccess', 'Admin Yetkisi', NOW()),
('tr', 'users.editModal.adminAccessDesc', 'Admin paneline erişim', NOW()),
('tr', 'users.editModal.permissions', 'İzinler', NOW()),
('tr', 'users.editModal.superAdmin', 'Super admin — tüm yetkilere sahip, düzenlenemez.', NOW()),
('tr', 'users.editModal.saving', 'Kaydediliyor...', NOW()),
('tr', 'users.editModal.save', 'Kaydet', NOW()),
('tr', 'perm.intake', 'Kabul (Paket Kabul)', NOW()),
('tr', 'perm.pickup', 'Teslimat', NOW()),
('tr', 'perm.demurrage', 'Gecikme Yönetimi', NOW()),
('tr', 'perm.packages', 'Paket Listesi', NOW()),
('tr', 'perm.invoices', 'Fatura Yönetimi', NOW()),
('tr', 'perm.customers', 'Müşteri Yönetimi', NOW()),
('tr', 'perm.settings', 'Sistem Ayarları', NOW()),
('tr', 'error.root.title', 'Bir şeyler ters gitti', NOW()),
('tr', 'error.root.description', 'Beklenmeyen bir hata oluştu. Lütfen tekrar deneyin.', NOW()),
('tr', 'error.root.retry', 'Tekrar Dene', NOW()),
('tr', 'notFound.title', 'Sayfa Bulunamadı', NOW()),
('tr', 'notFound.description', 'Aradığınız sayfa mevcut değil veya taşınmış olabilir.', NOW()),
('tr', 'notFound.homeLink', 'Ana Sayfaya Dön', NOW()),
('tr', 'error.dashboard.title', 'Bir hata oluştu', NOW()),
('tr', 'error.dashboard.description', 'Sayfa yüklenirken bir sorun yaşandı.', NOW()),
('tr', 'error.dashboard.retry', 'Tekrar Dene', NOW()),
('tr', 'error.admin.title', 'Yönetim Paneli Hatası', NOW()),
('tr', 'error.admin.description', 'Sayfa yüklenirken bir sorun yaşandı.', NOW()),
('tr', 'error.admin.retry', 'Tekrar Dene', NOW()),
('tr', 'loading.text', 'Yükleniyor...', NOW()),
('tr', 'loading.adminText', 'Yükleniyor...', NOW()),
('tr', 'login.email', 'E-posta', NOW()),
('tr', 'login.password', 'Şifre', NOW()),
('tr', 'login.rememberMe', 'Beni Hatırla', NOW()),
('tr', 'login.forgotPassword', 'Şifremi Unuttum', NOW()),
('tr', 'login.submit', 'Giriş Yap', NOW()),
('tr', 'login.submitting', 'Giriş Yapılıyor...', NOW()),
('tr', 'login.noAccount', 'Hesabınız yok mu?', NOW()),
('tr', 'login.registerLink', 'Kayıt Olun', NOW()),
('tr', 'register.steps.info', 'Bilgiler', NOW()),
('tr', 'register.steps.emailVerify', 'E-posta', NOW()),
('tr', 'register.steps.phoneVerify', 'Telefon', NOW()),
('tr', 'register.steps.payment', 'Ödeme', NOW()),
('tr', 'register.nameLabel', 'Ad Soyad', NOW()),
('tr', 'register.namePlaceholder', 'Adınız Soyadınız', NOW()),
('tr', 'register.emailLabel', 'E-posta', NOW()),
('tr', 'register.emailPlaceholder', 'ornek@email.com', NOW()),
('tr', 'register.passwordLabel', 'Şifre', NOW()),
('tr', 'register.passwordConfirmLabel', 'Şifre Tekrar', NOW()),
('tr', 'register.passwordMismatch', 'Şifreler eşleşmiyor', NOW()),
('tr', 'register.planLabel', 'Plan Seçin', NOW()),
('tr', 'register.tosAgreement', 'Kullanım koşullarını ve gizlilik politikasını okudum, kabul ediyorum.', NOW()),
('tr', 'register.tosRequired', 'Kullanım koşullarını kabul etmelisiniz', NOW()),
('tr', 'register.continue', 'Devam Et', NOW()),
('tr', 'register.loginLink', 'Giriş Yapın', NOW()),
('tr', 'register.emailVerifyTitle', 'E-postanızı Doğrulayın', NOW()),
('tr', 'register.emailVerifyDescription', 'adresine gönderilen 6 haneli kodu girin.', NOW()),
('tr', 'register.verifying', 'Doğrulanıyor...', NOW()),
('tr', 'register.resendCode', 'Kodu Tekrar Gönder', NOW()),
('tr', 'register.smsNotReceived', 'SMS gelmedi mi? {countdown}s sonra tekrar gönderin', NOW()),
('tr', 'register.backToInfo', 'Bilgilere Dön', NOW()),
('tr', 'register.phoneVerifyTitle', 'Telefonunuzu Doğrulayın', NOW()),
('tr', 'register.phoneVerifyDescription', 'numarasına gönderilen 6 haneli kodu girin.', NOW()),
('tr', 'register.phoneTitle', 'Telefon Numaranız', NOW()),
('tr', 'register.phoneDescription', 'Teslimat bildirimleri için telefon numaranızı girin.', NOW()),
('tr', 'register.phoneLabel', 'Telefon Numarası', NOW()),
('tr', 'register.sendSmsCode', 'SMS Kodu Gönder', NOW()),
('tr', 'register.freeTrialFirst', 'İlk 7 gün ücretsiz', NOW()),
('tr', 'register.trialBadge', 'Deneme', NOW()),
('tr', 'register.dueToday', 'Bugün ödenecek', NOW()),
('tr', 'register.cardNumberLabel', 'Kart Numarası', NOW()),
('tr', 'register.cardExpiryLabel', 'Son Kullanma', NOW()),
('tr', 'register.cardCvcLabel', 'CVC', NOW()),
('tr', 'register.backBtn', 'Geri', NOW()),
('tr', 'register.processing', 'İşleniyor...', NOW()),
('tr', 'register.securePayment', 'Stripe güvenli ödeme ile korunmaktadır', NOW()),
('tr', 'register.confirmPayment', 'Ödemeyi Onayla — €0.00', NOW()),
('tr', 'register.welcomeTitle', 'Hoş Geldiniz!', NOW()),
('tr', 'register.welcomeMessage', 'Hesabınız ve aboneliğiniz aktif edildi.', NOW()),
('tr', 'register.redirecting', 'Yönlendiriliyorsunuz...', NOW()),
('tr', 'register.planTemel', 'Temel', NOW()),
('tr', 'register.planPremium', 'Premium', NOW()),
('tr', 'register.emailNotReceived', 'Kod gelmedi mi? {countdown}s sonra tekrar gönderin', NOW()),
('tr', 'register.backToEmail', '← E-posta Adımına Dön', NOW()),
('tr', 'register.monthSuffix', '/ay', NOW()),
('tr', 'dashboard.greeting', 'Merhaba {name}', NOW()),
('tr', 'dashboard.defaultPlan', 'Temel Plan', NOW()),
('tr', 'dashboard.planActive', 'Aktif', NOW()),
('tr', 'dashboard.chiosBoxId', 'ChiosBox ID:', NOW()),
('tr', 'dashboard.addressCopied', 'Kopyalandı!', NOW()),
('tr', 'dashboard.copyAddress', 'Adresimi Kopyala', NOW()),
('tr', 'dashboard.payInvoice', 'Ödeme Yap', NOW()),
('tr', 'dashboard.activePackages', 'Aktif Paketler', NOW()),
('tr', 'dashboard.viewAll', 'Tümünü Gör →', NOW()),
('tr', 'dashboard.noPackagesYet', 'Henüz paket bildirmediniz', NOW()),
('tr', 'dashboard.reportFirstPackage', 'İlk paketinizi bildirin →', NOW()),
('tr', 'dashboard.storagePeriod', 'Depolama Süresi', NOW()),
('tr', 'dashboard.freeStorage', 'Ücretsiz depolama', NOW()),
('tr', 'dashboard.storageExpiring', 'Süre doluyor!', NOW()),
('tr', 'dashboard.inWarehouseDesc', 'Depoda bekleyen', NOW()),
('tr', 'dashboard.inTransit', 'Yolda olan', NOW()),
('tr', 'dashboard.reportPackage', 'Paket Bildir', NOW()),
('tr', 'dashboard.consolidateAction', 'Birleştir', NOW()),
('tr', 'dashboard.settings', 'Ayarlar', NOW()),
('tr', 'dashboard.pendingInvoiceCount', '{count} bekleyen fatura', NOW()),
('tr', 'dashboard.pendingTotal', 'Toplam: €{amount}', NOW()),
('tr', 'dashboard.status.depoda', 'Depoda', NOW()),
('tr', 'dashboard.status.yolda', 'Yolda', NOW()),
('tr', 'dashboard.status.bekleniyor', 'Ödeme Bekleniyor', NOW()),
('tr', 'dashboard.status.teslim_edildi', 'Teslim Edildi', NOW()),
('tr', 'packages.status.depoda', 'Depoda', NOW()),
('tr', 'packages.status.yolda', 'Yolda', NOW()),
('tr', 'packages.status.bekleniyor', 'Ödeme Bekleniyor', NOW()),
('tr', 'packages.status.birlestirildi', 'Birleştirildi', NOW()),
('tr', 'packages.status.teslim_edildi', 'Teslim Edildi', NOW()),
('tr', 'packages.stepper.reported', 'Bildirildi', NOW()),
('tr', 'packages.stepper.inWarehouse', 'Depoda', NOW()),
('tr', 'packages.stepper.consolidated', 'Birleştirildi', NOW()),
('tr', 'packages.stepper.delivered', 'Teslim Edildi', NOW()),
('tr', 'packages.detail.warehouse', 'Depo', NOW()),
('tr', 'packages.detail.masterBox', 'Master Kutu', NOW()),
('tr', 'packages.detail.warehouseArrival', 'Depo Varış', NOW()),
('tr', 'packages.detail.freeDaysLeft', 'Kalan Ücretsiz', NOW()),
('tr', 'packages.detail.chat', 'Destek', NOW()),
('tr', 'packages.detail.messagePlaceholder', 'Mesajınızı yazın...', NOW()),
('tr', 'packages.searchPlaceholder2', 'Takip no, içerik veya kargo ile ara...', NOW()),
('tr', 'packages.filter.all', 'Tümü', NOW()),
('tr', 'packages.filter.depoda', 'Depoda', NOW()),
('tr', 'packages.filter.yolda', 'Yolda', NOW()),
('tr', 'packages.filter.bekleniyor', 'Ödeme Bekleniyor', NOW()),
('tr', 'packages.filter.birlestirildi', 'Birleştirildi', NOW()),
('tr', 'packages.filter.teslim_edildi', 'Teslim Edildi', NOW()),
('tr', 'packages.noSearchResults', 'Aramanıza uygun paket bulunamadı', NOW()),
('tr', 'packages.noCategoryPackages', 'Bu kategoride paket bulunmuyor', NOW()),
('tr', 'checkout.error.loadFailed', 'Fatura yüklenemedi', NOW()),
('tr', 'checkout.error.generic', 'Bir hata oluştu', NOW()),
('tr', 'checkout.error.tryLater', 'Lütfen daha sonra tekrar deneyin', NOW()),
('tr', 'checkout.loading', 'Faturalar yükleniyor...', NOW()),
('tr', 'checkout.empty.title', 'Bekleyen Fatura Yok', NOW()),