('en', 'pricing.storageDays', 'Storage Duration (Days)', NOW()),
('en', 'pricing.storage1', '1 day', NOW()),
('en', 'pricing.storage30', '30 days', NOW()),
('en', 'pricing.freeStorage', 'First 14 days free storage', NOW()),
('en', 'pricing.acceptFeeInfo', 'Accept fee per package €4', NOW()),
('en', 'pricing.monthlyCost', 'Estimated Monthly Cost', NOW()),
('en', 'pricing.acceptFee', 'Accept Fee', NOW()),
('en', 'pricing.consolidationFee', 'Consolidation Fee', NOW()),
('en', 'pricing.demurrageFee', 'Late Fee', NOW()),
('en', 'pricing.total', 'Total', NOW()),
('en', 'pricing.savings', 'You can save ~€{amount} by consolidating!', NOW()),
('en', 'pricing.planTitle', 'Choose the Plan That Suits You', NOW()),
('en', 'pricing.planDesc', 'Door-to-door shipping privilege from Turkey to Europe, Europe to Turkey', NOW()),
('en', 'pricing.basic.name', 'Basic', NOW()),
('en', 'pricing.basic.price', '€9.99', NOW()),
('en', 'pricing.basic.pricePeriod', '/month', NOW()),
('en', 'pricing.basic.subtitle', 'Simple address, simple delivery', NOW()),
('en', 'pricing.basic.f1', 'ChiosBox EU address', NOW()),
('en', 'pricing.basic.f2', '14 days free storage', NOW()),
('en', 'pricing.basic.f3', 'Panel access', NOW()),
('en', 'pricing.basic.f4', 'Email notifications', NOW()),
('en', 'pricing.basic.cta', 'Choose Basic Plan', NOW()),
('en', 'pricing.premium.badge', 'Most Popular', NOW()),
('en', 'pricing.premium.name', 'Premium', NOW()),
('en', 'pricing.premium.subtitle', 'Full control, maximum savings', NOW()),
('en', 'pricing.premium.f1', 'Everything in Basic plan', NOW()),
('en', 'pricing.premium.f2', '21 days free storage', NOW()),
('en', 'pricing.premium.f3', 'Free consolidation', NOW()),
('en', 'pricing.premium.f4', 'Turkey delivery tracking', NOW()),
('en', 'pricing.premium.f5', 'Dedicated support line', NOW()),
('en', 'pricing.premium.cta', 'Choose Premium Plan', NOW()),
('en', 'pricing.month', '/month', NOW()),
('en', 'pricing.mostPopular', 'Most Popular', NOW()),
('en', 'pricing.fee.accept', 'Accept Fee', NOW()),
('en', 'pricing.fee.storage14', '14 days free storage', NOW()),
('en', 'pricing.fee.acceptInfo', 'Accept fee per package €4', NOW()),
('en', 'pricing.fee.acceptUnit', '× €{fee}', NOW()),
('en', 'pricing.demurrageFeeLabel', '{days} days × €{fee}', NOW()),
('en', 'trust.tag', 'Trustworthy & Transparent', NOW()),
('en', 'trust.title', 'Trust Us', NOW()),
('en', 'trust.description', 'Thousands of users shop safely from Turkey to Europe with ChiosBox.', NOW()),
('en', 'trust.stat1.label', 'Active Users', NOW()),
('en', 'trust.stat2.label', 'Packages Delivered', NOW()),
('en', 'trust.stat3.label', 'Satisfaction Rate', NOW()),
('en', 'trust.stat4.label', 'Average Delivery', NOW()),
('en', 'trust.stat4.suffix', 'days', NOW()),
('en', 'trust.badge1.title', 'Greek IKE Registered', NOW()),
('en', 'trust.badge1.desc', 'Officially registered company', NOW()),
('en', 'trust.badge2.title', 'SSL 256-bit Encryption', NOW()),
('en', 'trust.badge2.desc', 'Your data is safe', NOW()),
('en', 'trust.badge3.title', 'Stripe Payment Infrastructure', NOW()),
('en', 'trust.badge3.desc', 'Secure online payment', NOW()),
('en', 'trust.badge4.title', 'EU Compliant', NOW()),
('en', 'trust.badge4.desc', 'Compliant with European Union regulations', NOW()),
('en', 'trust.testimonial1.text', 'I now manage everything I buy from Turkey through ChiosBox. Thanks to consolidation, my shipping costs dropped by half.', NOW()),
('en', 'trust.testimonial2.text', 'The panel is very easy to use. I see photos of my packages and know when they''ll arrive. Great service!', NOW()),
('en', 'trust.testimonial3.text', 'Picking up with QR code is so practical. I went to the office, showed the code, got my package in 2 minutes. Highly recommend!', NOW()),
('en', 'finalCta.tag', 'Get Started Now', NOW()),
('en', 'finalCta.title', 'Get Started Now', NOW()),
('en', 'finalCta.title1', 'Your European Delivery Address', NOW()),
('en', 'finalCta.title2', 'Get Now', NOW()),
('en', 'finalCta.description', 'Starting from €9.99/month, let us deliver your purchases from Turkey to the EU seamlessly via Chios.', NOW()),
('en', 'finalCta.cta', 'Start Now', NOW()),
('en', 'finalCta.cta2', '7-day free trial. No credit card required.', NOW()),
('en', 'finalCta.trust1', 'Instant ChiosBox ID', NOW()),
('en', 'finalCta.trust2', 'Door-to-door delivery', NOW()),
('en', 'finalCta.trust3', 'Secure payment', NOW()),
('en', 'pkgReq.tag', 'Quick Application', NOW()),
('en', 'pkgReq.title', 'Create Package Request', NOW()),
('en', 'pkgReq.description', 'Notify us about your package from Turkey, let us receive it safely at our warehouse.', NOW()),
('en', 'pkgReq.ready', 'Ready in 3 Steps', NOW()),
('en', 'pkgReq.readyDesc', 'Enter your information, let us track your package', NOW()),
('en', 'pkgReq.success.title', 'Your Request Has Been Received!', NOW()),
('en', 'pkgReq.success.desc', 'Your package notification has been saved. We will notify you when it arrives at our warehouse from Turkey.', NOW()),
('en', 'pkgReq.newRequest', 'New Request', NOW()),
('en', 'pkgReq.registerTrack', 'Register & Track', NOW()),
('en', 'pkgReq.step1.title', 'Personal Information', NOW()),
('en', 'pkgReq.fullName', 'Full Name *', NOW()),
('en', 'pkgReq.fullNamePlaceholder', 'Your Full Name', NOW()),
('en', 'pkgReq.email', 'Email *', NOW()),
('en', 'pkgReq.phone', 'Phone', NOW()),
('en', 'pkgReq.step2.title', 'Shipping Information', NOW()),
('en', 'pkgReq.carrier', 'Carrier *', NOW()),
('en', 'pkgReq.trackingNo', 'Tracking Number *', NOW()),
('en', 'pkgReq.trackingPlaceholder', 'Your tracking number', NOW()),
('en', 'pkgReq.content', 'Package Contents *', NOW()),
('en', 'pkgReq.contentPlaceholder', 'What''s in your package?', NOW()),
('en', 'pkgReq.estimatedValue', 'Estimated Value (€)', NOW()),
('en', 'pkgReq.step3.title', 'Summary & Approval', NOW()),
('en', 'pkgReq.summaryName', 'Full Name', NOW()),
('en', 'pkgReq.summaryEmail', 'Email', NOW()),
('en', 'pkgReq.summaryPhone', 'Phone', NOW()),
('en', 'pkgReq.summaryCarrier', 'Shipping', NOW()),
('en', 'pkgReq.summaryTracking', 'Tracking No', NOW()),
('en', 'pkgReq.summaryContent', 'Contents', NOW()),
('en', 'pkgReq.summaryValue', 'Estimated Value', NOW()),
('en', 'pkgReq.notes', 'Notes', NOW()),
('en', 'pkgReq.notesPlaceholder', 'Do you have a note to add?', NOW()),
('en', 'pkgReq.info', 'Your package notification will be processed at our warehouse. By registering, you can track your packages from the panel and benefit from consolidation and delivery options.', NOW()),
('en', 'pkgReq.back', 'Back', NOW()),
('en', 'pkgReq.continue', 'Continue', NOW()),
('en', 'pkgReq.submit', 'Submit Request', NOW()),
('en', 'pkgReq.carrier.yurtici', 'Yurtiçi Kargo', NOW()),
('en', 'pkgReq.carrier.aras', 'Aras Kargo', NOW()),
('en', 'pkgReq.carrier.mng', 'MNG Kargo', NOW()),
('en', 'pkgReq.carrier.ptt', 'PTT Kargo', NOW()),
('en', 'pkgReq.carrier.surat', 'Sürat Kargo', NOW()),
('en', 'pkgReq.carrier.diger', 'Other', NOW()),
('en', 'dashboard.title', 'Admin Dashboard', NOW()),
('en', 'dashboard.welcome', 'Welcome, {name}', NOW()),
('en', 'dashboard.totalPackages', 'Total Packages', NOW()),
('en', 'dashboard.inWarehouse', 'In Warehouse', NOW()),
('en', 'dashboard.last7Days', 'Last 7 Days', NOW()),
('en', 'dashboard.newPackages', 'new packages', NOW()),
('en', 'dashboard.weeklyRevenue', 'Weekly Revenue', NOW()),
('en', 'dashboard.statusDistribution', 'Status Distribution', NOW()),
('en', 'dashboard.recentActivity', 'Recent Activity', NOW()),
('en', 'dashboard.unknown', 'Unknown', NOW()),
('en', 'dashboard.demurrageAlert', 'Delay Alert', NOW()),
('en', 'dashboard.demurrageDesc', '{count} packages exceeded 14 days', NOW()),
('en', 'dashboard.pendingInvoices', 'Pending Invoices', NOW()),
('en', 'dashboard.pendingInvoiceDesc', '{count} invoices awaiting payment', NOW()),
('en', 'dashboard.shelfUsage', 'Shelf Usage', NOW()),
('en', 'dashboard.quickActions', 'Quick Actions', NOW()),
('en', 'status.beklemede', 'Pending', NOW()),
('en', 'status.yolda', 'In Transit', NOW()),
('en', 'status.depoda', 'In Warehouse', NOW()),
('en', 'status.birlestirildi', 'Consolidated', NOW()),
('en', 'status.teslimEdildi', 'Delivered', NOW()),
('en', 'action.kabul', 'Intake', NOW()),
('en', 'actions.delivery', 'Delivery', NOW()),
('en', 'action.delay', 'Delay', NOW()),
('en', 'action.packages', 'Packages', NOW()),
('en', 'action.faturalar', 'Invoices', NOW()),
('en', 'action.musteriler', 'Customers', NOW()),
('en', 'packages.title', 'Packages', NOW()),
('en', 'packages.count', '{total} packages', NOW()),
('en', 'packages.searchPlaceholder', 'Search by tracking no...', NOW()),
('en', 'packages.allStatuses', 'All Statuses', NOW()),
('en', 'packages.notFound', 'Package not found', NOW()),
('en', 'packages.daysAgo', '{n} days', NOW()),
('en', 'packages.previous', 'Previous', NOW()),
('en', 'packages.next', 'Next', NOW()),
('en', 'packages.deleteConfirm', 'Are you sure you want to delete this package?', NOW()),
('en', 'packages.detail.customer', 'Customer', NOW()),
('en', 'packages.detail.carrier', 'Carrier', NOW()),
('en', 'packages.detail.trackingNo', 'Tracking No', NOW()),
('en', 'packages.detail.shelf', 'Shelf', NOW()),
('en', 'packages.detail.arrival', 'Arrival', NOW()),
('en', 'packages.detail.notification', 'Notification', NOW()),
('en', 'packages.detail.inWarehouse', 'In Warehouse', NOW()),
('en', 'packages.detail.weight', 'Weight', NOW()),
('en', 'packages.detail.dimensions', 'Dimensions', NOW()),
('en', 'packages.detail.demurrageFee', 'Delay Fee', NOW()),
('en', 'packages.detail.notes', 'Note', NOW()),
('en', 'packages.detail.updateStatus', 'Update Status', NOW()),
('en', 'packages.detail.delete', 'Delete Package', NOW()),
('en', 'packages.detail.cancel', 'Cancel', NOW()),
('en', 'packages.detail.deleting', 'Deleting...', NOW()),
('en', 'packages.detail.confirmDelete', 'Yes, Delete', NOW()),
('en', 'customers.title', 'Customers', NOW()),
('en', 'customers.count', '{total} customers', NOW()),
('en', 'customers.searchPlaceholder', 'Search by name, email or ChiosBox ID...', NOW()),
('en', 'customers.notFound', 'Customer not found', NOW()),
('en', 'customers.packageCount', '{n} packages', NOW()),
('en', 'customers.pending', 'pending', NOW()),
('en', 'customers.previous', 'Previous', NOW()),
('en', 'customers.next', 'Next', NOW()),
('en', 'invoices.title', 'Invoices', NOW()),
('en', 'invoices.count', '{total} invoices', NOW()),
('en', 'invoices.newInvoice', '+ New Invoice', NOW()),
('en', 'invoices.all', 'All', NOW()),
('en', 'invoices.pending', 'Pending', NOW()),
('en', 'invoices.paid', 'Paid', NOW()),
('en', 'invoices.cancelled', 'Cancelled', NOW()),
('en', 'invoices.notFound', 'Invoice not found', NOW()),
('en', 'invoices.acceptFee', 'Accept: €{amount}', NOW()),
('en', 'invoices.consolidationFee', 'Consolidation: €{amount}', NOW()),
('en', 'invoices.demurrageFee', 'Delay: €{amount}', NOW()),
('en', 'invoices.packageCount', '{n} packages', NOW()),
('en', 'invoices.previous', 'Previous', NOW()),
('en', 'invoices.next', 'Next', NOW()),
('en', 'invoices.createModal.title', 'New Invoice', NOW()),
('en', 'invoices.createModal.customer', 'Customer', NOW()),
('en', 'invoices.createModal.selectCustomer', 'Select a customer', NOW()),
('en', 'invoices.createModal.packetsToBill', 'Packets to Bill', NOW()),
('en', 'invoices.createModal.noUnbilled', 'No unbilled packages found', NOW()),
('en', 'invoices.createModal.consolidationFee', 'Consolidation Fee', NOW()),
('en', 'invoices.createModal.acceptFee', 'Accept Fee ({count} packages × €{fee})', NOW()),
('en', 'invoices.createModal.demurrageFee', 'Delay Fee', NOW()),
('en', 'invoices.createModal.consolidationLine', 'Consolidation Fee', NOW()),
('en', 'invoices.createModal.total', 'Total', NOW()),
('en', 'invoices.createModal.creating', 'Creating...', NOW()),
('en', 'invoices.createModal.createButton', 'Create Invoice (€{amount})', NOW()),
('en', 'invoices.createModal.selectCustomerError', 'Select a customer', NOW()),
('en', 'invoices.createModal.selectPackageError', 'Select at least one package', NOW()),
('en', 'invoices.createModal.createError', 'Invoice could not be created', NOW()),
('en', 'invoices.detail.customer', 'Customer', NOW()),
('en', 'invoices.detail.date', 'Date', NOW()),
('en', 'invoices.detail.paymentDate', 'Payment Date', NOW()),
('en', 'invoices.detail.acceptFee', 'Accept Fee', NOW()),
('en', 'invoices.detail.consolidationFee', 'Consolidation Fee', NOW()),
('en', 'invoices.detail.demurrageFee', 'Delay Fee', NOW()),
('en', 'invoices.detail.total', 'Total', NOW()),
('en', 'invoices.detail.packets', 'Packages ({count})', NOW()),
('en', 'invoices.detail.markPaid', 'Mark as Paid', NOW()),
('en', 'invoices.detail.cancel', 'Cancel', NOW()),
('en', 'invoices.detail.undoCancel', 'Undo Cancel', NOW()),
('en', 'invoices.detail.undoPayment', 'Undo Payment', NOW()),
('en', 'intake.title', 'Package Intake', NOW()),
('en', 'intake.newIntake', 'New Intake', NOW()),
('en', 'intake.error.search', 'Search failed', NOW()),
('en', 'intake.error.searchPaket', 'Error while searching for package', NOW()),
('en', 'intake.error.saveFailed', 'Save failed', NOW()),
('en', 'intake.error.generic', 'An error occurred', NOW()),
('en', 'intake.barcodeInstruction', 'Show barcode to camera or enter manually', NOW()),
('en', 'intake.barcodeLabel', 'Barcode / Tracking No', NOW()),
('en', 'intake.barcodePlaceholder', 'Scan or type the barcode', NOW()),
('en', 'intake.notFound', 'No package found for this tracking number', NOW()),
('en', 'intake.customer', 'Customer', NOW()),
('en', 'intake.content', 'Content', NOW()),
('en', 'intake.notes', 'Note: {text}', NOW()),
('en', 'intake.shelfAssignment', 'Shelf Assignment', NOW()),
('en', 'intake.saving', 'Saving...', NOW()),
('en', 'intake.save', 'SAVE', NOW()),
('en', 'intake.saved', 'Saved!', NOW()),
('en', 'intake.shelfPrefix', 'Shelf: {shelf}', NOW()),
('en', 'intake.unknown', 'Unknown', NOW()),
('en', 'pickup.title', 'Delivery', NOW()),
('en', 'pickup.newDelivery', 'New Delivery', NOW()),
('en', 'pickup.error.search', 'Search failed', NOW()),
('en', 'pickup.error.searchPaket', 'Error while searching for package', NOW()),
('en', 'pickup.error.codeFailed', 'Code could not be generated', NOW()),
('en', 'pickup.error.generic', 'An error occurred', NOW()),
('en', 'pickup.error.deliveryFailed', 'Delivery failed', NOW()),
('en', 'pickup.inputPlaceholder', 'Enter tracking no or CBX ID', NOW()),
('en', 'pickup.notFound', 'No package found for this code', NOW()),
('en', 'pickup.toDeliver', 'To Be Delivered', NOW()),
('en', 'pickup.verificationTitle', 'Verification Code', NOW()),
('en', 'pickup.verificationDesc', 'Send one-time code to customer', NOW()),
('en', 'pickup.sending', 'Sending...', NOW()),
('en', 'pickup.sendCode', 'Send Code', NOW()),
('en', 'pickup.mockCodeLabel', 'Verification Code (Mock)', NOW()),
('en', 'pickup.mockCodeNote', 'Will be sent to customer via real SMS', NOW()),
('en', 'pickup.customerCode', 'Customer''s Code', NOW()),
('en', 'pickup.codePlaceholder', '6-digit code', NOW()),
('en', 'pickup.delivering', 'Delivering...', NOW()),
('en', 'pickup.deliver', 'DELIVER', NOW()),
('en', 'pickup.delivered', 'Delivered!', NOW()),
('en', 'demurrage.title', 'Delay Radar', NOW()),
('en', 'demurrage.subtitle', 'Track packages that exceed storage time', NOW()),
('en', 'demurrage.normal', 'Normal (≤14 days)', NOW()),
('en', 'demurrage.delay', 'Delay (15-29 days)', NOW()),
('en', 'demurrage.abandonedZone', 'Abandoned (30+ days)', NOW()),
('en', 'demurrage.abandoned', 'Abandoned', NOW()),
('en', 'demurrage.unknown', 'Unknown', NOW()),
('en', 'demurrage.shelfPrefix', 'Shelf {shelf}', NOW()),
('en', 'demurrage.arrival', 'Arrival: {date}', NOW()),
('en', 'demurrage.daysLabel', '{n} days', NOW()),
('en', 'demurrage.demurrageFee', 'Delay Fee', NOW()),
('en', 'demurrage.error.applyFailed', 'Delay fee could not be applied', NOW()),
('en', 'demurrage.cancel', 'Cancel', NOW()),
('en', 'demurrage.applyAmount', 'Apply €{amount}', NOW()),
('en', 'demurrage.invoiceCreated', 'Invoice Created!', NOW()),
('en', 'demurrage.applyFeeButton', 'Apply Delay Fee (€{amount})', NOW()),
('en', 'demurrage.confirmDelete', 'Yes, Delete', NOW()),
('en', 'demurrage.discard', 'Dispose', NOW()),
('en', 'demurrage.allClear', 'All packages cleared', NOW()),
('en', 'demurrage.detail.customer', 'Customer', NOW()),
('en', 'demurrage.detail.content', 'Content', NOW()),
('en', 'demurrage.detail.shelf', 'Shelf', NOW()),
('en', 'demurrage.detail.arrivalDate', 'Arrival Date', NOW()),
('en', 'demurrage.detail.inWarehouse', 'In Warehouse', NOW()),
('en', 'demurrage.detail.freeDaysLeft', 'Remaining Free Days', NOW()),
('en', 'demurrage.detail.demurrageFee', 'Delay Fee', NOW()),
('en', 'demurrage.detail.appliedFee', 'Applied Fee', NOW()),
('en', 'demurrage.detail.weight', 'Weight', NOW()),
('en', 'demurrage.detail.dimensions', 'Dimensions', NOW()),
('en', 'demurrage.detail.notes', 'Note', NOW()),
('en', 'users.title', 'User Management', NOW()),
('en', 'users.subtitle', 'Role and permission assignments', NOW()),
('en', 'users.searchPlaceholder', 'Search by name, email or ChiosBox ID...', NOW()),
('en', 'users.error.updateFailed', 'Update failed', NOW()),
('en', 'users.editModal.title', 'Edit User', NOW()),
('en', 'users.editModal.adminAccess', 'Admin Permission', NOW()),
('en', 'users.editModal.adminAccessDesc', 'Access to admin panel', NOW()),
('en', 'users.editModal.permissions', 'Permissions', NOW()),
('en', 'users.editModal.superAdmin', 'Super admin — has all permissions, cannot be edited.', NOW()),
('en', 'users.editModal.saving', 'Saving...', NOW()),
('en', 'users.editModal.save', 'Save', NOW()),
('en', 'perm.intake', 'Intake (Package Intake)', NOW()),
('en', 'perm.pickup', 'Delivery', NOW()),
('en', 'perm.demurrage', 'Delay Management', NOW()),
('en', 'perm.packages', 'Package List', NOW()),
('en', 'perm.invoices', 'Invoice Management', NOW()),
('en', 'perm.customers', 'Customer Management', NOW()),
('en', 'perm.settings', 'System Settings', NOW()),
('en', 'error.root.title', 'Something went wrong', NOW()),
('en', 'error.root.description', 'An unexpected error occurred. Please try again.', NOW()),
('en', 'error.root.retry', 'Try Again', NOW()),
('en', 'notFound.title', 'Page Not Found', NOW()),
('en', 'notFound.description', 'The page you are looking for may not exist or may have been moved.', NOW()),
('en', 'notFound.homeLink', 'Go to Home Page', NOW()),
('en', 'error.dashboard.title', 'An error occurred', NOW()),
('en', 'error.dashboard.description', 'A problem occurred while loading the page.', NOW()),
('en', 'error.dashboard.retry', 'Try Again', NOW()),
('en', 'error.admin.title', 'Admin Dashboard Error', NOW()),
('en', 'error.admin.description', 'A problem occurred while loading the page.', NOW()),
('en', 'error.admin.retry', 'Try Again', NOW()),
('en', 'loading.text', 'Loading...', NOW()),
('en', 'loading.adminText', 'Loading...', NOW()),
('en', 'login.email', 'Email', NOW()),
('en', 'login.password', 'Password', NOW()),
('en', 'login.rememberMe', 'Remember Me', NOW()),
('en', 'login.forgotPassword', 'Forgot Password', NOW()),
('en', 'login.submit', 'Log In', NOW()),
('en', 'login.submitting', 'Logging in...', NOW()),
('en', 'login.noAccount', 'Don''t have an account?', NOW()),
('en', 'login.registerLink', 'Sign Up', NOW()),
('en', 'register.steps.info', 'Details', NOW()),
('en', 'register.steps.emailVerify', 'Email', NOW()),
('en', 'register.steps.phoneVerify', 'Phone', NOW()),
('en', 'register.steps.payment', 'Payment', NOW()),
('en', 'register.nameLabel', 'Full Name', NOW()),
('en', 'register.namePlaceholder', 'Your Full Name', NOW()),
('en', 'register.emailLabel', 'Email', NOW()),
('en', 'register.emailPlaceholder', 'example@email.com', NOW()),
('en', 'register.passwordLabel', 'Password', NOW()),
('en', 'register.passwordConfirmLabel', 'Confirm Password', NOW()),
('en', 'register.passwordMismatch', 'Passwords do not match', NOW()),
('en', 'register.planLabel', 'Choose a Plan', NOW()),
('en', 'register.tosAgreement', 'I have read and accept the terms of use and privacy policy.', NOW()),
('en', 'register.tosRequired', 'You must accept the terms of use', NOW()),
('en', 'register.continue', 'Continue', NOW()),
('en', 'register.loginLink', 'Log In', NOW()),
('en', 'register.emailVerifyTitle', 'Verify Your Email', NOW()),
('en', 'register.emailVerifyDescription', 'Enter the 6-digit code sent to your email.', NOW()),
('en', 'register.verifying', 'Verifying...', NOW()),
('en', 'register.resendCode', 'Resend Code', NOW()),
('en', 'register.smsNotReceived', 'Didn''t receive SMS? Resend in {countdown}s', NOW()),
('en', 'register.backToInfo', 'Back to Details', NOW()),
('en', 'register.phoneVerifyTitle', 'Verify Your Phone', NOW()),
('en', 'register.phoneVerifyDescription', 'Enter the 6-digit code sent to your phone number.', NOW()),
('en', 'register.phoneTitle', 'Your Phone Number', NOW()),
('en', 'register.phoneDescription', 'Enter your phone number for delivery notifications.', NOW()),
('en', 'register.phoneLabel', 'Phone Number', NOW()),
('en', 'register.sendSmsCode', 'Send SMS Code', NOW()),
('en', 'register.freeTrialFirst', 'First 7 days free', NOW()),
('en', 'register.trialBadge', 'Trial', NOW()),
('en', 'register.dueToday', 'Due Today', NOW()),
('en', 'register.cardNumberLabel', 'Card Number', NOW()),
('en', 'register.cardExpiryLabel', 'Expiry Date', NOW()),
('en', 'register.cardCvcLabel', 'CVC', NOW()),
('en', 'register.backBtn', 'Back', NOW()),
('en', 'register.processing', 'Processing...', NOW()),
('en', 'register.securePayment', 'Secured by Stripe safe payment', NOW()),
('en', 'register.confirmPayment', 'Confirm Payment — €0.00', NOW()),
('en', 'register.welcomeTitle', 'Welcome!', NOW()),
('en', 'register.welcomeMessage', 'Your account and subscription have been activated.', NOW()),
('en', 'register.redirecting', 'Redirecting...', NOW()),
('en', 'register.planTemel', 'Basic', NOW()),
('en', 'register.planPremium', 'Premium', NOW()),
('en', 'register.emailNotReceived', 'Didn''t receive code? Resend in {countdown}s', NOW()),
('en', 'register.backToEmail', '← Back to Email Step', NOW()),
('en', 'register.monthSuffix', '/mo', NOW()),
('en', 'dashboard.greeting', 'Hello {name}', NOW()),
('en', 'dashboard.defaultPlan', 'Basic Plan', NOW()),
('en', 'dashboard.planActive', 'Active', NOW()),
('en', 'dashboard.chiosBoxId', 'ChiosBox ID:', NOW()),
('en', 'dashboard.addressCopied', 'Copied!', NOW()),
('en', 'dashboard.copyAddress', 'Copy My Address', NOW()),
('en', 'dashboard.payInvoice', 'Pay Now', NOW()),
('en', 'dashboard.activePackages', 'Active Packages', NOW()),
('en', 'dashboard.viewAll', 'View All →', NOW()),
('en', 'dashboard.noPackagesYet', 'You haven''t reported any packages yet', NOW()),
('en', 'dashboard.reportFirstPackage', 'Report your first package →', NOW()),
('en', 'dashboard.storagePeriod', 'Storage Period', NOW()),
('en', 'dashboard.freeStorage', 'Free storage', NOW()),
('en', 'dashboard.storageExpiring', 'Expiring soon!', NOW()),
('en', 'dashboard.inWarehouseDesc', 'In warehouse', NOW()),
('en', 'dashboard.inTransit', 'In transit', NOW()),
('en', 'dashboard.reportPackage', 'Report Package', NOW()),
('en', 'dashboard.consolidateAction', 'Consolidate', NOW()),
('en', 'dashboard.settings', 'Settings', NOW()),
('en', 'dashboard.pendingInvoiceCount', '{count} pending invoice(s)', NOW()),
('en', 'dashboard.pendingTotal', 'Total: €{amount}', NOW()),
('en', 'dashboard.status.depoda', 'In Warehouse', NOW()),
('en', 'dashboard.status.yolda', 'In Transit', NOW()),
('en', 'dashboard.status.bekleniyor', 'Awaiting Payment', NOW()),
('en', 'dashboard.status.teslim_edildi', 'Delivered', NOW()),
('en', 'packages.status.depoda', 'In Warehouse', NOW()),
('en', 'packages.status.yolda', 'In Transit', NOW()),
('en', 'packages.status.bekleniyor', 'Awaiting Payment', NOW()),
('en', 'packages.status.birlestirildi', 'Consolidated', NOW()),
('en', 'packages.status.teslim_edildi', 'Delivered', NOW()),
('en', 'packages.stepper.reported', 'Reported', NOW()),
('en', 'packages.stepper.inWarehouse', 'In Warehouse', NOW()),
('en', 'packages.stepper.consolidated', 'Consolidated', NOW()),
('en', 'packages.stepper.delivered', 'Delivered', NOW()),
('en', 'packages.detail.warehouse', 'Warehouse', NOW()),
('en', 'packages.detail.masterBox', 'Master Box', NOW()),
('en', 'packages.detail.warehouseArrival', 'Warehouse Arrival', NOW()),
('en', 'packages.detail.freeDaysLeft', 'Free Days Left', NOW()),
('en', 'packages.detail.chat', 'Support', NOW()),
('en', 'packages.detail.messagePlaceholder', 'Type your message...', NOW()),
('en', 'packages.searchPlaceholder2', 'Search by tracking no, content, or carrier...', NOW()),
('en', 'packages.filter.all', 'All', NOW()),
('en', 'packages.filter.depoda', 'In Warehouse', NOW()),
('en', 'packages.filter.yolda', 'In Transit', NOW()),
('en', 'packages.filter.bekleniyor', 'Awaiting Payment', NOW()),
('en', 'packages.filter.birlestirildi', 'Consolidated', NOW()),
('en', 'packages.filter.teslim_edildi', 'Delivered', NOW()),
('en', 'packages.noSearchResults', 'No packages match your search', NOW()),
('en', 'packages.noCategoryPackages', 'No packages in this category', NOW()),
('en', 'checkout.error.loadFailed', 'Failed to load invoice', NOW()),
('en', 'checkout.error.generic', 'An error occurred', NOW()),
('en', 'checkout.error.tryLater', 'Please try again later', NOW()),
('en', 'checkout.loading', 'Loading invoices...', NOW()),
('en', 'checkout.empty.title', 'No Pending Invoices', NOW()),
('en', 'checkout.empty.description', 'You have no invoices to pay right now. An invoice will be created when your packages arrive at the warehouse.', NOW()),
('en', 'checkout.summary.title', 'Payment Summary', NOW()),
('en', 'checkout.summary.pendingCount', '{count} pending invoice(s)', NOW()),
('en', 'checkout.summary.selectedCount', '{count} invoice(s) selected', NOW()),
('en', 'checkout.payAll', 'Pay All — €{amount}', NOW()),
('en', 'checkout.paySelected', 'Pay Selected — €{amount}', NOW()),
('en', 'checkout.secureNote', 'Secured by Stripe secure payment infrastructure', NOW()),
('en', 'checkout.processing.title', 'Payment Processing...', NOW()),
('en', 'checkout.processing.subtitle', 'Please wait', NOW()),
('en', 'checkout.success.title', 'Payment Successful!', NOW()),
('en', 'checkout.success.subtitle', 'Your delivery QR code is being generated', NOW()),
('en', 'checkout.success.ready', 'Ready for Delivery', NOW()),
('en', 'checkout.fee.accept', 'Accept Fee', NOW()),
('en', 'checkout.fee.consolidation', 'Consolidation Fee', NOW()),
('en', 'checkout.fee.consolidationShort', 'Consolidation', NOW()),
('en', 'checkout.fee.demurrage', 'Demurrage Fee', NOW()),
('en', 'consolidate.title', 'Consolidation', NOW()),
('en', 'consolidate.description', 'Save on shipping costs by consolidating your packages', NOW()),
('en', 'consolidate.error.consolidationFailed', 'Consolidation failed', NOW()),
('en', 'consolidate.error.generic', 'An error occurred', NOW()),
('en', 'consolidate.availablePackages', 'Packages Available for Consolidation', NOW()),
('en', 'consolidate.packageCount', '{count} package(s)', NOW()),
('en', 'consolidate.add', 'Add', NOW()),
('en', 'consolidate.noAvailable', 'All packages added or no packages in warehouse', NOW()),
('en', 'consolidate.masterBox', 'Master Box', NOW()),
('en', 'consolidate.addFromLeft', 'Add packages from the left', NOW()),
('en', 'consolidate.costSummary', 'Cost Summary', NOW()),
('en', 'consolidate.acceptFeeLine', 'Accept Fee ({count} × €{fee})', NOW()),
('en', 'consolidate.consolidationFee', 'Consolidation Fee', NOW()),
('en', 'consolidate.total', 'Total', NOW()),
('en', 'consolidate.savings', 'Estimated Savings: +€{amount}', NOW()),
('en', 'consolidate.submitting', 'Consolidating...', NOW()),
('en', 'consolidate.submit', 'Consolidate', NOW()),
('en', 'profile.title', 'Profile', NOW()),
('en', 'profile.description', 'Manage your account information and delivery address', NOW()),
('en', 'profile.saved', 'Information updated', NOW()),
('en', 'profile.edit', 'Edit', NOW()),
('en', 'profile.nameLabel', 'Full Name', NOW()),
('en', 'profile.nameRequired', 'Full name cannot be empty', NOW()),
('en', 'profile.emailLabel', 'Email', NOW()),
('en', 'profile.phoneLabel', 'Phone', NOW()),
('en', 'profile.chiosBoxId', 'ChiosBox ID', NOW()),
('en', 'profile.cancel', 'Cancel', NOW()),
('en', 'profile.saving', 'Saving...', NOW()),
('en', 'profile.save', 'Save', NOW()),
('en', 'profile.saveFailed', 'Update failed', NOW()),
('en', 'profile.genericError', 'An error occurred', NOW()),
('en', 'profile.addressTitle', 'Your Delivery Address', NOW()),
('en', 'profile.addressCopied', 'Copied!', NOW()),
('en', 'profile.copyAddress', 'Copy Address', NOW()),
('en', 'profile.subscriptionTitle', 'Subscription Information', NOW()),
('en', 'profile.defaultPlan', 'Basic Plan', NOW()),
('en', 'profile.statusActive', 'Active', NOW()),
('en', 'profile.statusInactive', 'Inactive', NOW()),
('en', 'profile.notificationsTitle', 'Notifications', NOW()),
('en', 'profile.notificationsDescription', 'Receive package and invoice notifications instantly', NOW()),
('en', 'profile.notificationsActive', 'Notifications active', NOW()),
('en', 'profile.notificationsDenied', 'You need to enable notification permission from browser settings', NOW()),
('en', 'profile.notificationsEnabling', 'Setting up...', NOW()),
('en', 'profile.notificationsEnable', 'Enable Notifications', NOW()),
('en', 'profile.logout', 'Log Out', NOW()),
('en', 'profile.changePassword', 'Change Password', NOW()),
('en', 'profile.changePasswordDescription', 'You can change your password here for security.', NOW()),
('en', 'profile.currentPassword', 'Current password', NOW()),
('en', 'profile.newPassword', 'New password', NOW()),
('en', 'profile.confirmPassword', 'New password (confirm)', NOW()),