('de', 'sidebar.logout', 'Abmelden', NOW()),
('de', 'profile.addressLabel', 'Adresse', NOW()),
('de', 'profile.addressPlaceholder', 'Adresse eingeben', NOW()),
('de', 'tour.start', 'Tour starten', NOW()),
('de', 'tour.next', 'Weiter', NOW()),
('de', 'tour.back', 'Zurück', NOW()),
('de', 'tour.finish', 'Fertig', NOW()),
('de', 'tour.skip', 'Überspringen', NOW()),
('de', 'tour.close', 'Schließen', NOW()),
('de', 'tour.helpTooltip', 'Tourenführer', NOW()),
('de', 'tour.step.dashboardWelcome.title', 'Willkommen', NOW()),
('de', 'tour.step.dashboardWelcome.content', 'Willkommen bei ChiosBox! Dies ist Ihr Dashboard. Oben sehen Sie Ihre ChiosBox-ID und Lieferadresse. Verwenden Sie ''Adresse kopieren'', um Ihre Adresse für türkische Online-Shops zu kopieren.', NOW()),
('de', 'tour.step.dashboardStats.title', 'Statistik-Karten', NOW()),
('de', 'tour.step.dashboardStats.content', 'Sehen Sie Ihre aktive Paketanzahl, Lager- und Transportpakete, verbleibende kostenlose Lagertage und ausstehende Rechnungen. Jede Karte informiert Sie.', NOW()),
('de', 'tour.step.dashboardPackages.title', 'Aktive Pakete', NOW()),
('de', 'tour.step.dashboardPackages.content', 'Ihre zuletzt hinzugefügten Pakete werden hier mit Statusanzeigen aufgelistet. Wenn Sie noch keine Pakete gemeldet haben, erscheint eine leere Statusmeldung. Klicken Sie auf ''Alle anzeigen''.', NOW()),
('de', 'tour.step.dashboardActions.title', 'Schnellaktionen', NOW()),
('de', 'tour.step.dashboardActions.content', 'Schnellzugriff auf häufige Aktionen. ''Adresse kopieren'' kopiert Ihre ChiosBox-Adresse — verwenden Sie sie als Lieferadresse beim Online-Shopping. ''Jetzt zahlen'' für ausstehende Rechnungen.', NOW()),
('de', 'tour.step.actions.title', 'Paket melden — Bestellprozess', NOW()),
('de', 'tour.step.actions.content', 'Nach Ihrem Online-Einkauf generiert der Verkäufer eine Sendungsnummer, wenn er Ihre Bestellung versendet. Geben Sie diese Nummer hier ein, um das Paket Ihrem ChiosBox-Konto hinzuzufügen. So können wir Sie benachrichtigen, wenn es im Lager eintrifft. Füllen wir das Formular Schritt für Schritt aus!', NOW()),
('de', 'tour.step.tracking.title', 'Sendungsnummer', NOW()),
('de', 'tour.step.tracking.content', 'Geben Sie die Sendungsnummer ein, die Sie vom Verkäufer erhalten haben. Der Frachtdienst wird oft automatisch erkannt. Beispiel: TR-2026-0044.', NOW()),
('de', 'tour.step.carrier.title', 'Versanddienst', NOW()),
('de', 'tour.step.carrier.content', 'Wählen Sie den Versanddienst, der Ihr Paket liefert. Falls nicht automatisch erkannt, wählen Sie aus der Liste oder geben Sie ihn unter ''Andere'' manuell ein.', NOW()),
('de', 'tour.step.packageForm.title', 'Paketdetails', NOW()),
('de', 'tour.step.packageForm.content', 'Geben Sie Ihre Paketdetails ein: Inhaltsbeschreibung (identifiziert den Inhalt), Gewicht (beeinflusst den Preis), Abmessungen (wichtig für die Boxauswahl) und besondere Hinweise. Diese Informationen beschleunigen die Paketbearbeitung.', NOW()),
('de', 'tour.step.submit.title', 'Paket melden', NOW()),
('de', 'tour.step.submit.content', 'Sobald alle Felder ausgefüllt sind, klicken Sie auf diese Schaltfläche, um Ihr Paket bei ChiosBox zu melden. Im Demo-Modus wird das Formular ausgefüllt und das 3. Paket zu Ihrer Liste hinzugefügt.', NOW()),
('de', 'tour.step.packages.title', 'Meine Pakete — Liste', NOW()),
('de', 'tour.step.packages.content', 'Alle Ihre gemeldeten Pakete werden hier aufgelistet. Verwenden Sie Suche und Filter, um Pakete schnell zu finden. Jede Karte zeigt Status, Versanddienst, Sendungsnummer und Inhalt. Sie haben jetzt 3 Demo-Pakete!', NOW()),
('de', 'tour.step.packageCard.title', 'Paketkarte', NOW()),
('de', 'tour.step.packageCard.content', 'Jede Paketkarte zeigt eine Statusanzeige (erwartet, unterwegs, im Lager, geliefert), Versanddienst, Sendungsnummer und Inhaltszusammenfassung. Klicken Sie auf die Karte für Details.', NOW()),
('de', 'tour.step.packageDetail.title', 'Paketdetails', NOW()),
('de', 'tour.step.packageDetail.content', 'Wenn Sie auf ein Paket klicken, öffnet sich das Detail-Modal. Hier sehen Sie das Ankunftsdatum im Lager, die verbleibende kostenlose Lagerzeit, die Regalposition und ein Lagerfoto. Verwenden Sie den Support-Chat, um Fragen zu stellen. Überprüfen Sie Ihre Informationen hier, bevor Sie Zahlungen vornehmen.', NOW()),
('de', 'tour.step.consolidateLeft.title', 'Lagerpakete', NOW()),
('de', 'tour.step.consolidateLeft.content', 'Ihre Lagerpakete werden im linken Panel aufgelistet. Wählen Sie Pakete für die Konsolidierungsbox aus. Kombinieren Sie mehrere Pakete in einer Box und sparen Sie bei internationalen Versandkosten.', NOW()),
('de', 'tour.step.consolidateRight.title', 'Konsolidierungsbox', NOW()),
('de', 'tour.step.consolidateRight.content', 'Ihre ausgewählten Pakete werden in die Master-Box übertragt. Beim Kombinieren wird eine Konsolidierungsgebühr hinzugefügt, aber es ist viel günstiger als einzelne Sendungen. Den Unterschied sehen Sie im Preisvergleich.', NOW()),
('de', 'tour.step.consolidateConfirm.title', 'Konsolidierungsbestätigung', NOW()),
('de', 'tour.step.consolidateConfirm.content', 'Nach der Auswahl Ihrer Pakete klicken Sie auf diese Schaltfläche, um Ihre Konsolidierungsanfrage zu senden. Dieser Schritt ist optional — Sie können Pakete auch einzeln versenden.', NOW()),
('de', 'tour.step.checkout.title', 'Rechnungsprüfung', NOW()),
('de', 'tour.step.checkout.content', 'Überprüfen Sie Ihre Rechnungen vor der Zahlung. Sehen Sie Positionen wie Annahmegebühr, Konsolidierungsgebühr und Lagergebühren mit Paketaufschlüsselung. Prüfen Sie den Gesamtbetrag. Sie können zu Ihren Paketen zurückkehren.', NOW()),
('de', 'tour.step.checkoutPay.title', 'Zahlung & QR-Code', NOW()),
('de', 'tour.step.checkoutPay.content', 'Nach der Zahlungsbestätigung wird Ihr Lieferungs-QR-Code generiert. Zeigen Sie diesen QR-Code an der ChiosBox-Abholstelle, um Ihre Pakete abzuholen.', NOW()),
('de', 'tour.step.profileInfo.title', 'Persönliche Informationen', NOW()),
('de', 'tour.step.profileInfo.content', 'Ihr Name, Ihre E-Mail, Telefonnummer und ChiosBox-ID werden hier angezeigt. Verwenden Sie die Schaltfläche ''Bearbeiten'', um Ihre Informationen zu aktualisieren.', NOW()),
('de', 'tour.step.profilePassword.title', 'Passwort ändern', NOW()),
('de', 'tour.step.profilePassword.content', 'Sie können Ihr Passwort hier aus Sicherheitsgründen ändern. Geben Sie Ihr aktuelles Passwort ein, setzen Sie ein neues und bestätigen Sie.', NOW()),
('de', 'tour.step.profileAddress.title', 'ChiosBox-Lieferadresse', NOW()),
('de', 'tour.step.profileAddress.content', 'Dies ist die Adresse unseres Lagers auf der Insel Chios. Verwenden Sie diese Adresse als Lieferadresse bei türkischen Online-Shops. Die Schaltfläche ''Adresse kopieren'' kopiert sie sofort in die Zwischenablage.', NOW()),
('de', 'tour.step.profileSubscription.title', 'Abonnement-Info', NOW()),
('de', 'tour.step.profileSubscription.content', 'Ihr aktueller Plan und Abonnementstatus werden hier angezeigt. Sie können den Plannamen (Basic-Plan) und den Status (Aktiv/Inaktiv) überprüfen.', NOW()),
('de', 'tour.step.profileExtras.title', 'Einstellungen & Benachrichtigungen', NOW()),
('de', 'tour.step.profileExtras.content', 'Aktivieren Sie Benachrichtigungen, um sofortige Paketupdates zu erhalten. Verwenden Sie die ''?''-Schaltfläche, um die Tour neu zu starten. Klicken Sie auf die Abmelde-Schaltfläche unten.', NOW()),
('de', 'tour.orderFlow.title', 'Bestell- & Versandprozess', NOW()),
('de', 'tour.orderFlow.step1.title', 'Webseite besuchen', NOW()),
('de', 'tour.orderFlow.step1.content', 'Kaufen Sie in jedem türkischen Online-Shop ein (Trendyol, Hepsiburada, Amazon usw.).', NOW()),
('de', 'tour.orderFlow.step2.title', 'Auswählen & Kaufen', NOW()),
('de', 'tour.orderFlow.step2.content', 'Wählen Sie Ihr Produkt, legen Sie es in den Warenkorb und schließen Sie die Bestellung ab. Verwenden Sie Ihre ChiosBox-Adresse bei der Bezahlung.', NOW()),
('de', 'tour.orderFlow.step3.title', 'Verkäufer versendet', NOW()),
('de', 'tour.orderFlow.step3.content', 'Wenn der Verkäufer Ihre Bestellung versendet, wird eine Sendungsnummer generiert. Notieren Sie diese zusammen mit dem Frachtnamen.', NOW()),
('de', 'tour.orderFlow.step4.title', 'Sendungsnummer bereit', NOW()),
('de', 'tour.orderFlow.step4.content', 'Ihr Frachtdienst und Ihre Sendungsnummer sind bestätigt! Jetzt können Sie das Paket bei ChiosBox melden.', NOW()),
('de', 'tour.orderFlow.step5.title', 'Bereit zum Melden!', NOW()),
('de', 'tour.orderFlow.step5.content', 'Im nächsten Schritt geben Sie Ihre Sendungsnummer und den Frachtdienst ein, um das Paket Ihrem ChiosBox-Konto hinzuzufügen.', NOW()),
('de', 'tour.orderFlow.next', 'Weiter', NOW()),
('de', 'tour.orderFlow.finish', 'Verstanden!', NOW()),
('de', 'admin.panel', 'Panel', NOW()),
('de', 'admin.users', 'Benutzer', NOW()),
('de', 'admin.languages', 'Sprachen', NOW()),
('de', 'admin.translations', 'Übersetzungen', NOW()),
('de', 'admin.logout', 'Abmelden', NOW()),
('de', 'adminLogin.title', 'Admin-Anmeldung', NOW()),
('de', 'adminLogin.email', 'E-Mail', NOW()),
('de', 'adminLogin.password', 'Passwort', NOW()),
('de', 'adminLogin.submitting', 'Anmeldung läuft...', NOW()),
('de', 'adminLogin.error.loginFailed', 'Anmeldung fehlgeschlagen', NOW()),
('de', 'adminLogin.error.noAdminAccess', 'Dieses Konto hat keinen Admin-Zugang', NOW()),
('de', 'adminLogin.error.generic', 'Ein Fehler ist aufgetreten', NOW()),
('de', 'planSelector.period', '/Mon.', NOW()),
('de', 'planSelector.temel.name', 'Basis', NOW()),
('de', 'planSelector.temel.f1', 'ChiosBox EU-Adresse', NOW()),
('de', 'planSelector.temel.f2', '14 Tage kostenlose Lagerung', NOW()),
('de', 'planSelector.temel.f3', 'Panelzugang', NOW()),
('de', 'planSelector.temel.f4', 'E-Mail-Benachrichtigungen', NOW()),
('de', 'planSelector.premium.name', 'Premium', NOW()),
('de', 'planSelector.premium.badge', 'Am beliebtesten', NOW()),
('de', 'planSelector.premium.f1', 'Alles im Basis-Paket', NOW()),
('de', 'planSelector.premium.f2', '21 Tage kostenlose Lagerung', NOW()),
('de', 'planSelector.premium.f3', 'Kostenlose Konsolidierung', NOW()),
('de', 'planSelector.premium.f4', 'Türkei Lieferverfolgung', NOW()),
('de', 'planSelector.premium.f5', 'Dedizierte Support-Hotline', NOW()),
('de', 'register.pageTitle', 'ChiosBox beitreten', NOW()),
('de', 'register.pageSubtitle', 'Holen Sie sich jetzt Ihre europäische Lieferadresse und genießen Sie den Tür-zu-Tür-Versand.', NOW()),
('de', 'store.error.packagesLoadFailed', 'Pakete konnten nicht geladen werden', NOW()),
('de', 'store.error.generic', 'Ein Fehler ist aufgetreten', NOW()),
('de', 'store.error.deleteFailed', 'Löschen fehlgeschlagen', NOW()),
('de', 'store.error.intakeFailed', 'Annahme fehlgeschlagen', NOW()),
('de', 'store.error.deliveryFailed', 'Zustellung fehlgeschlagen', NOW()),
('de', 'store.error.discardFailed', 'Entsorgung fehlgeschlagen', NOW()),
('de', 'store.error.registerFailed', 'Registrierung fehlgeschlagen', NOW()),
('de', 'api.error.loginRequired', 'Sie müssen sich anmelden', NOW()),
('de', 'api.error.unauthorized', 'Nicht autorisierter Zugriff', NOW()),
('de', 'api.error.authCheckFailed', 'Autorisierungsprüfung fehlgeschlagen', NOW()),
('de', 'api.error.rateLimited', 'Zu viele Anfragen. Bitte versuchen Sie es später erneut.', NOW()),
('de', 'authLayout.heading', 'Europa vor Ihrer Tür mit ChiosBox', NOW()),
('de', 'authLayout.description', 'Tür-zu-Tür-Versand von der Türkei nach Europa, Europa in die Türkei', NOW()),
('de', 'login.pageTitle', 'Willkommen zurück', NOW()),
('de', 'login.pageSubtitle', 'Melden Sie sich bei Ihrem ChiosBox-Konto an', NOW()),
('de', 'packages.demurrageFee', 'Verzugsgebühr', NOW()),
('de', 'packages.weight', 'Gewicht', NOW()),
('de', 'packages.noMessagesYet', 'Noch keine Nachrichten', NOW()),
('de', 'packages.chatHint', 'Hier können Sie Ihre Fragen zum Paket stellen', NOW()),
('de', 'packages.giveUp', 'Abbrechen', NOW()),
('de', 'packages.daysFree', '{days} Tage kostenlos', NOW()),
('de', 'packages.carrier', 'Spediteur', NOW()),
('de', 'packages.trackingNo', 'Sendungsnummer', NOW()),
('de', 'packages.notification', 'Benachrichtigung', NOW()),
('de', 'packages.dimensions', 'Abmessungen', NOW()),
('de', 'packages.note', 'Notiz', NOW()),
('de', 'packages.deletePackage', 'Paket löschen', NOW()),
('de', 'packages.deleting', 'Wird gelöscht...', NOW()),
('de', 'packages.confirmDelete', 'Ja, löschen', NOW()),
('de', 'packages.close', 'Schließen', NOW()),
('de', 'packages.notifyNew', 'Neu melden', NOW()),
('de', 'packages.demurrageShort', 'Verzugsgebühr', NOW()),
('de', 'common.days', 'Tage', NOW()),
('de', 'islandScene.departed.badge', 'Aus der Türkei abgeschickt', NOW()),
('de', 'islandScene.departed.title', 'Ihre Pakete sind unterwegs', NOW()),
('de', 'islandScene.departed.description', 'Paketkäufe von türkischen Verkäufern sind auf dem Weg zu unserem Lager auf Chios.', NOW()),
('de', 'islandScene.crossing.badge', 'Überquert die Ägäis', NOW()),
('de', 'islandScene.crossing.title', 'Sicher transportiert', NOW()),
('de', 'islandScene.crossing.description', 'Über Schiffe und Frachtrouten ist jedes Paket versichert und verfolgbar.', NOW()),
('de', 'islandScene.arrived.badge', 'Am Ziel angekommen', NOW()),
('de', 'islandScene.arrived.title', 'In unserem Lager auf Chios', NOW()),
('de', 'islandScene.arrived.description', 'Konsolidieren Sie, sparen Sie, wir liefern an Ihre Tür.', NOW()),
('de', 'bento.route.title', 'Nahtlose Logistik', NOW()),
('de', 'bento.route.euStore', 'EU-Shop', NOW()),
('de', 'bento.route.warehouse', 'Chios-Lager', NOW()),
('de', 'bento.storage.title', 'Wartezeit', NOW()),
('de', 'bento.storage.days', 'Tage Kostenlos', NOW()),
('de', 'bento.storage.subtitle', 'Lagerrecht', NOW()),
('de', 'bento.delivery.title', 'Einfache Lieferung', NOW()),
('de', 'bento.delivery.headline', 'Zur Insel rüber', NOW()),
('de', 'bento.delivery.subtitle', 'Abholung mit Wochenendfähre.', NOW()),
('de', 'adminCustomers.backToList', 'Zurück zu Kunden', NOW()),
('de', 'adminCustomers.package', 'Paket', NOW()),
('de', 'adminCustomers.totalSpent', 'Gesamtausgaben', NOW()),
('de', 'adminCustomers.pending', 'Ausstehend', NOW()),
('de', 'adminCustomers.packages', 'Pakete', NOW()),
('de', 'adminCustomers.invoices', 'Rechnungen', NOW()),
('de', 'adminCustomers.noPackagesYet', 'Noch keine Pakete', NOW()),
('de', 'adminCustomers.noInvoicesYet', 'Noch keine Rechnungen', NOW()),
('de', 'adminCustomers.paid', 'Bezahlt', NOW()),
('de', 'adminCustomers.cancelled', 'Storniert', NOW()),
('de', 'adminCustomers.waiting', 'Ausstehend', NOW()),
('de', 'adminCustomers.status.bekleniyor', 'Ausstehend', NOW()),
('de', 'adminCustomers.status.yolda', 'Unterwegs', NOW()),
('de', 'adminCustomers.status.depoda', 'Im Lager', NOW()),
('de', 'adminCustomers.status.birlestirildi', 'Konsolidiert', NOW()),
('de', 'adminCustomers.status.teslim_edildi', 'Zugestellt', NOW()),
('de', 'adminLogin.brandingTitle', 'ChiosBox Admin-Panel', NOW()),
('de', 'adminLogin.brandingDesc', 'Admin-Anmeldung für Paketverwaltung, Abrechnung und Kundenvorgänge', NOW()),
('de', 'adminLogin.heading', 'Admin-Panel', NOW()),
('de', 'adminLogin.subheading', 'Melden Sie sich mit Ihrem Admin-Konto an', NOW()),
('de', 'adminLogin.customerQuestion', 'Sind Sie Kunde?', NOW()),
('de', 'adminLogin.customerLogin', 'Kundenanmeldung', NOW()),
('de', 'adminTranslations.title', 'Übersetzungen', NOW()),
('de', 'adminTranslations.description', 'Alle Texte bearbeiten', NOW()),
('de', 'adminTranslations.saveChanges', '{count} Änderungen speichern', NOW()),
('de', 'adminTranslations.saving', 'Wird gespeichert...', NOW()),
('de', 'adminTranslations.saved', '{count} Übersetzungen gespeichert', NOW()),
('de', 'adminTranslations.saveFailed', 'Speichern fehlgeschlagen', NOW()),
('de', 'adminTranslations.searchPlaceholder', 'Übersetzungsschlüssel suchen...', NOW()),
('de', 'adminTranslations.noResults', 'Keine Übersetzungen für diese Suche gefunden', NOW()),
('de', 'adminTranslations.empty', 'Noch keine Übersetzungen für diese Sprache hinzugefügt', NOW()),
('de', 'adminTranslations.delete', 'Löschen', NOW()),
('de', 'adminLanguages.title', 'Sprachen', NOW()),
('de', 'adminLanguages.description', 'Anwendungssprachen verwalten', NOW()),
('de', 'adminLanguages.addLanguage', 'Sprache hinzufügen', NOW()),
('de', 'adminLanguages.addNewLanguage', 'Neue Sprache hinzufügen', NOW()),
('de', 'adminLanguages.code', 'Code', NOW()),
('de', 'adminLanguages.name', 'Name', NOW()),
('de', 'adminLanguages.flag', 'Flaggen-Emoji', NOW()),
('de', 'adminLanguages.add', 'Hinzufügen', NOW()),
('de', 'adminLanguages.adding', 'Wird hinzugefügt...', NOW()),
('de', 'adminLanguages.cancel', 'Abbrechen', NOW()),
('de', 'adminLanguages.default', 'Standard', NOW()),
('de', 'adminLanguages.active', 'Aktiv', NOW()),
('de', 'adminLanguages.inactive', 'Inaktiv', NOW()),
('de', 'adminLanguages.setDefault', 'Als Standard festlegen', NOW()),
('de', 'adminLanguages.delete', 'Löschen', NOW()),
('de', 'adminLanguages.remove', 'Entfernen', NOW()),
('de', 'adminLanguages.noLanguagesYet', 'Noch keine Sprachen hinzugefügt', NOW()),
('de', 'admin.policies', 'Richtlinien', NOW()),
('de', 'adminPolicies.title', 'Rechtliche Richtlinien', NOW()),
('de', 'adminPolicies.description', 'Verwalten Sie Nutzungsbedingungen, Datenschutzerklärung und KVKK-Belehrungstexte.', NOW()),
('de', 'admin.settings', 'Einstellungen', NOW()),
('de', 'adminSettings.title', 'Systemeinstellungen', NOW()),
('de', 'adminSettings.description', 'Verwalten Sie Gebühren, Planpreise, Grenzen und Geschäftsregeln. Änderungen gelten sofort.', NOW()),
('de', 'adminSettings.saving', 'Speichern...', NOW()),
('de', 'adminSettings.saveChanges', '{count} Änderungen Speichern', NOW()),
('de', 'adminSettings.saved', '{count} Einstellungen gespeichert.', NOW()),
('de', 'adminSettings.saveFailed', 'Speichern fehlgeschlagen.', NOW()),
('de', 'adminSettings.empty', 'Keine Einstellungen in dieser Kategorie gefunden.', NOW()),
('de', 'adminSettings.catFees', 'Gebühren', NOW()),
('de', 'adminSettings.catPlans', 'Pläne', NOW()),
('de', 'adminSettings.catLimits', 'Grenzen', NOW()),
('de', 'adminSettings.catBusiness', 'Geschäftsregeln', NOW()),
('de', 'adminSettings.catRateLimits', 'Rate Limits', NOW()),
('de', 'adminSettings.warningTitle', 'Achtung', NOW()),
('de', 'adminSettings.warningText', 'Gebühren- und Planänderungen betreffen nur neue Transaktionen. Bestehende Rechnungen behalten ihre Beträge. Bitte sorgfältig prüfen.', NOW()),
('de', 'adminPolicies.titleLabel', 'Titel', NOW()),
('de', 'adminPolicies.titlePlaceholder', 'Richtlinientitel', NOW()),
('de', 'adminPolicies.contentLabel', 'Inhalt', NOW()),
('de', 'adminPolicies.contentPlaceholder', 'HTML-Inhalt hier schreiben...', NOW()),
('de', 'adminPolicies.contentHint', 'Sie können Inhalte im HTML-Format eingeben. Tags werden unterstützt.', NOW()),
('de', 'adminPolicies.save', 'Speichern', NOW()),
('de', 'adminPolicies.saving', 'Wird gespeichert...', NOW()),
('de', 'adminPolicies.saved', 'Erfolgreich gespeichert', NOW()),
('de', 'adminPolicies.saveFailed', 'Speichern fehlgeschlagen', NOW()),
('de', 'adminPolicies.published', 'Veröffentlicht', NOW()),
('de', 'adminPolicies.draft', 'Entwurf', NOW()),
('de', 'footer.kvkk', 'KVKK Belehrung', NOW())
ON CONFLICT (language_code, key) DO UPDATE SET value = EXCLUDED.value, updated_at = EXCLUDED.updated_at;