('en', 'profile.passwordChanged', 'Password changed successfully!', NOW()),
('en', 'profile.passwordRequired', 'Please fill in all password fields.', NOW()),
('en', 'profile.passwordMinLength', 'Password must be at least 6 characters.', NOW()),
('en', 'profile.passwordMismatch', 'Passwords do not match.', NOW()),
('en', 'profile.passwordChangeFailed', 'Password change failed.', NOW()),
('en', 'profile.addressLabel', 'Address', NOW()),
('en', 'profile.addressPlaceholder', 'Enter your address', NOW()),
('en', 'tour.start', 'Start Tour Guide', NOW()),
('en', 'tour.next', 'Next', NOW()),
('en', 'tour.back', 'Back', NOW()),
('en', 'tour.finish', 'Finish', NOW()),
('en', 'tour.skip', 'Skip', NOW()),
('en', 'tour.close', 'Close', NOW()),
('en', 'tour.helpTooltip', 'Tour Guide', NOW()),
('en', 'tour.step.dashboardWelcome.title', 'Welcome', NOW()),
('en', 'tour.step.dashboardWelcome.content', 'Welcome to ChiosBox! This is your dashboard. Your ChiosBox ID and delivery address appear at the top. Use the ''Copy My Address'' button to copy your address for use in Turkish online stores.', NOW()),
('en', 'tour.step.dashboardStats.title', 'Statistics Cards', NOW()),
('en', 'tour.step.dashboardStats.content', 'See your active package count, warehouse and in-transit packages, remaining free storage days, and pending invoice count. Each card keeps you informed.', NOW()),
('en', 'tour.step.dashboardPackages.title', 'Active Packages', NOW()),
('en', 'tour.step.dashboardPackages.content', 'Your recently added packages are listed here with status badges. If you haven''t reported any packages yet, an empty state message appears. Click ''View All'' to see all your packages.', NOW()),
('en', 'tour.step.dashboardActions.title', 'Quick Actions', NOW()),
('en', 'tour.step.dashboardActions.content', 'Quick access to frequent actions. ''Copy My Address'' copies your ChiosBox address — use it as your delivery address when shopping online. ''Pay Now'' lets you pay pending invoices.', NOW()),
('en', 'tour.step.actions.title', 'Report Package — Order Process', NOW()),
('en', 'tour.step.actions.content', 'After your online purchase, when the seller ships your order, a tracking number is generated. Enter that number here to add the package to your ChiosBox account. This way we can notify you when it arrives at the warehouse. Let''s fill out the form step by step!', NOW()),
('en', 'tour.step.tracking.title', 'Tracking Number', NOW()),
('en', 'tour.step.tracking.content', 'Enter the shipping tracking number you received from the seller. The carrier is often detected automatically from the number format. For example: TR-2026-0044.', NOW()),
('en', 'tour.step.carrier.title', 'Shipping Carrier', NOW()),
('en', 'tour.step.carrier.content', 'Select which carrier is delivering your package. If not auto-detected from the tracking number, choose from the list or select ''Other'' to enter manually.', NOW()),
('en', 'tour.step.packageForm.title', 'Package Details', NOW()),
('en', 'tour.step.packageForm.content', 'Enter your package details: content description (identifies what''s inside), weight (affects pricing), dimensions (important for box selection), and special notes. This information speeds up package processing.', NOW()),
('en', 'tour.step.submit.title', 'Submit Package Report', NOW()),
('en', 'tour.step.submit.content', 'Once all fields are filled, click this button to report your package to ChiosBox. In demo mode, the form will be filled and the 3rd package will be added to your list.', NOW()),
('en', 'tour.step.packages.title', 'My Packages — List', NOW()),
('en', 'tour.step.packages.content', 'All your reported packages are listed here. Use search and filters to find packages quickly. Each card shows status, carrier, tracking number, and contents. You now have 3 demo packages!', NOW()),
('en', 'tour.step.packageCard.title', 'Package Card', NOW()),
('en', 'tour.step.packageCard.content', 'Each package card shows a status badge (awaiting, in transit, in warehouse, delivered), carrier, tracking number, and content summary. Click the card for details.', NOW()),
('en', 'tour.step.packageDetail.title', 'Package Details', NOW()),
('en', 'tour.step.packageDetail.content', 'Clicking a package opens the detail modal. Here you can see warehouse arrival date, remaining free storage days, shelf location, and a warehouse photo. Use the support chat to ask questions about your package. Review your package info here before making any payments.', NOW()),
('en', 'tour.step.consolidateLeft.title', 'Warehouse Packages', NOW()),
('en', 'tour.step.consolidateLeft.content', 'Your warehouse packages are listed in the left panel. Select packages to add to the consolidation box. Combine multiple packages into one box to save on international shipping costs.', NOW()),
('en', 'tour.step.consolidateRight.title', 'Consolidation Box', NOW()),
('en', 'tour.step.consolidateRight.content', 'Your selected packages transfer to the master box. A consolidation fee is added when combining, but it''s much cheaper than shipping separately. You can see the difference in the price comparison.', NOW()),
('en', 'tour.step.consolidateConfirm.title', 'Consolidation Confirmation', NOW()),
('en', 'tour.step.consolidateConfirm.content', 'After selecting your packages, click this button to submit your consolidation request. This step is optional — you can also ship packages individually.', NOW()),
('en', 'tour.step.checkout.title', 'Invoice Review', NOW()),
('en', 'tour.step.checkout.content', 'Review your invoices before paying. See line items like acceptance fee, consolidation fee, and demurrage charges with per-package breakdown. Check the total. You can go back to your packages to make edits.', NOW()),
('en', 'tour.step.checkoutPay.title', 'Payment & QR Code', NOW()),
('en', 'tour.step.checkoutPay.content', 'After confirming payment, your delivery QR code is generated. Show this QR code at the ChiosBox pickup point to collect your packages.', NOW()),
('en', 'tour.step.profileInfo.title', 'Personal Information', NOW()),
('en', 'tour.step.profileInfo.content', 'Your name, email, phone number, and ChiosBox ID appear here. Use the Edit button to update your information and the Save button to save changes.', NOW()),
('en', 'tour.step.profilePassword.title', 'Change Password', NOW()),
('en', 'tour.step.profilePassword.content', 'You can change your password here for security. Enter your current password, set a new one, and confirm.', NOW()),
('en', 'tour.step.profileAddress.title', 'ChiosBox Delivery Address', NOW()),
('en', 'tour.step.profileAddress.content', 'This is the address of our warehouse on Chios Island. Use this address as your delivery address when shopping from Turkish online stores. The ''Copy Address'' button copies it to your clipboard instantly.', NOW()),
('en', 'tour.step.profileSubscription.title', 'Subscription Info', NOW()),
('en', 'tour.step.profileSubscription.content', 'Your current plan and subscription status appear here. You can check the plan name (Basic Plan) and status (Active/Inactive).', NOW()),
('en', 'tour.step.profileExtras.title', 'Settings & Notifications', NOW()),
('en', 'tour.step.profileExtras.content', 'Enable notifications to receive instant package updates. Use the ''?'' button to restart the tour. Click the logout button at the bottom to sign out.', NOW()),
('en', 'tour.orderFlow.title', 'Order & Shipping Process', NOW()),
('en', 'tour.orderFlow.step1.title', 'Visit the Website', NOW()),
('en', 'tour.orderFlow.step1.content', 'Shop from any Turkish online store (Trendyol, Hepsiburada, Amazon, etc.).', NOW()),
('en', 'tour.orderFlow.step2.title', 'Select & Purchase', NOW()),
('en', 'tour.orderFlow.step2.content', 'Choose your product, add to cart, and complete the order. Use your ChiosBox address at checkout.', NOW()),
('en', 'tour.orderFlow.step3.title', 'Seller Ships', NOW()),
('en', 'tour.orderFlow.step3.content', 'When the seller ships your order, a tracking number is generated. Note it down along with the carrier name.', NOW()),
('en', 'tour.orderFlow.step4.title', 'Tracking Number Ready', NOW()),
('en', 'tour.orderFlow.step4.content', 'Your carrier and tracking number are confirmed! Now you can report the package to ChiosBox.', NOW()),
('en', 'tour.orderFlow.step5.title', 'Ready to Report!', NOW()),
('en', 'tour.orderFlow.step5.content', 'In the next step, enter your tracking number and carrier to add the package to your ChiosBox account.', NOW()),
('en', 'tour.orderFlow.next', 'Next', NOW()),
('en', 'tour.orderFlow.finish', 'Got It!', NOW()),
('en', 'actions.carrier.other', 'Other', NOW()),
('en', 'actions.weight.light', 'Light', NOW()),
('en', 'actions.weight.medium', 'Medium', NOW()),
('en', 'actions.weight.heavy', 'Heavy', NOW()),
('en', 'actions.weight.veryHeavy', 'Very Heavy', NOW()),
('en', 'actions.dimension.small', 'Small', NOW()),
('en', 'actions.dimension.smallBox', 'Small box', NOW()),
('en', 'actions.dimension.medium', 'Medium', NOW()),
('en', 'actions.dimension.mediumBox', 'Standard box', NOW()),
('en', 'actions.dimension.large', 'Large', NOW()),
('en', 'actions.dimension.largeBox', 'Large box', NOW()),
('en', 'actions.submitFailed', 'Submission failed', NOW()),
('en', 'actions.connectionError', 'Connection error — please try again', NOW()),
('en', 'actions.success.title', 'Package Reported!', NOW()),
('en', 'actions.feeLabel', 'Accept Fee', NOW()),
('en', 'actions.feeDescription', 'To be paid when package arrives at warehouse', NOW()),
('en', 'actions.feeExplanation', 'An invoice will be created when your package arrives at the ChiosBox warehouse and you will be asked to pay.', NOW()),
('en', 'actions.goToPayment', 'Go to Payment', NOW()),
('en', 'actions.viewPackages', 'View My Packages', NOW()),
('en', 'actions.newReport', 'Report New Package', NOW()),
('en', 'actions.formDescription', 'Enter the details of your package', NOW()),
('en', 'actions.trackingLabel', 'Tracking Number', NOW()),
('en', 'actions.trackingPlaceholder', 'e.g.: 1Z999AA10123456784', NOW()),
('en', 'actions.carrierLabel', 'Carrier', NOW()),
('en', 'actions.carrierPlaceholder', 'Enter carrier name', NOW()),
('en', 'actions.contentLabel', 'Package Contents', NOW()),
('en', 'actions.contentPlaceholder', 'e.g.: Nike Air Max 90', NOW()),
('en', 'actions.weightLabel', 'Weight', NOW()),
('en', 'actions.optional', '(optional)', NOW()),
('en', 'actions.weightManualPlaceholder', 'or enter manually', NOW()),
('en', 'actions.weightUnit', 'kg', NOW()),
('en', 'actions.sizeLabel', 'Size', NOW()),
('en', 'actions.sizeManualPlaceholder', 'or manual: 30x20x15 cm', NOW()),
('en', 'actions.noteLabel', 'Note', NOW()),
('en', 'actions.notePlaceholder', 'Fragile, gift wrap, etc.', NOW()),
('en', 'actions.submitting', 'Submitting...', NOW()),
('en', 'actions.submit', 'Report', NOW()),
('en', 'sidebar.home', 'Home', NOW()),
('en', 'sidebar.packages', 'My Packages', NOW()),
('en', 'sidebar.consolidate', 'Consolidate', NOW()),
('en', 'sidebar.actions', 'Actions', NOW()),
('en', 'sidebar.payment', 'Payment', NOW()),
('en', 'sidebar.profile', 'Profile', NOW()),
('en', 'sidebar.logout', 'Log Out', NOW()),
('en', 'admin.panel', 'Panel', NOW()),
('en', 'admin.users', 'Users', NOW()),
('en', 'admin.languages', 'Languages', NOW()),
('en', 'admin.translations', 'Translations', NOW()),
('en', 'admin.logout', 'Logout', NOW()),
('en', 'adminLogin.title', 'Admin Login', NOW()),
('en', 'adminLogin.email', 'Email', NOW()),
('en', 'adminLogin.password', 'Password', NOW()),
('en', 'adminLogin.submitting', 'Logging in...', NOW()),
('en', 'adminLogin.error.loginFailed', 'Login failed', NOW()),
('en', 'adminLogin.error.noAdminAccess', 'This account does not have admin access', NOW()),
('en', 'adminLogin.error.generic', 'An error occurred', NOW()),
('en', 'planSelector.period', '/mo', NOW()),
('en', 'planSelector.temel.name', 'Basic', NOW()),
('en', 'planSelector.temel.f1', 'ChiosBox EU address', NOW()),
('en', 'planSelector.temel.f2', '14 days free storage', NOW()),
('en', 'planSelector.temel.f3', 'Panel access', NOW()),
('en', 'planSelector.temel.f4', 'Email notifications', NOW()),
('en', 'planSelector.premium.name', 'Premium', NOW()),
('en', 'planSelector.premium.badge', 'Most Popular', NOW()),
('en', 'planSelector.premium.f1', 'Everything in Basic plan', NOW()),
('en', 'planSelector.premium.f2', '21 days free storage', NOW()),
('en', 'planSelector.premium.f3', 'Free consolidation', NOW()),
('en', 'planSelector.premium.f4', 'Turkey delivery tracking', NOW()),
('en', 'planSelector.premium.f5', 'Dedicated support line', NOW()),
('en', 'register.pageTitle', 'Join ChiosBox', NOW()),
('en', 'register.pageSubtitle', 'Get your European delivery address now and enjoy door-to-door shipping.', NOW()),
('en', 'store.error.packagesLoadFailed', 'Failed to load packages', NOW()),
('en', 'store.error.generic', 'An error occurred', NOW()),
('en', 'store.error.deleteFailed', 'Delete failed', NOW()),
('en', 'store.error.intakeFailed', 'Intake failed', NOW()),
('en', 'store.error.deliveryFailed', 'Delivery failed', NOW()),
('en', 'store.error.discardFailed', 'Discard failed', NOW()),
('en', 'store.error.registerFailed', 'Registration failed', NOW()),
('en', 'api.error.loginRequired', 'You need to log in', NOW()),
('en', 'api.error.unauthorized', 'Unauthorized access', NOW()),
('en', 'api.error.authCheckFailed', 'Authorization check failed', NOW()),
('en', 'api.error.rateLimited', 'Too many requests. Please try again later.', NOW()),
('en', 'authLayout.heading', 'Europe at Your Doorstep with ChiosBox', NOW()),
('en', 'authLayout.description', 'Door-to-door shipping service from Turkey to Europe, Europe to Turkey', NOW()),
('en', 'login.pageTitle', 'Welcome Back', NOW()),
('en', 'login.pageSubtitle', 'Log in to your ChiosBox account', NOW()),
('en', 'packages.demurrageFee', 'Delay Fee', NOW()),
('en', 'packages.weight', 'Weight', NOW()),
('en', 'packages.noMessagesYet', 'No messages yet', NOW()),
('en', 'packages.chatHint', 'You can ask your package-related questions here', NOW()),
('en', 'packages.giveUp', 'Cancel', NOW()),
('en', 'packages.daysFree', '{days} days free', NOW()),
('en', 'packages.carrier', 'Carrier', NOW()),
('en', 'packages.trackingNo', 'Tracking No', NOW()),
('en', 'packages.notification', 'Notification', NOW()),
('en', 'packages.dimensions', 'Dimensions', NOW()),
('en', 'packages.note', 'Note', NOW()),
('en', 'packages.deletePackage', 'Delete Package', NOW()),
('en', 'packages.deleting', 'Deleting...', NOW()),
('en', 'packages.confirmDelete', 'Yes, Delete', NOW()),
('en', 'packages.close', 'Close', NOW()),
('en', 'packages.notifyNew', 'Report New', NOW()),
('en', 'packages.demurrageShort', 'late fee', NOW()),
('en', 'common.days', 'days', NOW()),
('en', 'islandScene.departed.badge', 'Departed from Turkey', NOW()),
('en', 'islandScene.departed.title', 'Your Packages Are On the Way', NOW()),
('en', 'islandScene.departed.description', 'Packages purchased from Turkish sellers are heading to our Chios warehouse.', NOW()),
('en', 'islandScene.crossing.badge', 'Crossing the Aegean', NOW()),
('en', 'islandScene.crossing.title', 'Transported Safely', NOW()),
('en', 'islandScene.crossing.description', 'Via boats and cargo routes, every package is insured and trackable.', NOW()),
('en', 'islandScene.arrived.badge', 'Arrived at Destination', NOW()),
('en', 'islandScene.arrived.title', 'At Our Chios Warehouse', NOW()),
('en', 'islandScene.arrived.description', 'Consolidate, save, and we''ll deliver to your door.', NOW()),
('en', 'bento.route.title', 'Seamless Logistics', NOW()),
('en', 'bento.route.euStore', 'EU Store', NOW()),
('en', 'bento.route.warehouse', 'Chios Warehouse', NOW()),
('en', 'bento.storage.title', 'Wait Time', NOW()),
('en', 'bento.storage.days', 'Days Free', NOW()),
('en', 'bento.storage.subtitle', 'Storage Right', NOW()),
('en', 'bento.delivery.title', 'Easy Delivery', NOW()),
('en', 'bento.delivery.headline', 'Cross to the Island', NOW()),
('en', 'bento.delivery.subtitle', 'Pick up by weekend ferry.', NOW()),
('en', 'adminCustomers.backToList', 'Back to Customers', NOW()),
('en', 'adminCustomers.package', 'Package', NOW()),
('en', 'adminCustomers.totalSpent', 'Total Spent', NOW()),
('en', 'adminCustomers.pending', 'Pending', NOW()),
('en', 'adminCustomers.packages', 'Packages', NOW()),
('en', 'adminCustomers.invoices', 'Invoices', NOW()),
('en', 'adminCustomers.noPackagesYet', 'No packages yet', NOW()),
('en', 'adminCustomers.noInvoicesYet', 'No invoices yet', NOW()),
('en', 'adminCustomers.paid', 'Paid', NOW()),
('en', 'adminCustomers.cancelled', 'Cancelled', NOW()),
('en', 'adminCustomers.waiting', 'Pending', NOW()),
('en', 'adminCustomers.status.bekleniyor', 'Pending', NOW()),
('en', 'adminCustomers.status.yolda', 'In Transit', NOW()),
('en', 'adminCustomers.status.depoda', 'In Warehouse', NOW()),
('en', 'adminCustomers.status.birlestirildi', 'Consolidated', NOW()),
('en', 'adminCustomers.status.teslim_edildi', 'Delivered', NOW()),
('en', 'adminLogin.brandingTitle', 'ChiosBox Admin Panel', NOW()),
('en', 'adminLogin.brandingDesc', 'Admin login for package management, billing, and customer operations', NOW()),
('en', 'adminLogin.heading', 'Admin Panel', NOW()),
('en', 'adminLogin.subheading', 'Log in with your admin account', NOW()),
('en', 'adminLogin.customerQuestion', 'Are you a customer?', NOW()),
('en', 'adminLogin.customerLogin', 'Customer Login', NOW()),
('en', 'adminTranslations.title', 'Translations', NOW()),
('en', 'adminTranslations.description', 'Edit all text content', NOW()),
('en', 'adminTranslations.saveChanges', 'Save {count} Changes', NOW()),
('en', 'adminTranslations.saving', 'Saving...', NOW()),
('en', 'adminTranslations.saved', '{count} translations saved', NOW()),
('en', 'adminTranslations.saveFailed', 'Save failed', NOW()),
('en', 'adminTranslations.searchPlaceholder', 'Search translation keys...', NOW()),
('en', 'adminTranslations.noResults', 'No translations found for this search', NOW()),
('en', 'adminTranslations.empty', 'No translations added for this language yet', NOW()),
('en', 'adminTranslations.delete', 'Delete', NOW()),
('en', 'adminLanguages.title', 'Languages', NOW()),
('en', 'adminLanguages.description', 'Manage application languages', NOW()),
('en', 'adminLanguages.addLanguage', 'Add Language', NOW()),
('en', 'adminLanguages.addNewLanguage', 'Add New Language', NOW()),
('en', 'adminLanguages.code', 'Code', NOW()),
('en', 'adminLanguages.name', 'Name', NOW()),
('en', 'adminLanguages.flag', 'Flag Emoji', NOW()),
('en', 'adminLanguages.add', 'Add', NOW()),
('en', 'adminLanguages.adding', 'Adding...', NOW()),
('en', 'adminLanguages.cancel', 'Cancel', NOW()),
('en', 'adminLanguages.default', 'Default', NOW()),
('en', 'adminLanguages.active', 'Active', NOW()),
('en', 'adminLanguages.inactive', 'Inactive', NOW()),
('en', 'adminLanguages.setDefault', 'Set Default', NOW()),
('en', 'adminLanguages.delete', 'Delete', NOW()),
('en', 'adminLanguages.remove', 'Remove', NOW()),
('en', 'adminLanguages.noLanguagesYet', 'No languages added yet', NOW()),
('en', 'admin.policies', 'Policies', NOW()),
('en', 'adminPolicies.title', 'Legal Policies', NOW()),
('en', 'adminPolicies.description', 'Manage terms of service, privacy policy, and KVKK disclosure texts.', NOW()),
('en', 'admin.settings', 'Settings', NOW()),
('en', 'adminSettings.title', 'System Settings', NOW()),
('en', 'adminSettings.description', 'Manage fees, plan prices, limits and business rules. Changes take effect immediately.', NOW()),
('en', 'adminSettings.saving', 'Saving...', NOW()),
('en', 'adminSettings.saveChanges', 'Save {count} Changes', NOW()),
('en', 'adminSettings.saved', '{count} settings saved.', NOW()),
('en', 'adminSettings.saveFailed', 'Save failed.', NOW()),
('en', 'adminSettings.empty', 'No settings found in this category.', NOW()),
('en', 'adminSettings.catFees', 'Fees', NOW()),
('en', 'adminSettings.catPlans', 'Plans', NOW()),
('en', 'adminSettings.catLimits', 'Limits', NOW()),
('en', 'adminSettings.catBusiness', 'Business Rules', NOW()),
('en', 'adminSettings.catRateLimits', 'Rate Limits', NOW()),
('en', 'adminSettings.warningTitle', 'Warning', NOW()),
('en', 'adminSettings.warningText', 'Fee and plan changes affect new transactions only. Existing invoices keep their amounts. Make sure before changing.', NOW()),
('en', 'adminPolicies.titleLabel', 'Title', NOW()),
('en', 'adminPolicies.titlePlaceholder', 'Policy title', NOW()),
('en', 'adminPolicies.contentLabel', 'Content', NOW()),
('en', 'adminPolicies.contentPlaceholder', 'Write HTML content here...', NOW()),
('en', 'adminPolicies.contentHint', 'You can enter content in HTML format. Tags are supported.', NOW()),
('en', 'adminPolicies.save', 'Save', NOW()),
('en', 'adminPolicies.saving', 'Saving...', NOW()),
('en', 'adminPolicies.saved', 'Saved successfully', NOW()),
('en', 'adminPolicies.saveFailed', 'Save failed', NOW()),
('en', 'adminPolicies.published', 'Published', NOW()),
('en', 'adminPolicies.draft', 'Draft', NOW()),
('en', 'footer.kvkk', 'KVKK Disclosure', NOW()),
('de', 'nav.howItWorks', 'Wie funktioniert es?', NOW()),
('de', 'nav.pricing', 'Preise', NOW()),
('de', 'nav.trust', 'Vertrauen', NOW()),
('de', 'nav.logout', 'Abmelden', NOW()),
('de', 'nav.login', 'Anmelden', NOW()),
('de', 'nav.getAddress', 'Jetzt Adresse holen', NOW()),
('de', 'footer.description', 'Paketkonsolidierungsverwaltung mit Sitz auf Chios für E-Commerce-Käufer von der Türkei in die EU.', NOW()),
('de', 'footer.service', 'Service', NOW()),
('de', 'footer.howItWorks', 'Wie funktioniert es?', NOW()),
('de', 'footer.pricing', 'Preisgestaltung', NOW()),
('de', 'footer.consolidation', 'Konsolidierung', NOW()),
('de', 'footer.support', 'Support', NOW()),
('de', 'footer.faq', 'Häufig gestellte Fragen', NOW()),
('de', 'footer.contact', 'Kontakt', NOW()),
('de', 'footer.tracking', 'Sendungsverfolgung', NOW()),
('de', 'footer.legal', 'Rechtliches', NOW()),
('de', 'footer.privacy', 'Datenschutzrichtlinie', NOW()),
('de', 'footer.terms', 'Nutzungsbedingungen', NOW()),
('de', 'footer.sslSecure', 'SSL-Sicher', NOW()),
('de', 'footer.copyright', '© 2026 ChiosBox — Griechische IKE-Firma. Alle Rechte vorbehalten.', NOW()),
('de', 'footer.location', 'Chios, Griechenland', NOW()),
('de', 'hero.tag', 'Türkei → EU Versand leicht gemacht', NOW()),
('de', 'hero.badge', 'Türkei → EU Versand leicht gemacht', NOW()),
('de', 'hero.title.line1', 'Europäische Lieferung', NOW()),
('de', 'hero.title.line2', 'Ihre Adresse', NOW()),
('de', 'hero.title.line3', 'Bereit', NOW()),
('de', 'hero.title1', 'Europäische Lieferung', NOW()),
('de', 'hero.title2', 'Ihre Adresse', NOW()),
('de', 'hero.title3', 'Bereit', NOW()),
('de', 'hero.description', 'Kaufen Sie in der Türkei, lassen Sie Ihre Pakete an unserem Lager auf Chios ankommen. Konsolidieren, sparen, und wir liefern an Ihre Tür.', NOW()),
('de', 'hero.cta', 'Jetzt Adresse holen', NOW()),
('de', 'hero.ctaSecondary', 'Wie funktioniert es?', NOW()),
('de', 'hero.howItWorks', 'Wie funktioniert es?', NOW()),
('de', 'hero.feature1', 'Ab €9.99/Monat', NOW()),
('de', 'hero.feature2', 'Sofortige Adresse', NOW()),
('de', 'hero.feature3', 'Tür-zu-Tür-Lieferung', NOW()),
('de', 'howItWorks.tag', 'Einfach & Schnell', NOW()),
('de', 'howItWorks.title', 'Wie funktioniert es?', NOW()),
('de', 'howItWorks.description', 'Verwalten Sie Ihren Versand von der Türkei nach Europa in vier einfachen Schritten.', NOW()),
('de', 'howItWorks.step1.number', '01', NOW()),
('de', 'howItWorks.step1.title', 'Einkaufen', NOW()),
('de', 'howItWorks.step1.description', 'Kaufen Sie in jedem Online-Shop in der Türkei. Verwenden Sie Ihre ChiosBox-Adresse als Lieferadresse.', NOW()),
('de', 'howItWorks.step1.desc', 'Kaufen Sie in jedem Online-Shop in der Türkei. Verwenden Sie Ihre ChiosBox-Adresse als Lieferadresse.', NOW()),
('de', 'howItWorks.step2.number', '02', NOW()),
('de', 'howItWorks.step2.title', 'Ankommen in unserem Lager', NOW()),
('de', 'howItWorks.step2.description', 'Ihre Pakete kommen in unserem sicheren Lager auf Chios an. Der Barcode wird gescannt und im System erfasst.', NOW()),
('de', 'howItWorks.step2.desc', 'Ihre Pakete kommen in unserem sicheren Lager auf Chios an. Der Barcode wird gescannt und im System erfasst.', NOW()),
('de', 'howItWorks.step3.number', '03', NOW()),
('de', 'howItWorks.step3.title', 'Foto-Genehmigung', NOW()),
('de', 'howItWorks.step3.description', 'Das Lagerpersonal macht ein Foto Ihres Pakets. Sie sehen es in Ihrem Panel und überprüfen den Inhalt.', NOW()),
('de', 'howItWorks.step3.desc', 'Das Lagerpersonal macht ein Foto Ihres Pakets. Sie sehen es in Ihrem Panel und überprüfen den Inhalt.', NOW()),
('de', 'howItWorks.step4.number', '04', NOW()),
('de', 'howItWorks.step4.title', 'Abholen', NOW()),
('de', 'howItWorks.step4.description', 'Konsolidieren Sie Ihre Pakete, sparen Sie Geld. Zeigen Sie Ihren QR-Code, holen Sie auf Ihrer Insel ab. So einfach ist das!', NOW()),
('de', 'howItWorks.step4.desc', 'Konsolidieren Sie Ihre Pakete, sparen Sie Geld. Zeigen Sie Ihren QR-Code, holen Sie auf Ihrer Insel ab. So einfach ist das!', NOW()),
('de', 'pricing.tag', 'Transparente Preisgestaltung', NOW()),
('de', 'pricing.title', 'Berechnen Sie Ihre Kosten', NOW()),
('de', 'pricing.description', 'Wählen Sie, wie viele Pakete Sie haben und wie lange Sie sie lagern möchten. Sehen Sie Ihre geschätzten Kosten sofort.', NOW()),
('de', 'pricing.parameters', 'Parameter', NOW()),
('de', 'pricing.packageCount', 'Paketanzahl', NOW()),
('de', 'pricing.storageDays', 'Lagerdauer (Tage)', NOW()),
('de', 'pricing.storage1', '1 Tag', NOW()),
('de', 'pricing.storage30', '30 Tage', NOW()),
('de', 'pricing.freeStorage', 'Erste 14 Tage kostenlose Lagerung', NOW()),
('de', 'pricing.acceptFeeInfo', 'Annahmegebühr pro Paket €4', NOW()),
('de', 'pricing.monthlyCost', 'Geschätzte monatliche Kosten', NOW()),
('de', 'pricing.acceptFee', 'Annahmegebühr', NOW()),
('de', 'pricing.consolidationFee', 'Konsolidierungsgebühr', NOW()),
('de', 'pricing.demurrageFee', 'Verzugsgebühr', NOW()),
('de', 'pricing.total', 'Gesamt', NOW()),
('de', 'pricing.savings', 'Sie können ~€{amount} durch Konsolidierung sparen!', NOW()),
('de', 'pricing.planTitle', 'Wählen Sie den Plan, der zu Ihnen passt', NOW()),
('de', 'pricing.planDesc', 'Tür-zu-Tür-Versand-Privileg von der Türkei nach Europa, Europa in die Türkei', NOW()),
('de', 'pricing.basic.name', 'Basis', NOW()),
('de', 'pricing.basic.price', '€9.99', NOW()),
('de', 'pricing.basic.pricePeriod', '/Monat', NOW()),
('de', 'pricing.basic.subtitle', 'Einfache Adresse, einfache Lieferung', NOW()),
('de', 'pricing.basic.f1', 'ChiosBox EU-Adresse', NOW()),
('de', 'pricing.basic.f2', '14 Tage kostenlose Lagerung', NOW()),
('de', 'pricing.basic.f3', 'Panelzugang', NOW()),
('de', 'pricing.basic.f4', 'E-Mail-Benachrichtigungen', NOW()),
('de', 'pricing.basic.cta', 'Basis-Paket wählen', NOW()),
('de', 'pricing.premium.badge', 'Am beliebtesten', NOW()),
('de', 'pricing.premium.name', 'Premium', NOW()),
('de', 'pricing.premium.subtitle', 'Volle Kontrolle, maximale Ersparnis', NOW()),
('de', 'pricing.premium.f1', 'Alles im Basis-Paket', NOW()),
('de', 'pricing.premium.f2', '21 Tage kostenlose Lagerung', NOW()),
('de', 'pricing.premium.f3', 'Kostenlose Konsolidierung', NOW()),
('de', 'pricing.premium.f4', 'Türkei Lieferverfolgung', NOW()),
('de', 'pricing.premium.f5', 'Dedizierte Support-Hotline', NOW()),
('de', 'pricing.premium.cta', 'Premium-Paket wählen', NOW()),
('de', 'pricing.month', '/Monat', NOW()),
('de', 'pricing.mostPopular', 'Am beliebtesten', NOW()),
('de', 'pricing.fee.accept', 'Annahmegebühr', NOW()),
('de', 'pricing.fee.storage14', '14 Tage kostenlose Lagerung', NOW()),
('de', 'pricing.fee.acceptInfo', 'Annahmegebühr pro Paket €4', NOW()),
('de', 'pricing.fee.acceptUnit', '× €{fee}', NOW()),
('de', 'pricing.demurrageFeeLabel', '{days} Tage × €{fee}', NOW()),
('de', 'trust.tag', 'Vertrauenswürdig & Transparent', NOW()),
('de', 'trust.title', 'Vertrauen Sie uns', NOW()),
('de', 'trust.description', 'Tausende von Nutzern kaufen sicher von der Türkei nach Europa mit ChiosBox.', NOW()),
('de', 'trust.stat1.label', 'Aktive Nutzer', NOW()),
('de', 'trust.stat2.label', 'Gelieferte Pakete', NOW()),
('de', 'trust.stat3.label', 'Zufriedenheitsrate', NOW()),
('de', 'trust.stat4.label', 'Durchschnittliche Lieferung', NOW()),
('de', 'trust.stat4.suffix', 'Tage', NOW()),
('de', 'trust.badge1.title', 'Griechisch IKE Registriert', NOW()),
('de', 'trust.badge1.desc', 'Offiziell registriertes Unternehmen', NOW()),
('de', 'trust.badge2.title', 'SSL 256-Bit-Verschlüsselung', NOW()),
('de', 'trust.badge2.desc', 'Ihre Daten sind sicher', NOW()),
('de', 'trust.badge3.title', 'Stripe Zahlungsinfrastruktur', NOW()),
('de', 'trust.badge3.desc', 'Sichere Online-Zahlung', NOW()),
('de', 'trust.badge4.title', 'EU-konform', NOW()),
('de', 'trust.badge4.desc', 'Konform mit EU-Vorschriften', NOW()),
('de', 'trust.testimonial1.text', 'Ich verwalte alles, was ich aus der Türkei kaufe, über ChiosBox. Durch Konsolidierung sind meine Versandkosten um die Hälfte gesunken.', NOW()),
('de', 'trust.testimonial2.text', 'Das Panel ist sehr einfach zu bedienen. Ich sehe Fotos meiner Pakete und weiß, wann sie ankommen. Toller Service!', NOW()),
('de', 'trust.testimonial3.text', 'Die Abholung per QR-Code ist sehr praktisch. Ich bin zum Büro gegangen, habe den Code gezeigt und mein Paket in 2 Minuten bekommen. Sehr empfehlenswert!', NOW()),
('de', 'finalCta.tag', 'Jetzt starten', NOW()),
('de', 'finalCta.title', 'Jetzt starten', NOW()),
('de', 'finalCta.title1', 'Ihre europäische Lieferadresse', NOW()),
('de', 'finalCta.title2', 'Jetzt holen', NOW()),
('de', 'finalCta.description', 'Ab €9,99/Monat liefern wir Ihre Einkäufe aus der Türkei nahtlos über Chios in die EU.', NOW()),
('de', 'finalCta.cta', 'Jetzt starten', NOW()),